// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package product

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//商品信息
type Product struct {
	Id                         string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BrandId                    int64    `protobuf:"varint,2,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	ProductCategoryId          int64    `protobuf:"varint,3,opt,name=product_category_id,json=productCategoryId,proto3" json:"product_category_id,omitempty"`
	FeightTemplateId           int64    `protobuf:"varint,4,opt,name=feight_template_id,json=feightTemplateId,proto3" json:"feight_template_id,omitempty"`
	ProductAttributeCategoryId int64    `protobuf:"varint,5,opt,name=product_attribute_category_id,json=productAttributeCategoryId,proto3" json:"product_attribute_category_id,omitempty"`
	Name                       string   `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Pic                        string   `protobuf:"bytes,7,opt,name=pic,proto3" json:"pic,omitempty"`
	ProductSn                  string   `protobuf:"bytes,8,opt,name=product_sn,json=productSn,proto3" json:"product_sn,omitempty"`
	DeleteStatus               int64    `protobuf:"varint,9,opt,name=delete_status,json=deleteStatus,proto3" json:"delete_status,omitempty"`
	PublishStatus              int64    `protobuf:"varint,10,opt,name=publish_status,json=publishStatus,proto3" json:"publish_status,omitempty"`
	NewStatus                  int64    `protobuf:"varint,11,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	RecommandStatus            int64    `protobuf:"varint,12,opt,name=recommand_status,json=recommandStatus,proto3" json:"recommand_status,omitempty"`
	VerifyStatus               int64    `protobuf:"varint,13,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`
	Sort                       int64    `protobuf:"varint,14,opt,name=sort,proto3" json:"sort,omitempty"`
	Sale                       int64    `protobuf:"varint,15,opt,name=sale,proto3" json:"sale,omitempty"`
	Price                      float32  `protobuf:"fixed32,16,opt,name=price,proto3" json:"price,omitempty"`
	PromotionPrice             float32  `protobuf:"fixed32,17,opt,name=promotion_price,json=promotionPrice,proto3" json:"promotion_price,omitempty"`
	GiftGrowth                 int64    `protobuf:"varint,18,opt,name=gift_growth,json=giftGrowth,proto3" json:"gift_growth,omitempty"`
	GiftPoint                  int64    `protobuf:"varint,19,opt,name=gift_point,json=giftPoint,proto3" json:"gift_point,omitempty"`
	UsePointLimit              int64    `protobuf:"varint,20,opt,name=use_point_limit,json=usePointLimit,proto3" json:"use_point_limit,omitempty"`
	SubTitle                   string   `protobuf:"bytes,21,opt,name=sub_title,json=subTitle,proto3" json:"sub_title,omitempty"`
	Description                string   `protobuf:"bytes,22,opt,name=description,proto3" json:"description,omitempty"`
	OriginalPrice              float32  `protobuf:"fixed32,23,opt,name=original_price,json=originalPrice,proto3" json:"original_price,omitempty"`
	Stock                      int64    `protobuf:"varint,24,opt,name=stock,proto3" json:"stock,omitempty"`
	LowStock                   int64    `protobuf:"varint,25,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,omitempty"`
	Unit                       string   `protobuf:"bytes,26,opt,name=unit,proto3" json:"unit,omitempty"`
	Weight                     float32  `protobuf:"fixed32,27,opt,name=weight,proto3" json:"weight,omitempty"`
	PreviewStatus              int64    `protobuf:"varint,28,opt,name=preview_status,json=previewStatus,proto3" json:"preview_status,omitempty"`
	ServiceIds                 string   `protobuf:"bytes,29,opt,name=service_ids,json=serviceIds,proto3" json:"service_ids,omitempty"`
	Keywords                   string   `protobuf:"bytes,30,opt,name=keywords,proto3" json:"keywords,omitempty"`
	Note                       string   `protobuf:"bytes,31,opt,name=note,proto3" json:"note,omitempty"`
	AlbumPics                  string   `protobuf:"bytes,32,opt,name=album_pics,json=albumPics,proto3" json:"album_pics,omitempty"`
	DetailTitle                string   `protobuf:"bytes,33,opt,name=detail_title,json=detailTitle,proto3" json:"detail_title,omitempty"`
	DetailDesc                 string   `protobuf:"bytes,34,opt,name=detail_desc,json=detailDesc,proto3" json:"detail_desc,omitempty"`
	DetailHtml                 string   `protobuf:"bytes,35,opt,name=detail_html,json=detailHtml,proto3" json:"detail_html,omitempty"`
	DetailMobileHtml           string   `protobuf:"bytes,36,opt,name=detail_mobile_html,json=detailMobileHtml,proto3" json:"detail_mobile_html,omitempty"`
	PromotionStartTime         string   `protobuf:"bytes,37,opt,name=promotion_start_time,json=promotionStartTime,proto3" json:"promotion_start_time,omitempty"`
	PromotionEndTime           string   `protobuf:"bytes,38,opt,name=promotion_end_time,json=promotionEndTime,proto3" json:"promotion_end_time,omitempty"`
	PromotionPerLimit          int64    `protobuf:"varint,39,opt,name=promotion_per_limit,json=promotionPerLimit,proto3" json:"promotion_per_limit,omitempty"`
	PromotionType              int64    `protobuf:"varint,40,opt,name=promotion_type,json=promotionType,proto3" json:"promotion_type,omitempty"`
	BrandName                  string   `protobuf:"bytes,41,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	ProductCategoryName        string   `protobuf:"bytes,42,opt,name=product_category_name,json=productCategoryName,proto3" json:"product_category_name,omitempty"`
	CreatedTime                string   `protobuf:"bytes,43,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdateTime                 string   `protobuf:"bytes,44,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Product) GetBrandId() int64 {
	if m != nil {
		return m.BrandId
	}
	return 0
}

func (m *Product) GetProductCategoryId() int64 {
	if m != nil {
		return m.ProductCategoryId
	}
	return 0
}

func (m *Product) GetFeightTemplateId() int64 {
	if m != nil {
		return m.FeightTemplateId
	}
	return 0
}

func (m *Product) GetProductAttributeCategoryId() int64 {
	if m != nil {
		return m.ProductAttributeCategoryId
	}
	return 0
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *Product) GetProductSn() string {
	if m != nil {
		return m.ProductSn
	}
	return ""
}

func (m *Product) GetDeleteStatus() int64 {
	if m != nil {
		return m.DeleteStatus
	}
	return 0
}

func (m *Product) GetPublishStatus() int64 {
	if m != nil {
		return m.PublishStatus
	}
	return 0
}

func (m *Product) GetNewStatus() int64 {
	if m != nil {
		return m.NewStatus
	}
	return 0
}

func (m *Product) GetRecommandStatus() int64 {
	if m != nil {
		return m.RecommandStatus
	}
	return 0
}

func (m *Product) GetVerifyStatus() int64 {
	if m != nil {
		return m.VerifyStatus
	}
	return 0
}

func (m *Product) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *Product) GetSale() int64 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Product) GetPromotionPrice() float32 {
	if m != nil {
		return m.PromotionPrice
	}
	return 0
}

func (m *Product) GetGiftGrowth() int64 {
	if m != nil {
		return m.GiftGrowth
	}
	return 0
}

func (m *Product) GetGiftPoint() int64 {
	if m != nil {
		return m.GiftPoint
	}
	return 0
}

func (m *Product) GetUsePointLimit() int64 {
	if m != nil {
		return m.UsePointLimit
	}
	return 0
}

func (m *Product) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetOriginalPrice() float32 {
	if m != nil {
		return m.OriginalPrice
	}
	return 0
}

func (m *Product) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *Product) GetLowStock() int64 {
	if m != nil {
		return m.LowStock
	}
	return 0
}

func (m *Product) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *Product) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Product) GetPreviewStatus() int64 {
	if m != nil {
		return m.PreviewStatus
	}
	return 0
}

func (m *Product) GetServiceIds() string {
	if m != nil {
		return m.ServiceIds
	}
	return ""
}

func (m *Product) GetKeywords() string {
	if m != nil {
		return m.Keywords
	}
	return ""
}

func (m *Product) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Product) GetAlbumPics() string {
	if m != nil {
		return m.AlbumPics
	}
	return ""
}

func (m *Product) GetDetailTitle() string {
	if m != nil {
		return m.DetailTitle
	}
	return ""
}

func (m *Product) GetDetailDesc() string {
	if m != nil {
		return m.DetailDesc
	}
	return ""
}

func (m *Product) GetDetailHtml() string {
	if m != nil {
		return m.DetailHtml
	}
	return ""
}

func (m *Product) GetDetailMobileHtml() string {
	if m != nil {
		return m.DetailMobileHtml
	}
	return ""
}

func (m *Product) GetPromotionStartTime() string {
	if m != nil {
		return m.PromotionStartTime
	}
	return ""
}

func (m *Product) GetPromotionEndTime() string {
	if m != nil {
		return m.PromotionEndTime
	}
	return ""
}

func (m *Product) GetPromotionPerLimit() int64 {
	if m != nil {
		return m.PromotionPerLimit
	}
	return 0
}

func (m *Product) GetPromotionType() int64 {
	if m != nil {
		return m.PromotionType
	}
	return 0
}

func (m *Product) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *Product) GetProductCategoryName() string {
	if m != nil {
		return m.ProductCategoryName
	}
	return ""
}

func (m *Product) GetCreatedTime() string {
	if m != nil {
		return m.CreatedTime
	}
	return ""
}

func (m *Product) GetUpdateTime() string {
	if m != nil {
		return m.UpdateTime
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetProductById struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductById) Reset()         { *m = In_GetProductById{} }
func (m *In_GetProductById) String() string { return proto.CompactTextString(m) }
func (*In_GetProductById) ProtoMessage()    {}
func (*In_GetProductById) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *In_GetProductById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductById.Unmarshal(m, b)
}
func (m *In_GetProductById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductById.Marshal(b, m, deterministic)
}
func (m *In_GetProductById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductById.Merge(m, src)
}
func (m *In_GetProductById) XXX_Size() int {
	return xxx_messageInfo_In_GetProductById.Size(m)
}
func (m *In_GetProductById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductById proto.InternalMessageInfo

func (m *In_GetProductById) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Out_GetProductById struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Product              *ProductDetails `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Out_GetProductById) Reset()         { *m = Out_GetProductById{} }
func (m *Out_GetProductById) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductById) ProtoMessage()    {}
func (*Out_GetProductById) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{3}
}

func (m *Out_GetProductById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductById.Unmarshal(m, b)
}
func (m *Out_GetProductById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductById.Marshal(b, m, deterministic)
}
func (m *Out_GetProductById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductById.Merge(m, src)
}
func (m *Out_GetProductById) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductById.Size(m)
}
func (m *Out_GetProductById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductById proto.InternalMessageInfo

func (m *Out_GetProductById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductById) GetProduct() *ProductDetails {
	if m != nil {
		return m.Product
	}
	return nil
}

type Out_UpdateProductInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Product              *Product `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_UpdateProductInfo) Reset()         { *m = Out_UpdateProductInfo{} }
func (m *Out_UpdateProductInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateProductInfo) ProtoMessage()    {}
func (*Out_UpdateProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{4}
}

func (m *Out_UpdateProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateProductInfo.Unmarshal(m, b)
}
func (m *Out_UpdateProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateProductInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateProductInfo.Merge(m, src)
}
func (m *Out_UpdateProductInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateProductInfo.Size(m)
}
func (m *Out_UpdateProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateProductInfo proto.InternalMessageInfo

func (m *Out_UpdateProductInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateProductInfo) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type In_UpdateProductInfo struct {
	Product              *ProductDetails `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *In_UpdateProductInfo) Reset()         { *m = In_UpdateProductInfo{} }
func (m *In_UpdateProductInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateProductInfo) ProtoMessage()    {}
func (*In_UpdateProductInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{5}
}

func (m *In_UpdateProductInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateProductInfo.Unmarshal(m, b)
}
func (m *In_UpdateProductInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateProductInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateProductInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateProductInfo.Merge(m, src)
}
func (m *In_UpdateProductInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateProductInfo.Size(m)
}
func (m *In_UpdateProductInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateProductInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateProductInfo proto.InternalMessageInfo

func (m *In_UpdateProductInfo) GetProduct() *ProductDetails {
	if m != nil {
		return m.Product
	}
	return nil
}

type In_GetProducts struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProducts) Reset()         { *m = In_GetProducts{} }
func (m *In_GetProducts) String() string { return proto.CompactTextString(m) }
func (*In_GetProducts) ProtoMessage()    {}
func (*In_GetProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{6}
}

func (m *In_GetProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProducts.Unmarshal(m, b)
}
func (m *In_GetProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProducts.Marshal(b, m, deterministic)
}
func (m *In_GetProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProducts.Merge(m, src)
}
func (m *In_GetProducts) XXX_Size() int {
	return xxx_messageInfo_In_GetProducts.Size(m)
}
func (m *In_GetProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProducts.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProducts proto.InternalMessageInfo

func (m *In_GetProducts) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetProducts) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetProducts) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetProducts) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetProducts) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetProducts struct {
	Error                *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64      `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductList          []*Product `protobuf:"bytes,5,rep,name=product_list,json=productList,proto3" json:"product_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Out_GetProducts) Reset()         { *m = Out_GetProducts{} }
func (m *Out_GetProducts) String() string { return proto.CompactTextString(m) }
func (*Out_GetProducts) ProtoMessage()    {}
func (*Out_GetProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{7}
}

func (m *Out_GetProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProducts.Unmarshal(m, b)
}
func (m *Out_GetProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProducts.Marshal(b, m, deterministic)
}
func (m *Out_GetProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProducts.Merge(m, src)
}
func (m *Out_GetProducts) XXX_Size() int {
	return xxx_messageInfo_Out_GetProducts.Size(m)
}
func (m *Out_GetProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProducts.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProducts proto.InternalMessageInfo

func (m *Out_GetProducts) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProducts) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetProducts) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetProducts) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetProducts) GetProductList() []*Product {
	if m != nil {
		return m.ProductList
	}
	return nil
}

type In_DeleteProducts struct {
	DeleteStatus         int64    `protobuf:"varint,1,opt,name=delete_status,json=deleteStatus,proto3" json:"delete_status,omitempty"`
	ProductList          []string `protobuf:"bytes,2,rep,name=product_list,json=productList,proto3" json:"product_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_DeleteProducts) Reset()         { *m = In_DeleteProducts{} }
func (m *In_DeleteProducts) String() string { return proto.CompactTextString(m) }
func (*In_DeleteProducts) ProtoMessage()    {}
func (*In_DeleteProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{8}
}

func (m *In_DeleteProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteProducts.Unmarshal(m, b)
}
func (m *In_DeleteProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteProducts.Marshal(b, m, deterministic)
}
func (m *In_DeleteProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteProducts.Merge(m, src)
}
func (m *In_DeleteProducts) XXX_Size() int {
	return xxx_messageInfo_In_DeleteProducts.Size(m)
}
func (m *In_DeleteProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteProducts.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteProducts proto.InternalMessageInfo

func (m *In_DeleteProducts) GetDeleteStatus() int64 {
	if m != nil {
		return m.DeleteStatus
	}
	return 0
}

func (m *In_DeleteProducts) GetProductList() []string {
	if m != nil {
		return m.ProductList
	}
	return nil
}

type Out_DeleteProducts struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteProducts) Reset()         { *m = Out_DeleteProducts{} }
func (m *Out_DeleteProducts) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteProducts) ProtoMessage()    {}
func (*Out_DeleteProducts) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{9}
}

func (m *Out_DeleteProducts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteProducts.Unmarshal(m, b)
}
func (m *Out_DeleteProducts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteProducts.Marshal(b, m, deterministic)
}
func (m *Out_DeleteProducts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteProducts.Merge(m, src)
}
func (m *Out_DeleteProducts) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteProducts.Size(m)
}
func (m *Out_DeleteProducts) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteProducts.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteProducts proto.InternalMessageInfo

func (m *Out_DeleteProducts) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ProductMemberPrice struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	MemberLevelId        int64    `protobuf:"varint,3,opt,name=member_level_id,json=memberLevelId,proto3" json:"member_level_id,omitempty"`
	MemberPrice          float32  `protobuf:"fixed32,4,opt,name=member_price,json=memberPrice,proto3" json:"member_price,omitempty"`
	MemberLevelName      string   `protobuf:"bytes,5,opt,name=member_level_name,json=memberLevelName,proto3" json:"member_level_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductMemberPrice) Reset()         { *m = ProductMemberPrice{} }
func (m *ProductMemberPrice) String() string { return proto.CompactTextString(m) }
func (*ProductMemberPrice) ProtoMessage()    {}
func (*ProductMemberPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{10}
}

func (m *ProductMemberPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductMemberPrice.Unmarshal(m, b)
}
func (m *ProductMemberPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductMemberPrice.Marshal(b, m, deterministic)
}
func (m *ProductMemberPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductMemberPrice.Merge(m, src)
}
func (m *ProductMemberPrice) XXX_Size() int {
	return xxx_messageInfo_ProductMemberPrice.Size(m)
}
func (m *ProductMemberPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductMemberPrice.DiscardUnknown(m)
}

var xxx_messageInfo_ProductMemberPrice proto.InternalMessageInfo

func (m *ProductMemberPrice) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductMemberPrice) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductMemberPrice) GetMemberLevelId() int64 {
	if m != nil {
		return m.MemberLevelId
	}
	return 0
}

func (m *ProductMemberPrice) GetMemberPrice() float32 {
	if m != nil {
		return m.MemberPrice
	}
	return 0
}

func (m *ProductMemberPrice) GetMemberLevelName() string {
	if m != nil {
		return m.MemberLevelName
	}
	return ""
}

type ProductFullReduction struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FullPrice            float32  `protobuf:"fixed32,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	ReducePrice          float32  `protobuf:"fixed32,4,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductFullReduction) Reset()         { *m = ProductFullReduction{} }
func (m *ProductFullReduction) String() string { return proto.CompactTextString(m) }
func (*ProductFullReduction) ProtoMessage()    {}
func (*ProductFullReduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{11}
}

func (m *ProductFullReduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductFullReduction.Unmarshal(m, b)
}
func (m *ProductFullReduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductFullReduction.Marshal(b, m, deterministic)
}
func (m *ProductFullReduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductFullReduction.Merge(m, src)
}
func (m *ProductFullReduction) XXX_Size() int {
	return xxx_messageInfo_ProductFullReduction.Size(m)
}
func (m *ProductFullReduction) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductFullReduction.DiscardUnknown(m)
}

var xxx_messageInfo_ProductFullReduction proto.InternalMessageInfo

func (m *ProductFullReduction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductFullReduction) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductFullReduction) GetFullPrice() float32 {
	if m != nil {
		return m.FullPrice
	}
	return 0
}

func (m *ProductFullReduction) GetReducePrice() float32 {
	if m != nil {
		return m.ReducePrice
	}
	return 0
}

type ProductLadder struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	Discount             float32  `protobuf:"fixed32,4,opt,name=discount,proto3" json:"discount,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductLadder) Reset()         { *m = ProductLadder{} }
func (m *ProductLadder) String() string { return proto.CompactTextString(m) }
func (*ProductLadder) ProtoMessage()    {}
func (*ProductLadder) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{12}
}

func (m *ProductLadder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductLadder.Unmarshal(m, b)
}
func (m *ProductLadder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductLadder.Marshal(b, m, deterministic)
}
func (m *ProductLadder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductLadder.Merge(m, src)
}
func (m *ProductLadder) XXX_Size() int {
	return xxx_messageInfo_ProductLadder.Size(m)
}
func (m *ProductLadder) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductLadder.DiscardUnknown(m)
}

var xxx_messageInfo_ProductLadder proto.InternalMessageInfo

func (m *ProductLadder) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductLadder) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductLadder) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *ProductLadder) GetDiscount() float32 {
	if m != nil {
		return m.Discount
	}
	return 0
}

func (m *ProductLadder) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

//sku的库存
type ProductSkuStock struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuCode              string   `protobuf:"bytes,3,opt,name=sku_code,json=skuCode,proto3" json:"sku_code,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Stock                int64    `protobuf:"varint,5,opt,name=stock,proto3" json:"stock,omitempty"`
	Sp1                  string   `protobuf:"bytes,6,opt,name=sp1,proto3" json:"sp1,omitempty"`
	Sp2                  string   `protobuf:"bytes,7,opt,name=sp2,proto3" json:"sp2,omitempty"`
	Sp3                  string   `protobuf:"bytes,8,opt,name=sp3,proto3" json:"sp3,omitempty"`
	Pic                  string   `protobuf:"bytes,9,opt,name=pic,proto3" json:"pic,omitempty"`
	Sale                 int64    `protobuf:"varint,10,opt,name=sale,proto3" json:"sale,omitempty"`
	PromotionPrice       float32  `protobuf:"fixed32,11,opt,name=promotion_price,json=promotionPrice,proto3" json:"promotion_price,omitempty"`
	LockStock            int64    `protobuf:"varint,12,opt,name=lock_stock,json=lockStock,proto3" json:"lock_stock,omitempty"`
	LowStock             int64    `protobuf:"varint,13,opt,name=low_stock,json=lowStock,proto3" json:"low_stock,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductSkuStock) Reset()         { *m = ProductSkuStock{} }
func (m *ProductSkuStock) String() string { return proto.CompactTextString(m) }
func (*ProductSkuStock) ProtoMessage()    {}
func (*ProductSkuStock) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{13}
}

func (m *ProductSkuStock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductSkuStock.Unmarshal(m, b)
}
func (m *ProductSkuStock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductSkuStock.Marshal(b, m, deterministic)
}
func (m *ProductSkuStock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductSkuStock.Merge(m, src)
}
func (m *ProductSkuStock) XXX_Size() int {
	return xxx_messageInfo_ProductSkuStock.Size(m)
}
func (m *ProductSkuStock) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductSkuStock.DiscardUnknown(m)
}

var xxx_messageInfo_ProductSkuStock proto.InternalMessageInfo

func (m *ProductSkuStock) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductSkuStock) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductSkuStock) GetSkuCode() string {
	if m != nil {
		return m.SkuCode
	}
	return ""
}

func (m *ProductSkuStock) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductSkuStock) GetStock() int64 {
	if m != nil {
		return m.Stock
	}
	return 0
}

func (m *ProductSkuStock) GetSp1() string {
	if m != nil {
		return m.Sp1
	}
	return ""
}

func (m *ProductSkuStock) GetSp2() string {
	if m != nil {
		return m.Sp2
	}
	return ""
}

func (m *ProductSkuStock) GetSp3() string {
	if m != nil {
		return m.Sp3
	}
	return ""
}

func (m *ProductSkuStock) GetPic() string {
	if m != nil {
		return m.Pic
	}
	return ""
}

func (m *ProductSkuStock) GetSale() int64 {
	if m != nil {
		return m.Sale
	}
	return 0
}

func (m *ProductSkuStock) GetPromotionPrice() float32 {
	if m != nil {
		return m.PromotionPrice
	}
	return 0
}

func (m *ProductSkuStock) GetLockStock() int64 {
	if m != nil {
		return m.LockStock
	}
	return 0
}

func (m *ProductSkuStock) GetLowStock() int64 {
	if m != nil {
		return m.LowStock
	}
	return 0
}

type ProductAttributeValue struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ProductAttributeId   int64    `protobuf:"varint,3,opt,name=product_attribute_id,json=productAttributeId,proto3" json:"product_attribute_id,omitempty"`
	Value                string   `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductAttributeValue) Reset()         { *m = ProductAttributeValue{} }
func (m *ProductAttributeValue) String() string { return proto.CompactTextString(m) }
func (*ProductAttributeValue) ProtoMessage()    {}
func (*ProductAttributeValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{14}
}

func (m *ProductAttributeValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttributeValue.Unmarshal(m, b)
}
func (m *ProductAttributeValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttributeValue.Marshal(b, m, deterministic)
}
func (m *ProductAttributeValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttributeValue.Merge(m, src)
}
func (m *ProductAttributeValue) XXX_Size() int {
	return xxx_messageInfo_ProductAttributeValue.Size(m)
}
func (m *ProductAttributeValue) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttributeValue.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttributeValue proto.InternalMessageInfo

func (m *ProductAttributeValue) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductAttributeValue) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductAttributeValue) GetProductAttributeId() int64 {
	if m != nil {
		return m.ProductAttributeId
	}
	return 0
}

func (m *ProductAttributeValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type ProductDetails struct {
	Product                   *Product                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	ProductMemberPriceList    []*ProductMemberPrice    `protobuf:"bytes,2,rep,name=productMemberPriceList,proto3" json:"productMemberPriceList,omitempty"`
	ProductFullReductionList  []*ProductFullReduction  `protobuf:"bytes,3,rep,name=productFullReductionList,proto3" json:"productFullReductionList,omitempty"`
	ProductLadderList         []*ProductLadder         `protobuf:"bytes,4,rep,name=productLadderList,proto3" json:"productLadderList,omitempty"`
	ProductSkuStockList       []*ProductSkuStock       `protobuf:"bytes,5,rep,name=productSkuStockList,proto3" json:"productSkuStockList,omitempty"`
	ProductAttributeValueList []*ProductAttributeValue `protobuf:"bytes,6,rep,name=productAttributeValueList,proto3" json:"productAttributeValueList,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                 `json:"-"`
	XXX_unrecognized          []byte                   `json:"-"`
	XXX_sizecache             int32                    `json:"-"`
}

func (m *ProductDetails) Reset()         { *m = ProductDetails{} }
func (m *ProductDetails) String() string { return proto.CompactTextString(m) }
func (*ProductDetails) ProtoMessage()    {}
func (*ProductDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{15}
}

func (m *ProductDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductDetails.Unmarshal(m, b)
}
func (m *ProductDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductDetails.Marshal(b, m, deterministic)
}
func (m *ProductDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductDetails.Merge(m, src)
}
func (m *ProductDetails) XXX_Size() int {
	return xxx_messageInfo_ProductDetails.Size(m)
}
func (m *ProductDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductDetails.DiscardUnknown(m)
}

var xxx_messageInfo_ProductDetails proto.InternalMessageInfo

func (m *ProductDetails) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *ProductDetails) GetProductMemberPriceList() []*ProductMemberPrice {
	if m != nil {
		return m.ProductMemberPriceList
	}
	return nil
}

func (m *ProductDetails) GetProductFullReductionList() []*ProductFullReduction {
	if m != nil {
		return m.ProductFullReductionList
	}
	return nil
}

func (m *ProductDetails) GetProductLadderList() []*ProductLadder {
	if m != nil {
		return m.ProductLadderList
	}
	return nil
}

func (m *ProductDetails) GetProductSkuStockList() []*ProductSkuStock {
	if m != nil {
		return m.ProductSkuStockList
	}
	return nil
}

func (m *ProductDetails) GetProductAttributeValueList() []*ProductAttributeValue {
	if m != nil {
		return m.ProductAttributeValueList
	}
	return nil
}

type In_CreateProduct struct {
	ProductDetail        *ProductDetails `protobuf:"bytes,1,opt,name=productDetail,proto3" json:"productDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *In_CreateProduct) Reset()         { *m = In_CreateProduct{} }
func (m *In_CreateProduct) String() string { return proto.CompactTextString(m) }
func (*In_CreateProduct) ProtoMessage()    {}
func (*In_CreateProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{16}
}

func (m *In_CreateProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateProduct.Unmarshal(m, b)
}
func (m *In_CreateProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateProduct.Marshal(b, m, deterministic)
}
func (m *In_CreateProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateProduct.Merge(m, src)
}
func (m *In_CreateProduct) XXX_Size() int {
	return xxx_messageInfo_In_CreateProduct.Size(m)
}
func (m *In_CreateProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateProduct.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateProduct proto.InternalMessageInfo

func (m *In_CreateProduct) GetProductDetail() *ProductDetails {
	if m != nil {
		return m.ProductDetail
	}
	return nil
}

type Out_CreateProduct struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductDetail        *ProductDetails `protobuf:"bytes,2,opt,name=productDetail,proto3" json:"productDetail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Out_CreateProduct) Reset()         { *m = Out_CreateProduct{} }
func (m *Out_CreateProduct) String() string { return proto.CompactTextString(m) }
func (*Out_CreateProduct) ProtoMessage()    {}
func (*Out_CreateProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{17}
}

func (m *Out_CreateProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateProduct.Unmarshal(m, b)
}
func (m *Out_CreateProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateProduct.Marshal(b, m, deterministic)
}
func (m *Out_CreateProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateProduct.Merge(m, src)
}
func (m *Out_CreateProduct) XXX_Size() int {
	return xxx_messageInfo_Out_CreateProduct.Size(m)
}
func (m *Out_CreateProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateProduct.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateProduct proto.InternalMessageInfo

func (m *Out_CreateProduct) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateProduct) GetProductDetail() *ProductDetails {
	if m != nil {
		return m.ProductDetail
	}
	return nil
}

func init() {
	proto.RegisterType((*Product)(nil), "product.Product")
	proto.RegisterType((*Error)(nil), "product.Error")
	proto.RegisterType((*In_GetProductById)(nil), "product.In_GetProductById")
	proto.RegisterType((*Out_GetProductById)(nil), "product.Out_GetProductById")
	proto.RegisterType((*Out_UpdateProductInfo)(nil), "product.Out_UpdateProductInfo")
	proto.RegisterType((*In_UpdateProductInfo)(nil), "product.In_UpdateProductInfo")
	proto.RegisterType((*In_GetProducts)(nil), "product.In_GetProducts")
	proto.RegisterType((*Out_GetProducts)(nil), "product.Out_GetProducts")
	proto.RegisterType((*In_DeleteProducts)(nil), "product.In_DeleteProducts")
	proto.RegisterType((*Out_DeleteProducts)(nil), "product.Out_DeleteProducts")
	proto.RegisterType((*ProductMemberPrice)(nil), "product.Product_member_price")
	proto.RegisterType((*ProductFullReduction)(nil), "product.Product_full_reduction")
	proto.RegisterType((*ProductLadder)(nil), "product.Product_ladder")
	proto.RegisterType((*ProductSkuStock)(nil), "product.Product_sku_stock")
	proto.RegisterType((*ProductAttributeValue)(nil), "product.Product_attribute_value")
	proto.RegisterType((*ProductDetails)(nil), "product.ProductDetails")
	proto.RegisterType((*In_CreateProduct)(nil), "product.In_CreateProduct")
	proto.RegisterType((*Out_CreateProduct)(nil), "product.Out_CreateProduct")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 1624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x52, 0x1b, 0x47,
	0x16, 0x46, 0x12, 0x02, 0x74, 0x84, 0x84, 0x68, 0xcb, 0xd0, 0xc8, 0x2b, 0x23, 0x06, 0xff, 0x60,
	0xaf, 0xcb, 0xb5, 0xc6, 0xb5, 0x37, 0x5b, 0xb5, 0x17, 0xfe, 0x5b, 0x5b, 0x65, 0xbc, 0x21, 0x02,
	0xe7, 0xc6, 0x55, 0x99, 0x1a, 0xcd, 0x34, 0xd0, 0xc5, 0xfc, 0xa8, 0xa6, 0x7b, 0x20, 0x3c, 0x41,
	0x2a, 0x37, 0xa9, 0xdc, 0xe4, 0x35, 0xf2, 0x04, 0x79, 0x82, 0xbc, 0x45, 0x2e, 0xf2, 0x1e, 0xa9,
	0x3e, 0xdd, 0x33, 0x9a, 0xd1, 0x88, 0x32, 0xdc, 0x4d, 0x7f, 0xe7, 0xeb, 0x73, 0x4e, 0x77, 0x9f,
	0x3f, 0x09, 0x5a, 0x93, 0x38, 0xf2, 0x12, 0x57, 0x3e, 0x9f, 0xc4, 0x91, 0x8c, 0xc8, 0xb2, 0x59,
	0x5a, 0x7f, 0x36, 0x61, 0xf9, 0x50, 0x7f, 0x93, 0x36, 0x54, 0xb9, 0x47, 0x2b, 0x83, 0xca, 0x5e,
	0x63, 0x54, 0xe5, 0x1e, 0xd9, 0x82, 0x95, 0x71, 0xec, 0x84, 0x9e, 0xcd, 0x3d, 0x5a, 0x1d, 0x54,
	0xf6, 0x6a, 0xa3, 0x65, 0x5c, 0x0f, 0x3d, 0xf2, 0x1c, 0xee, 0x18, 0x0d, 0xb6, 0xeb, 0x48, 0x76,
	0x1a, 0xc5, 0x57, 0x8a, 0x55, 0x43, 0xd6, 0xba, 0x11, 0xbd, 0x31, 0x92, 0xa1, 0x47, 0x9e, 0x01,
	0x39, 0x61, 0xfc, 0xf4, 0x4c, 0xda, 0x92, 0x05, 0x13, 0xdf, 0x91, 0x4c, 0xd1, 0x17, 0x91, 0xde,
	0xd1, 0x92, 0x63, 0x23, 0x18, 0x7a, 0xe4, 0x15, 0xf4, 0x53, 0xed, 0x8e, 0x94, 0x31, 0x1f, 0x27,
	0x92, 0x15, 0xec, 0xd4, 0x71, 0x63, 0xcf, 0x90, 0x5e, 0xa5, 0x9c, 0x9c, 0x41, 0x02, 0x8b, 0xa1,
	0x13, 0x30, 0xba, 0x84, 0xa7, 0xc1, 0x6f, 0xd2, 0x81, 0xda, 0x84, 0xbb, 0x74, 0x19, 0x21, 0xf5,
	0x49, 0xfa, 0x00, 0xa9, 0x21, 0x11, 0xd2, 0x15, 0x14, 0x34, 0x0c, 0x72, 0x14, 0x92, 0x5d, 0x68,
	0x79, 0xcc, 0x67, 0x92, 0xd9, 0x42, 0x3a, 0x32, 0x11, 0xb4, 0x81, 0x76, 0x57, 0x35, 0x78, 0x84,
	0x18, 0x79, 0x08, 0xed, 0x49, 0x32, 0xf6, 0xb9, 0x38, 0x4b, 0x59, 0x80, 0xac, 0x96, 0x41, 0x0d,
	0xad, 0x0f, 0x10, 0xb2, 0xcb, 0x94, 0xd2, 0x44, 0x4a, 0x23, 0x64, 0x97, 0x46, 0xfc, 0x04, 0x3a,
	0x31, 0x73, 0xa3, 0x20, 0x50, 0xf7, 0x6d, 0x48, 0xab, 0x48, 0x5a, 0xcb, 0x70, 0x43, 0xdd, 0x85,
	0xd6, 0x05, 0x8b, 0xf9, 0xc9, 0x55, 0xca, 0x6b, 0x69, 0xaf, 0x34, 0x68, 0x48, 0x04, 0x16, 0x45,
	0x14, 0x4b, 0xda, 0x46, 0x19, 0x7e, 0x23, 0xe6, 0xf8, 0x8c, 0xae, 0x19, 0xcc, 0xf1, 0x19, 0xe9,
	0x42, 0x7d, 0x12, 0x73, 0x97, 0xd1, 0xce, 0xa0, 0xb2, 0x57, 0x1d, 0xe9, 0x05, 0x79, 0x0c, 0x6b,
	0x93, 0x38, 0x0a, 0x22, 0xc9, 0xa3, 0xd0, 0xd6, 0xf2, 0x75, 0x94, 0xb7, 0x33, 0xf8, 0x10, 0x89,
	0xdb, 0xd0, 0x3c, 0xe5, 0x27, 0xd2, 0x3e, 0x8d, 0xa3, 0x4b, 0x79, 0x46, 0x09, 0x6a, 0x06, 0x05,
	0xbd, 0x47, 0x44, 0x1d, 0x1b, 0x09, 0x93, 0x88, 0x87, 0x92, 0xde, 0xd1, 0xc7, 0x56, 0xc8, 0xa1,
	0x02, 0xc8, 0x23, 0x58, 0x4b, 0x04, 0xd3, 0x52, 0xdb, 0xe7, 0x01, 0x97, 0xb4, 0xab, 0x6f, 0x2f,
	0x11, 0x0c, 0x29, 0x07, 0x0a, 0x24, 0xf7, 0xa0, 0x21, 0x92, 0xb1, 0x2d, 0xb9, 0xf4, 0x19, 0xbd,
	0x8b, 0xef, 0xb4, 0x22, 0x92, 0xf1, 0xb1, 0x5a, 0x93, 0x01, 0x34, 0x3d, 0x26, 0xdc, 0x98, 0x4f,
	0x94, 0x63, 0x74, 0x03, 0xc5, 0x79, 0x48, 0xbd, 0x51, 0x14, 0xf3, 0x53, 0x1e, 0x3a, 0xbe, 0x39,
	0xce, 0x26, 0x1e, 0xa7, 0x95, 0xa2, 0xfa, 0x34, 0x5d, 0xa8, 0x0b, 0x19, 0xb9, 0xe7, 0x94, 0xa2,
	0x0f, 0x7a, 0xa1, 0x6c, 0xfb, 0x91, 0x7a, 0x39, 0x25, 0xd9, 0x42, 0xc9, 0x8a, 0x1f, 0x5d, 0x1e,
	0xa1, 0x90, 0xc0, 0x62, 0x12, 0x72, 0x49, 0x7b, 0x3a, 0xce, 0xd4, 0x37, 0xd9, 0x80, 0xa5, 0x4b,
	0x0c, 0x69, 0x7a, 0x0f, 0xad, 0x98, 0x15, 0x46, 0x4a, 0xcc, 0x2e, 0xf8, 0x34, 0x0c, 0xfe, 0x61,
	0x22, 0x45, 0xa3, 0xe6, 0xe9, 0xb6, 0xa1, 0x29, 0x58, 0x7c, 0xc1, 0x5d, 0x95, 0x23, 0x82, 0xf6,
	0x51, 0x33, 0x18, 0x68, 0xe8, 0x09, 0xd2, 0x83, 0x95, 0x73, 0x76, 0x75, 0x19, 0xc5, 0x9e, 0xa0,
	0xf7, 0xf5, 0x5d, 0xa4, 0x6b, 0x8c, 0xfb, 0x48, 0x32, 0xba, 0x6d, 0xe2, 0x3e, 0x92, 0x4c, 0xbd,
	0x81, 0xe3, 0x8f, 0x93, 0xc0, 0x9e, 0x70, 0x57, 0xd0, 0x81, 0x8e, 0x72, 0x44, 0x0e, 0xb9, 0x2b,
	0xc8, 0x0e, 0xac, 0x7a, 0x4c, 0x3a, 0xdc, 0x37, 0xd7, 0xbb, 0x93, 0xde, 0x9f, 0xc2, 0xf4, 0x0d,
	0x6f, 0x83, 0x59, 0xda, 0xea, 0x56, 0xa9, 0xa5, 0x5d, 0xd2, 0xd0, 0x5b, 0x26, 0xdc, 0x1c, 0xe1,
	0x4c, 0x06, 0x3e, 0xdd, 0xcd, 0x13, 0x3e, 0xc8, 0xc0, 0x57, 0x05, 0xc0, 0x10, 0x82, 0x68, 0xcc,
	0x7d, 0xa6, 0x79, 0x0f, 0x90, 0xd7, 0xd1, 0x92, 0x4f, 0x28, 0x40, 0xf6, 0xbf, 0xa0, 0x3b, 0x8d,
	0x3f, 0x21, 0x9d, 0x58, 0xda, 0x92, 0x07, 0x8c, 0x3e, 0x44, 0x3e, 0xc9, 0x64, 0x47, 0x4a, 0x74,
	0xcc, 0x03, 0xa6, 0xf4, 0x4f, 0x77, 0xb0, 0xd0, 0xd3, 0xfc, 0x47, 0x5a, 0x7f, 0x26, 0x79, 0x17,
	0x7a, 0xc8, 0xd6, 0xe5, 0x2b, 0x8d, 0x6f, 0x16, 0x9b, 0xd0, 0x7b, 0x9c, 0x95, 0x2f, 0x13, 0xe3,
	0x2c, 0xd6, 0xe1, 0x87, 0x2f, 0x97, 0xf2, 0xe5, 0xd5, 0x84, 0xd1, 0xbd, 0xf4, 0xe5, 0x0c, 0x7a,
	0x7c, 0x35, 0xc1, 0x8b, 0xd6, 0x05, 0x13, 0x4b, 0xcf, 0x13, 0x7d, 0xd1, 0x88, 0xfc, 0x5f, 0xd5,
	0x9f, 0x7d, 0xb8, 0x5b, 0x2a, 0x9a, 0xc8, 0x7c, 0x8a, 0xcc, 0x3b, 0x33, 0x65, 0x13, 0xf7, 0xec,
	0xc0, 0xaa, 0x1b, 0x33, 0x47, 0x32, 0x73, 0xa2, 0x7f, 0xea, 0xc7, 0x31, 0x18, 0x1e, 0x66, 0x1b,
	0x9a, 0xc9, 0xc4, 0x53, 0x25, 0x15, 0x19, 0xcf, 0xf4, 0xdd, 0x6b, 0x48, 0x11, 0xac, 0x7f, 0x43,
	0xfd, 0x5d, 0x1c, 0x47, 0xb1, 0x0a, 0x0e, 0x37, 0xf2, 0x18, 0x96, 0xf8, 0xfa, 0x08, 0xbf, 0x09,
	0x85, 0xe5, 0x80, 0x09, 0xe1, 0x9c, 0x32, 0xac, 0xf1, 0x8d, 0x51, 0xba, 0xb4, 0x76, 0x61, 0x7d,
	0x18, 0xda, 0xef, 0x99, 0x34, 0xfd, 0xe1, 0xb5, 0xaa, 0xab, 0x33, 0x3d, 0xc2, 0x0a, 0x80, 0x7c,
	0x93, 0xc8, 0x59, 0xd6, 0x03, 0xa8, 0x33, 0x65, 0x11, 0x89, 0xcd, 0xfd, 0xf6, 0xf3, 0xb4, 0xfb,
	0xa0, 0x1f, 0x23, 0x2d, 0x24, 0x2f, 0x20, 0x6d, 0x43, 0x68, 0xba, 0xb9, 0xbf, 0x99, 0xf1, 0x8c,
	0xb2, 0xb7, 0x18, 0x18, 0x62, 0x94, 0xb5, 0x2b, 0x0e, 0x77, 0x95, 0xb9, 0xcf, 0x78, 0x38, 0x43,
	0x1a, 0x86, 0x27, 0xd1, 0x0d, 0x2d, 0x3e, 0x9d, 0xb5, 0xd8, 0x99, 0xb5, 0x38, 0x35, 0x35, 0x84,
	0xee, 0x30, 0x9c, 0x63, 0x29, 0xe7, 0x75, 0xe5, 0x86, 0x5e, 0xff, 0x5a, 0x81, 0x76, 0xe1, 0x2a,
	0x85, 0x2a, 0x35, 0x3a, 0xe6, 0x2a, 0xba, 0xd4, 0xe0, 0x02, 0xab, 0xb1, 0x73, 0xca, 0x84, 0x69,
	0xb7, 0x7a, 0xa1, 0xc2, 0x4a, 0x30, 0x27, 0x76, 0xcf, 0xec, 0x73, 0x76, 0x85, 0x3d, 0xb6, 0x31,
	0x6a, 0x68, 0xe4, 0x23, 0xbb, 0x42, 0xf1, 0x34, 0x45, 0x16, 0x8d, 0x38, 0xcb, 0x8c, 0x2d, 0x58,
	0xc9, 0xf2, 0xa1, 0xae, 0x5f, 0x98, 0xe9, 0x34, 0xb0, 0x7e, 0xab, 0xc0, 0x5a, 0xf1, 0xf5, 0xc4,
	0x0d, 0x2f, 0x32, 0x73, 0xbf, 0x3a, 0xd7, 0xfd, 0x5a, 0xde, 0xfd, 0x2e, 0xd4, 0x65, 0x24, 0x1d,
	0xdf, 0xb4, 0x7b, 0xbd, 0x20, 0x2f, 0x61, 0x35, 0x4d, 0x06, 0x9f, 0x0b, 0x49, 0xeb, 0x83, 0xda,
	0xdc, 0xf7, 0x68, 0x1a, 0xe0, 0x80, 0x0b, 0x69, 0x7d, 0xc1, 0x90, 0x7c, 0x8b, 0xed, 0x37, 0xf3,
	0xb8, 0xd4, 0xa5, 0x2b, 0x73, 0xba, 0xf4, 0xce, 0x8c, 0xb9, 0xea, 0xa0, 0xa6, 0xf2, 0x28, 0xaf,
	0xfc, 0x3f, 0x3a, 0x94, 0x67, 0xb4, 0xdf, 0xe8, 0x3e, 0xac, 0xdf, 0x2b, 0xd0, 0x35, 0x5b, 0xec,
	0x80, 0x05, 0x63, 0x16, 0xeb, 0x3e, 0x93, 0xcb, 0x97, 0x1a, 0xce, 0x54, 0xb9, 0x89, 0xc3, 0x4c,
	0x55, 0xd3, 0x89, 0x63, 0xe8, 0xa9, 0x7e, 0x68, 0xb6, 0xfb, 0xec, 0x82, 0xf9, 0xd3, 0x99, 0xaa,
	0xa5, 0xe1, 0x03, 0x85, 0x0e, 0x3d, 0x75, 0x9c, 0xbc, 0x19, 0xbc, 0xda, 0xea, 0xa8, 0xa9, 0x31,
	0xdd, 0xcc, 0x9e, 0xc2, 0x7a, 0x41, 0x15, 0x56, 0x1a, 0x1d, 0x00, 0x6b, 0x39, 0x65, 0xaa, 0xca,
	0x58, 0x3f, 0x55, 0x60, 0x23, 0x75, 0xff, 0x24, 0xf1, 0x7d, 0x3b, 0x66, 0xea, 0x5b, 0xb5, 0xce,
	0x5b, 0x1e, 0xa0, 0x0f, 0x80, 0x0a, 0xb4, 0x5b, 0x35, 0x74, 0xab, 0xa1, 0x10, 0xed, 0xd4, 0x0e,
	0xac, 0xa2, 0x6a, 0x56, 0xf4, 0x5b, 0x63, 0x48, 0xb1, 0x7e, 0xac, 0x40, 0x3b, 0xf5, 0xc5, 0x77,
	0x3c, 0x8f, 0xc5, 0xb7, 0xf5, 0xa1, 0x0b, 0x75, 0x37, 0x4a, 0x42, 0x99, 0x86, 0x21, 0x2e, 0x54,
	0xd7, 0xf4, 0xb8, 0xd0, 0x02, 0x6d, 0x36, 0x5b, 0x4f, 0xa7, 0xa0, 0x7a, 0x6e, 0x0a, 0xb2, 0xfe,
	0xa8, 0xc2, 0x7a, 0xea, 0x89, 0x38, 0x4f, 0xf4, 0x04, 0x70, 0x5b, 0x67, 0xb6, 0x60, 0x45, 0xed,
	0xc5, 0xba, 0xab, 0x53, 0x77, 0x59, 0x9c, 0x27, 0x6f, 0x54, 0xe9, 0xcd, 0xac, 0x2e, 0xe6, 0x67,
	0xaf, 0x6c, 0x08, 0xa9, 0xe7, 0x87, 0x90, 0x0e, 0xd4, 0xc4, 0xe4, 0x85, 0x19, 0x67, 0xd5, 0xa7,
	0x46, 0xf6, 0xd3, 0x69, 0x56, 0x4c, 0xf6, 0x35, 0xf2, 0xd2, 0x8c, 0xb1, 0xea, 0x33, 0x9d, 0x78,
	0x1b, 0xd3, 0x89, 0x37, 0x9d, 0x01, 0x21, 0x37, 0x03, 0xce, 0x99, 0xf6, 0x9a, 0x73, 0xa7, 0xbd,
	0x3e, 0x80, 0x1f, 0xb9, 0xe7, 0x66, 0x14, 0xd2, 0xe3, 0x69, 0x43, 0x21, 0x47, 0xe5, 0x41, 0xa9,
	0x55, 0x1c, 0x94, 0xac, 0x5f, 0x2a, 0xb0, 0x79, 0x58, 0x1a, 0xea, 0x2f, 0x1c, 0x3f, 0xb9, 0x75,
	0x92, 0xe8, 0xe9, 0x60, 0x46, 0x53, 0x96, 0x29, 0x64, 0xf6, 0x57, 0x81, 0x8e, 0x08, 0xb4, 0x64,
	0xe2, 0x5f, 0x2f, 0xac, 0xbf, 0x6a, 0x59, 0xa4, 0x99, 0x92, 0x9d, 0x6f, 0x10, 0x95, 0xaf, 0x34,
	0x08, 0xf2, 0x19, 0x36, 0xcc, 0xe7, 0xa7, 0x69, 0xda, 0x1d, 0xa4, 0xc5, 0xa5, 0xb9, 0xdf, 0x9f,
	0xdd, 0x5a, 0xa8, 0x0c, 0xa3, 0x6b, 0x36, 0x93, 0x2f, 0x40, 0x8d, 0xe4, 0x7f, 0x89, 0xef, 0x8f,
	0xd2, 0x44, 0x44, 0xc5, 0x35, 0x54, 0xbc, 0x5d, 0x52, 0x5c, 0xcc, 0xd9, 0xd1, 0xb5, 0x0a, 0xc8,
	0x3b, 0x48, 0x7f, 0x9c, 0x1d, 0x60, 0x6a, 0xa1, 0xd6, 0x45, 0xd4, 0x5a, 0x6a, 0x63, 0x26, 0xfb,
	0x46, 0xe5, 0x1d, 0xe4, 0x20, 0xfb, 0xf9, 0x77, 0x74, 0x9e, 0xe0, 0xfb, 0x1e, 0x4c, 0x6b, 0x78,
	0xaf, 0xa4, 0x28, 0x4b, 0x9e, 0xd1, 0xbc, 0x6d, 0xe4, 0x7b, 0xd8, 0x9a, 0x7d, 0xb3, 0xef, 0xd4,
	0x03, 0xa1, 0xce, 0x25, 0xd4, 0x39, 0x28, 0xe9, 0x9c, 0x89, 0xa1, 0xd1, 0xf5, 0x2a, 0xac, 0x6f,
	0xa1, 0x33, 0x0c, 0xed, 0x37, 0x38, 0x32, 0xa5, 0xbf, 0x75, 0xff, 0x9b, 0xfd, 0x22, 0xd6, 0x4f,
	0xff, 0xb5, 0x5e, 0x5e, 0x64, 0x5b, 0x3f, 0xc0, 0xba, 0xea, 0x15, 0x45, 0x9d, 0x37, 0x6b, 0x9d,
	0x25, 0xcb, 0xd5, 0xdb, 0x58, 0xde, 0xff, 0x79, 0x1a, 0xb4, 0x1f, 0x9c, 0xd0, 0xf3, 0x59, 0x4c,
	0x3e, 0x42, 0x7b, 0x66, 0xfe, 0x9a, 0x3e, 0x41, 0x69, 0x82, 0xeb, 0xdd, 0xcb, 0x64, 0xe5, 0xc1,
	0xcd, 0x5a, 0x20, 0xc7, 0xb0, 0x5e, 0x9e, 0x79, 0xfa, 0x79, 0x7d, 0x25, 0x71, 0xef, 0x7e, 0x41,
	0x65, 0x49, 0x6e, 0x2d, 0x90, 0xd7, 0xd0, 0xcc, 0x0f, 0x19, 0x9b, 0xf3, 0xfd, 0x13, 0x3d, 0x7a,
	0x8d, 0x73, 0xc2, 0x5a, 0x50, 0xc7, 0x9c, 0xe9, 0xcd, 0x85, 0x63, 0x16, 0x65, 0x33, 0xc7, 0x2c,
	0x0a, 0xad, 0x05, 0xf2, 0x01, 0x5a, 0xc5, 0xc7, 0xdb, 0xca, 0xeb, 0x2a, 0x88, 0x7a, 0xbd, 0x82,
	0xaa, 0x82, 0xcc, 0x5a, 0x18, 0x2f, 0xe1, 0x3f, 0x2a, 0x2f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff,
	0x9c, 0xca, 0xa4, 0x8c, 0x62, 0x11, 0x00, 0x00,
}
