// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_addr.proto

package proto_user_addr

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserAddr struct {
	UserAddrId           int64    `protobuf:"varint,1,opt,name=user_addr_id,json=userAddrId,proto3" json:"user_addr_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Zip                  int64    `protobuf:"varint,3,opt,name=zip,proto3" json:"zip,omitempty"`
	Province             string   `protobuf:"bytes,4,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	District             string   `protobuf:"bytes,6,opt,name=district,proto3" json:"district,omitempty"`
	Address              string   `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	IsDefault            int64    `protobuf:"varint,8,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	ModifiedTime         string   `protobuf:"bytes,9,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAddr) Reset()         { *m = UserAddr{} }
func (m *UserAddr) String() string { return proto.CompactTextString(m) }
func (*UserAddr) ProtoMessage()    {}
func (*UserAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{1}
}

func (m *UserAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAddr.Unmarshal(m, b)
}
func (m *UserAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAddr.Marshal(b, m, deterministic)
}
func (m *UserAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAddr.Merge(m, src)
}
func (m *UserAddr) XXX_Size() int {
	return xxx_messageInfo_UserAddr.Size(m)
}
func (m *UserAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAddr.DiscardUnknown(m)
}

var xxx_messageInfo_UserAddr proto.InternalMessageInfo

func (m *UserAddr) GetUserAddrId() int64 {
	if m != nil {
		return m.UserAddrId
	}
	return 0
}

func (m *UserAddr) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserAddr) GetZip() int64 {
	if m != nil {
		return m.Zip
	}
	return 0
}

func (m *UserAddr) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *UserAddr) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UserAddr) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *UserAddr) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserAddr) GetIsDefault() int64 {
	if m != nil {
		return m.IsDefault
	}
	return 0
}

func (m *UserAddr) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

type In_GetUserAddrInfoById struct {
	UserAddrId           int64    `protobuf:"varint,1,opt,name=user_addr_id,json=userAddrId,proto3" json:"user_addr_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserAddrInfoById) Reset()         { *m = In_GetUserAddrInfoById{} }
func (m *In_GetUserAddrInfoById) String() string { return proto.CompactTextString(m) }
func (*In_GetUserAddrInfoById) ProtoMessage()    {}
func (*In_GetUserAddrInfoById) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{2}
}

func (m *In_GetUserAddrInfoById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserAddrInfoById.Unmarshal(m, b)
}
func (m *In_GetUserAddrInfoById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserAddrInfoById.Marshal(b, m, deterministic)
}
func (m *In_GetUserAddrInfoById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserAddrInfoById.Merge(m, src)
}
func (m *In_GetUserAddrInfoById) XXX_Size() int {
	return xxx_messageInfo_In_GetUserAddrInfoById.Size(m)
}
func (m *In_GetUserAddrInfoById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserAddrInfoById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserAddrInfoById proto.InternalMessageInfo

func (m *In_GetUserAddrInfoById) GetUserAddrId() int64 {
	if m != nil {
		return m.UserAddrId
	}
	return 0
}

type Out_GetUserAddrInfoById struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr             *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Out_GetUserAddrInfoById) Reset()         { *m = Out_GetUserAddrInfoById{} }
func (m *Out_GetUserAddrInfoById) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserAddrInfoById) ProtoMessage()    {}
func (*Out_GetUserAddrInfoById) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{3}
}

func (m *Out_GetUserAddrInfoById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserAddrInfoById.Unmarshal(m, b)
}
func (m *Out_GetUserAddrInfoById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserAddrInfoById.Marshal(b, m, deterministic)
}
func (m *Out_GetUserAddrInfoById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserAddrInfoById.Merge(m, src)
}
func (m *Out_GetUserAddrInfoById) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserAddrInfoById.Size(m)
}
func (m *Out_GetUserAddrInfoById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserAddrInfoById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserAddrInfoById proto.InternalMessageInfo

func (m *Out_GetUserAddrInfoById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserAddrInfoById) GetUserAddr() *UserAddr {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type Out_UpdateUserAddrInfo struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr             *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Out_UpdateUserAddrInfo) Reset()         { *m = Out_UpdateUserAddrInfo{} }
func (m *Out_UpdateUserAddrInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateUserAddrInfo) ProtoMessage()    {}
func (*Out_UpdateUserAddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{4}
}

func (m *Out_UpdateUserAddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateUserAddrInfo.Unmarshal(m, b)
}
func (m *Out_UpdateUserAddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateUserAddrInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateUserAddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateUserAddrInfo.Merge(m, src)
}
func (m *Out_UpdateUserAddrInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateUserAddrInfo.Size(m)
}
func (m *Out_UpdateUserAddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateUserAddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateUserAddrInfo proto.InternalMessageInfo

func (m *Out_UpdateUserAddrInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateUserAddrInfo) GetUserAddr() *UserAddr {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type In_UpdateUserAddrInfo struct {
	UserAddr             *UserAddr `protobuf:"bytes,1,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *In_UpdateUserAddrInfo) Reset()         { *m = In_UpdateUserAddrInfo{} }
func (m *In_UpdateUserAddrInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateUserAddrInfo) ProtoMessage()    {}
func (*In_UpdateUserAddrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{5}
}

func (m *In_UpdateUserAddrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateUserAddrInfo.Unmarshal(m, b)
}
func (m *In_UpdateUserAddrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateUserAddrInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateUserAddrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateUserAddrInfo.Merge(m, src)
}
func (m *In_UpdateUserAddrInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateUserAddrInfo.Size(m)
}
func (m *In_UpdateUserAddrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateUserAddrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateUserAddrInfo proto.InternalMessageInfo

func (m *In_UpdateUserAddrInfo) GetUserAddr() *UserAddr {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type In_GetUserAddrs struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserAddrs) Reset()         { *m = In_GetUserAddrs{} }
func (m *In_GetUserAddrs) String() string { return proto.CompactTextString(m) }
func (*In_GetUserAddrs) ProtoMessage()    {}
func (*In_GetUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{6}
}

func (m *In_GetUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserAddrs.Unmarshal(m, b)
}
func (m *In_GetUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserAddrs.Marshal(b, m, deterministic)
}
func (m *In_GetUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserAddrs.Merge(m, src)
}
func (m *In_GetUserAddrs) XXX_Size() int {
	return xxx_messageInfo_In_GetUserAddrs.Size(m)
}
func (m *In_GetUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserAddrs proto.InternalMessageInfo

func (m *In_GetUserAddrs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetUserAddrs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetUserAddrs) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetUserAddrs) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetUserAddrs) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetUserAddrs struct {
	Error                *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserAddrList         []*UserAddr `protobuf:"bytes,5,rep,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Out_GetUserAddrs) Reset()         { *m = Out_GetUserAddrs{} }
func (m *Out_GetUserAddrs) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserAddrs) ProtoMessage()    {}
func (*Out_GetUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{7}
}

func (m *Out_GetUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserAddrs.Unmarshal(m, b)
}
func (m *Out_GetUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserAddrs.Marshal(b, m, deterministic)
}
func (m *Out_GetUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserAddrs.Merge(m, src)
}
func (m *Out_GetUserAddrs) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserAddrs.Size(m)
}
func (m *Out_GetUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserAddrs proto.InternalMessageInfo

func (m *Out_GetUserAddrs) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserAddrs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetUserAddrs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetUserAddrs) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetUserAddrs) GetUserAddrList() []*UserAddr {
	if m != nil {
		return m.UserAddrList
	}
	return nil
}

type In_DeleteUserAddrs struct {
	UserAddrList         []int64  `protobuf:"varint,1,rep,packed,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_DeleteUserAddrs) Reset()         { *m = In_DeleteUserAddrs{} }
func (m *In_DeleteUserAddrs) String() string { return proto.CompactTextString(m) }
func (*In_DeleteUserAddrs) ProtoMessage()    {}
func (*In_DeleteUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{8}
}

func (m *In_DeleteUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteUserAddrs.Unmarshal(m, b)
}
func (m *In_DeleteUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteUserAddrs.Marshal(b, m, deterministic)
}
func (m *In_DeleteUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteUserAddrs.Merge(m, src)
}
func (m *In_DeleteUserAddrs) XXX_Size() int {
	return xxx_messageInfo_In_DeleteUserAddrs.Size(m)
}
func (m *In_DeleteUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteUserAddrs proto.InternalMessageInfo

func (m *In_DeleteUserAddrs) GetUserAddrList() []int64 {
	if m != nil {
		return m.UserAddrList
	}
	return nil
}

type Out_DeleteUserAddrs struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteUserAddrs) Reset()         { *m = Out_DeleteUserAddrs{} }
func (m *Out_DeleteUserAddrs) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteUserAddrs) ProtoMessage()    {}
func (*Out_DeleteUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{9}
}

func (m *Out_DeleteUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteUserAddrs.Unmarshal(m, b)
}
func (m *Out_DeleteUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteUserAddrs.Marshal(b, m, deterministic)
}
func (m *Out_DeleteUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteUserAddrs.Merge(m, src)
}
func (m *Out_DeleteUserAddrs) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteUserAddrs.Size(m)
}
func (m *Out_DeleteUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteUserAddrs proto.InternalMessageInfo

func (m *Out_DeleteUserAddrs) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateUserAddr struct {
	UserAddr             *UserAddr `protobuf:"bytes,1,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *In_CreateUserAddr) Reset()         { *m = In_CreateUserAddr{} }
func (m *In_CreateUserAddr) String() string { return proto.CompactTextString(m) }
func (*In_CreateUserAddr) ProtoMessage()    {}
func (*In_CreateUserAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{10}
}

func (m *In_CreateUserAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateUserAddr.Unmarshal(m, b)
}
func (m *In_CreateUserAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateUserAddr.Marshal(b, m, deterministic)
}
func (m *In_CreateUserAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateUserAddr.Merge(m, src)
}
func (m *In_CreateUserAddr) XXX_Size() int {
	return xxx_messageInfo_In_CreateUserAddr.Size(m)
}
func (m *In_CreateUserAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateUserAddr.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateUserAddr proto.InternalMessageInfo

func (m *In_CreateUserAddr) GetUserAddr() *UserAddr {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type Out_CreateUserAddr struct {
	Error                *Error    `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserAddr             *UserAddr `protobuf:"bytes,2,opt,name=user_addr,json=userAddr,proto3" json:"user_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Out_CreateUserAddr) Reset()         { *m = Out_CreateUserAddr{} }
func (m *Out_CreateUserAddr) String() string { return proto.CompactTextString(m) }
func (*Out_CreateUserAddr) ProtoMessage()    {}
func (*Out_CreateUserAddr) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{11}
}

func (m *Out_CreateUserAddr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateUserAddr.Unmarshal(m, b)
}
func (m *Out_CreateUserAddr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateUserAddr.Marshal(b, m, deterministic)
}
func (m *Out_CreateUserAddr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateUserAddr.Merge(m, src)
}
func (m *Out_CreateUserAddr) XXX_Size() int {
	return xxx_messageInfo_Out_CreateUserAddr.Size(m)
}
func (m *Out_CreateUserAddr) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateUserAddr.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateUserAddr proto.InternalMessageInfo

func (m *Out_CreateUserAddr) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateUserAddr) GetUserAddr() *UserAddr {
	if m != nil {
		return m.UserAddr
	}
	return nil
}

type In_GetOneUserAddrs struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetOneUserAddrs) Reset()         { *m = In_GetOneUserAddrs{} }
func (m *In_GetOneUserAddrs) String() string { return proto.CompactTextString(m) }
func (*In_GetOneUserAddrs) ProtoMessage()    {}
func (*In_GetOneUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{12}
}

func (m *In_GetOneUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetOneUserAddrs.Unmarshal(m, b)
}
func (m *In_GetOneUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetOneUserAddrs.Marshal(b, m, deterministic)
}
func (m *In_GetOneUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetOneUserAddrs.Merge(m, src)
}
func (m *In_GetOneUserAddrs) XXX_Size() int {
	return xxx_messageInfo_In_GetOneUserAddrs.Size(m)
}
func (m *In_GetOneUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetOneUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetOneUserAddrs proto.InternalMessageInfo

func (m *In_GetOneUserAddrs) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *In_GetOneUserAddrs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetOneUserAddrs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

type Out_GetOneUserAddrs struct {
	Error                *Error      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64       `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64       `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64       `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserAddrList         []*UserAddr `protobuf:"bytes,5,rep,name=user_addr_list,json=userAddrList,proto3" json:"user_addr_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Out_GetOneUserAddrs) Reset()         { *m = Out_GetOneUserAddrs{} }
func (m *Out_GetOneUserAddrs) String() string { return proto.CompactTextString(m) }
func (*Out_GetOneUserAddrs) ProtoMessage()    {}
func (*Out_GetOneUserAddrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_25acd5b3d3cf1498, []int{13}
}

func (m *Out_GetOneUserAddrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetOneUserAddrs.Unmarshal(m, b)
}
func (m *Out_GetOneUserAddrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetOneUserAddrs.Marshal(b, m, deterministic)
}
func (m *Out_GetOneUserAddrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetOneUserAddrs.Merge(m, src)
}
func (m *Out_GetOneUserAddrs) XXX_Size() int {
	return xxx_messageInfo_Out_GetOneUserAddrs.Size(m)
}
func (m *Out_GetOneUserAddrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetOneUserAddrs.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetOneUserAddrs proto.InternalMessageInfo

func (m *Out_GetOneUserAddrs) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetOneUserAddrs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetOneUserAddrs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetOneUserAddrs) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetOneUserAddrs) GetUserAddrList() []*UserAddr {
	if m != nil {
		return m.UserAddrList
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "proto_user_addr.Error")
	proto.RegisterType((*UserAddr)(nil), "proto_user_addr.User_addr")
	proto.RegisterType((*In_GetUserAddrInfoById)(nil), "proto_user_addr.In_GetUserAddrInfoById")
	proto.RegisterType((*Out_GetUserAddrInfoById)(nil), "proto_user_addr.Out_GetUserAddrInfoById")
	proto.RegisterType((*Out_UpdateUserAddrInfo)(nil), "proto_user_addr.Out_UpdateUserAddrInfo")
	proto.RegisterType((*In_UpdateUserAddrInfo)(nil), "proto_user_addr.In_UpdateUserAddrInfo")
	proto.RegisterType((*In_GetUserAddrs)(nil), "proto_user_addr.In_GetUserAddrs")
	proto.RegisterType((*Out_GetUserAddrs)(nil), "proto_user_addr.Out_GetUserAddrs")
	proto.RegisterType((*In_DeleteUserAddrs)(nil), "proto_user_addr.In_DeleteUserAddrs")
	proto.RegisterType((*Out_DeleteUserAddrs)(nil), "proto_user_addr.Out_DeleteUserAddrs")
	proto.RegisterType((*In_CreateUserAddr)(nil), "proto_user_addr.In_CreateUserAddr")
	proto.RegisterType((*Out_CreateUserAddr)(nil), "proto_user_addr.Out_CreateUserAddr")
	proto.RegisterType((*In_GetOneUserAddrs)(nil), "proto_user_addr.In_GetOneUserAddrs")
	proto.RegisterType((*Out_GetOneUserAddrs)(nil), "proto_user_addr.Out_GetOneUserAddrs")
}

func init() { proto.RegisterFile("user_addr.proto", fileDescriptor_25acd5b3d3cf1498) }

var fileDescriptor_25acd5b3d3cf1498 = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x54, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0x6e, 0x96, 0x66, 0x6d, 0xce, 0xca, 0x3a, 0xbc, 0xb1, 0x85, 0x48, 0x48, 0xc5, 0x9d, 0x58,
	0x2f, 0xd0, 0x2e, 0x86, 0x10, 0xd2, 0xae, 0x80, 0x0d, 0x4d, 0x11, 0x93, 0x86, 0x02, 0xbd, 0x40,
	0x48, 0x44, 0xa1, 0xf6, 0x86, 0xa1, 0x4d, 0x2a, 0xdb, 0x9b, 0x54, 0xb8, 0x00, 0xf1, 0x10, 0x3c,
	0x11, 0x12, 0xef, 0xc0, 0xd3, 0x20, 0xdb, 0x4d, 0xd7, 0x26, 0xa9, 0xaa, 0x72, 0x31, 0x89, 0xab,
	0xf8, 0x1c, 0x7f, 0xe7, 0xf3, 0xf9, 0xf9, 0x72, 0xa0, 0x79, 0x29, 0x28, 0x8f, 0x62, 0x42, 0xf8,
	0xfe, 0x90, 0xa7, 0x32, 0x45, 0x4d, 0xfd, 0x89, 0x26, 0x6e, 0xfc, 0x18, 0x9c, 0x17, 0x9c, 0xa7,
	0x1c, 0x21, 0xa8, 0xf6, 0x52, 0x42, 0x3d, 0xab, 0x65, 0x75, 0x9c, 0x50, 0x9f, 0x91, 0x07, 0xb5,
	0x01, 0x15, 0x22, 0xbe, 0xa0, 0xde, 0x4a, 0xcb, 0xea, 0xb8, 0x61, 0x66, 0xe2, 0x1f, 0x2b, 0xe0,
	0x76, 0x33, 0x12, 0xd4, 0x82, 0xc6, 0x84, 0x31, 0x62, 0x44, 0x73, 0xd8, 0x21, 0x28, 0xdf, 0x33,
	0x42, 0x78, 0x40, 0xd0, 0x0e, 0xd4, 0x34, 0x82, 0x11, 0xcd, 0x64, 0x87, 0xab, 0xca, 0x0c, 0x08,
	0xda, 0x00, 0xfb, 0x0b, 0x1b, 0x7a, 0xb6, 0x76, 0xaa, 0x23, 0xf2, 0xa1, 0x3e, 0xe4, 0xe9, 0x15,
	0x4b, 0x7a, 0xd4, 0xab, 0xea, 0x57, 0x27, 0xb6, 0x4e, 0x92, 0xc9, 0x91, 0xe7, 0x68, 0xbf, 0x3e,
	0x2b, 0x3c, 0x61, 0x42, 0x72, 0xd6, 0x93, 0xde, 0xaa, 0xc1, 0x67, 0xb6, 0x2a, 0x40, 0xe5, 0x44,
	0x85, 0xf0, 0x6a, 0xa6, 0x80, 0xb1, 0x89, 0xee, 0x01, 0x30, 0x11, 0x11, 0x7a, 0x1e, 0x5f, 0xf6,
	0xa5, 0x57, 0xd7, 0xcf, 0xbb, 0x4c, 0x1c, 0x1b, 0x07, 0x6a, 0xc3, 0xad, 0x41, 0x4a, 0xd8, 0x39,
	0xa3, 0x24, 0x92, 0x6c, 0x40, 0x3d, 0x57, 0x87, 0x37, 0x32, 0xe7, 0x1b, 0x36, 0xa0, 0xf8, 0x10,
	0xb6, 0x83, 0x24, 0x3a, 0xa1, 0xb2, 0x9b, 0x15, 0x9a, 0x9c, 0xa7, 0xcf, 0x47, 0x01, 0x59, 0xdc,
	0x10, 0xfc, 0xdd, 0x82, 0x9d, 0xb3, 0x4b, 0x59, 0x1a, 0xfd, 0x10, 0x1c, 0xaa, 0x66, 0xa2, 0xc3,
	0xd6, 0x0e, 0xb6, 0xf7, 0x73, 0x43, 0xdb, 0xd7, 0x13, 0x0b, 0x0d, 0x08, 0x3d, 0x01, 0x77, 0x72,
	0xa3, 0x9b, 0xbb, 0x76, 0xe0, 0x17, 0x22, 0x26, 0xb3, 0x0a, 0xeb, 0x59, 0x12, 0xf8, 0x1b, 0x6c,
	0xab, 0x0c, 0xba, 0x43, 0x12, 0x4b, 0x3a, 0x9d, 0xc4, 0x4d, 0x25, 0xf0, 0x0a, 0xee, 0x04, 0x49,
	0xd9, 0xfb, 0x33, 0x8c, 0xd6, 0x12, 0x8c, 0x3f, 0x2d, 0x68, 0xce, 0x8e, 0x44, 0xa0, 0x2d, 0x70,
	0xfa, 0x6c, 0xc0, 0xe4, 0x78, 0x08, 0xc6, 0x50, 0xde, 0x61, 0x7c, 0x41, 0xc5, 0x58, 0x8e, 0xc6,
	0x50, 0xaa, 0x10, 0x34, 0xe6, 0xbd, 0x8f, 0xd1, 0x67, 0x3a, 0xd2, 0xa2, 0x74, 0x43, 0xd7, 0x78,
	0x5e, 0xd2, 0x91, 0xbe, 0x96, 0x31, 0x97, 0x46, 0x12, 0xd5, 0xf1, 0xb5, 0xf2, 0x28, 0x3d, 0xa0,
	0xbb, 0x50, 0xa7, 0xc9, 0x58, 0x2f, 0x46, 0xa1, 0x35, 0x9a, 0x18, 0xa9, 0xfc, 0xb2, 0x60, 0x23,
	0x37, 0x6e, 0xb1, 0x64, 0x9b, 0x27, 0x75, 0xac, 0x94, 0xd6, 0x61, 0x4f, 0xd7, 0xb1, 0x05, 0x8e,
	0x4c, 0x65, 0xdc, 0xd7, 0x39, 0xda, 0xa1, 0x31, 0xd0, 0x53, 0x58, 0xbf, 0x56, 0x65, 0x9f, 0x09,
	0xe9, 0x39, 0x2d, 0x7b, 0x41, 0x6f, 0x1b, 0x59, 0x6f, 0x4f, 0x99, 0x90, 0xf8, 0x10, 0x50, 0x90,
	0x44, 0xc7, 0xb4, 0x4f, 0xaf, 0x27, 0x26, 0xd0, 0x6e, 0x81, 0xd7, 0x6a, 0xd9, 0x1d, 0x3b, 0x17,
	0x7b, 0x04, 0x9b, 0xaa, 0x03, 0xf9, 0xe0, 0xa5, 0x9a, 0x80, 0x4f, 0xe1, 0x76, 0x90, 0x44, 0x47,
	0x9c, 0x4e, 0x49, 0xe6, 0xdf, 0xe5, 0xf2, 0x15, 0x90, 0x4a, 0x29, 0x47, 0x77, 0x43, 0xea, 0x7f,
	0xab, 0x7b, 0x79, 0x42, 0xe5, 0x59, 0x32, 0xd5, 0x8e, 0xa9, 0x45, 0x69, 0xcd, 0x2c, 0xca, 0x25,
	0xc6, 0x8f, 0x7f, 0x5b, 0xa6, 0xd7, 0x79, 0xf2, 0xff, 0x4e, 0x70, 0x07, 0x7f, 0xaa, 0xd0, 0xcc,
	0xf2, 0x7f, 0x4d, 0xf9, 0x15, 0xeb, 0x51, 0xf4, 0x09, 0x36, 0xcb, 0xb6, 0xe6, 0x5e, 0x81, 0xb4,
	0x7c, 0x39, 0xfb, 0x9d, 0x02, 0x70, 0xce, 0x22, 0xc6, 0x15, 0x74, 0x01, 0xa8, 0x64, 0x3f, 0x3d,
	0x28, 0x7b, 0xaa, 0x88, 0xf3, 0xf7, 0x4a, 0x5f, 0x2a, 0x02, 0x71, 0x05, 0x75, 0xa1, 0x31, 0xb3,
	0x1b, 0x5a, 0x0b, 0xaa, 0x11, 0xfe, 0xfd, 0x45, 0x65, 0x08, 0x5c, 0x41, 0xef, 0xa1, 0x99, 0xff,
	0xe1, 0xda, 0x65, 0xcc, 0x39, 0x90, 0xbf, 0x5b, 0x4a, 0x9e, 0x43, 0xe1, 0x0a, 0x7a, 0x07, 0xeb,
	0xb9, 0xbf, 0x07, 0x97, 0xd1, 0xcf, 0x62, 0xfc, 0x76, 0x29, 0xfb, 0x2c, 0xc8, 0x24, 0x9f, 0x57,
	0x70, 0x7b, 0x4e, 0x5b, 0xa6, 0x41, 0x73, 0x92, 0xcf, 0xa1, 0x70, 0xe5, 0xc3, 0xaa, 0x86, 0x3d,
	0xfa, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x86, 0xaf, 0x1e, 0xa6, 0x26, 0x09, 0x00, 0x00,
}
