// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_login_log.proto

package user_login_log

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserLoginLog struct {
	LoginId              int64    `protobuf:"varint,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LoginTime            string   `protobuf:"bytes,3,opt,name=login_time,json=loginTime,proto3" json:"login_time,omitempty"`
	LoginIp              string   `protobuf:"bytes,4,opt,name=login_ip,json=loginIp,proto3" json:"login_ip,omitempty"`
	LoginType            int64    `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserLoginLog) Reset()         { *m = UserLoginLog{} }
func (m *UserLoginLog) String() string { return proto.CompactTextString(m) }
func (*UserLoginLog) ProtoMessage()    {}
func (*UserLoginLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{0}
}

func (m *UserLoginLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLoginLog.Unmarshal(m, b)
}
func (m *UserLoginLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLoginLog.Marshal(b, m, deterministic)
}
func (m *UserLoginLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLoginLog.Merge(m, src)
}
func (m *UserLoginLog) XXX_Size() int {
	return xxx_messageInfo_UserLoginLog.Size(m)
}
func (m *UserLoginLog) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLoginLog.DiscardUnknown(m)
}

var xxx_messageInfo_UserLoginLog proto.InternalMessageInfo

func (m *UserLoginLog) GetLoginId() int64 {
	if m != nil {
		return m.LoginId
	}
	return 0
}

func (m *UserLoginLog) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserLoginLog) GetLoginTime() string {
	if m != nil {
		return m.LoginTime
	}
	return ""
}

func (m *UserLoginLog) GetLoginIp() string {
	if m != nil {
		return m.LoginIp
	}
	return ""
}

func (m *UserLoginLog) GetLoginType() int64 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetUserLoginLogInfoById struct {
	LoginId              int64    `protobuf:"varint,1,opt,name=login_id,json=loginId,proto3" json:"login_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserLoginLogInfoById) Reset()         { *m = In_GetUserLoginLogInfoById{} }
func (m *In_GetUserLoginLogInfoById) String() string { return proto.CompactTextString(m) }
func (*In_GetUserLoginLogInfoById) ProtoMessage()    {}
func (*In_GetUserLoginLogInfoById) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{2}
}

func (m *In_GetUserLoginLogInfoById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserLoginLogInfoById.Unmarshal(m, b)
}
func (m *In_GetUserLoginLogInfoById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserLoginLogInfoById.Marshal(b, m, deterministic)
}
func (m *In_GetUserLoginLogInfoById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserLoginLogInfoById.Merge(m, src)
}
func (m *In_GetUserLoginLogInfoById) XXX_Size() int {
	return xxx_messageInfo_In_GetUserLoginLogInfoById.Size(m)
}
func (m *In_GetUserLoginLogInfoById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserLoginLogInfoById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserLoginLogInfoById proto.InternalMessageInfo

func (m *In_GetUserLoginLogInfoById) GetLoginId() int64 {
	if m != nil {
		return m.LoginId
	}
	return 0
}

type Out_GetUserLoginLogInfoById struct {
	Error                *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog         *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_GetUserLoginLogInfoById) Reset()         { *m = Out_GetUserLoginLogInfoById{} }
func (m *Out_GetUserLoginLogInfoById) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserLoginLogInfoById) ProtoMessage()    {}
func (*Out_GetUserLoginLogInfoById) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{3}
}

func (m *Out_GetUserLoginLogInfoById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserLoginLogInfoById.Unmarshal(m, b)
}
func (m *Out_GetUserLoginLogInfoById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserLoginLogInfoById.Marshal(b, m, deterministic)
}
func (m *Out_GetUserLoginLogInfoById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserLoginLogInfoById.Merge(m, src)
}
func (m *Out_GetUserLoginLogInfoById) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserLoginLogInfoById.Size(m)
}
func (m *Out_GetUserLoginLogInfoById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserLoginLogInfoById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserLoginLogInfoById proto.InternalMessageInfo

func (m *Out_GetUserLoginLogInfoById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserLoginLogInfoById) GetUserLoginLog() *UserLoginLog {
	if m != nil {
		return m.UserLoginLog
	}
	return nil
}

type Out_UpdateUserLoginLogInfo struct {
	Error                *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog         *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_UpdateUserLoginLogInfo) Reset()         { *m = Out_UpdateUserLoginLogInfo{} }
func (m *Out_UpdateUserLoginLogInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateUserLoginLogInfo) ProtoMessage()    {}
func (*Out_UpdateUserLoginLogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{4}
}

func (m *Out_UpdateUserLoginLogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateUserLoginLogInfo.Unmarshal(m, b)
}
func (m *Out_UpdateUserLoginLogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateUserLoginLogInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateUserLoginLogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateUserLoginLogInfo.Merge(m, src)
}
func (m *Out_UpdateUserLoginLogInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateUserLoginLogInfo.Size(m)
}
func (m *Out_UpdateUserLoginLogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateUserLoginLogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateUserLoginLogInfo proto.InternalMessageInfo

func (m *Out_UpdateUserLoginLogInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateUserLoginLogInfo) GetUserLoginLog() *UserLoginLog {
	if m != nil {
		return m.UserLoginLog
	}
	return nil
}

type In_UpdateUserLoginLogInfo struct {
	UserLoginLog         *UserLoginLog `protobuf:"bytes,1,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *In_UpdateUserLoginLogInfo) Reset()         { *m = In_UpdateUserLoginLogInfo{} }
func (m *In_UpdateUserLoginLogInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateUserLoginLogInfo) ProtoMessage()    {}
func (*In_UpdateUserLoginLogInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{5}
}

func (m *In_UpdateUserLoginLogInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateUserLoginLogInfo.Unmarshal(m, b)
}
func (m *In_UpdateUserLoginLogInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateUserLoginLogInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateUserLoginLogInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateUserLoginLogInfo.Merge(m, src)
}
func (m *In_UpdateUserLoginLogInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateUserLoginLogInfo.Size(m)
}
func (m *In_UpdateUserLoginLogInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateUserLoginLogInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateUserLoginLogInfo proto.InternalMessageInfo

func (m *In_UpdateUserLoginLogInfo) GetUserLoginLog() *UserLoginLog {
	if m != nil {
		return m.UserLoginLog
	}
	return nil
}

type In_GetUserLoginLogs struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserLoginLogs) Reset()         { *m = In_GetUserLoginLogs{} }
func (m *In_GetUserLoginLogs) String() string { return proto.CompactTextString(m) }
func (*In_GetUserLoginLogs) ProtoMessage()    {}
func (*In_GetUserLoginLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{6}
}

func (m *In_GetUserLoginLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserLoginLogs.Unmarshal(m, b)
}
func (m *In_GetUserLoginLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserLoginLogs.Marshal(b, m, deterministic)
}
func (m *In_GetUserLoginLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserLoginLogs.Merge(m, src)
}
func (m *In_GetUserLoginLogs) XXX_Size() int {
	return xxx_messageInfo_In_GetUserLoginLogs.Size(m)
}
func (m *In_GetUserLoginLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserLoginLogs.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserLoginLogs proto.InternalMessageInfo

func (m *In_GetUserLoginLogs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetUserLoginLogs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetUserLoginLogs) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetUserLoginLogs) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetUserLoginLogs) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetUserLoginLogs struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64           `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserLoginLogList     []*UserLoginLog `protobuf:"bytes,5,rep,name=user_login_log_list,json=userLoginLogList,proto3" json:"user_login_log_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Out_GetUserLoginLogs) Reset()         { *m = Out_GetUserLoginLogs{} }
func (m *Out_GetUserLoginLogs) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserLoginLogs) ProtoMessage()    {}
func (*Out_GetUserLoginLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{7}
}

func (m *Out_GetUserLoginLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserLoginLogs.Unmarshal(m, b)
}
func (m *Out_GetUserLoginLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserLoginLogs.Marshal(b, m, deterministic)
}
func (m *Out_GetUserLoginLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserLoginLogs.Merge(m, src)
}
func (m *Out_GetUserLoginLogs) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserLoginLogs.Size(m)
}
func (m *Out_GetUserLoginLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserLoginLogs.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserLoginLogs proto.InternalMessageInfo

func (m *Out_GetUserLoginLogs) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserLoginLogs) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetUserLoginLogs) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetUserLoginLogs) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetUserLoginLogs) GetUserLoginLogList() []*UserLoginLog {
	if m != nil {
		return m.UserLoginLogList
	}
	return nil
}

type In_DeleteUserLoginLogs struct {
	UserLoginLogList     []int64  `protobuf:"varint,1,rep,packed,name=user_login_log_list,json=userLoginLogList,proto3" json:"user_login_log_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_DeleteUserLoginLogs) Reset()         { *m = In_DeleteUserLoginLogs{} }
func (m *In_DeleteUserLoginLogs) String() string { return proto.CompactTextString(m) }
func (*In_DeleteUserLoginLogs) ProtoMessage()    {}
func (*In_DeleteUserLoginLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{8}
}

func (m *In_DeleteUserLoginLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteUserLoginLogs.Unmarshal(m, b)
}
func (m *In_DeleteUserLoginLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteUserLoginLogs.Marshal(b, m, deterministic)
}
func (m *In_DeleteUserLoginLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteUserLoginLogs.Merge(m, src)
}
func (m *In_DeleteUserLoginLogs) XXX_Size() int {
	return xxx_messageInfo_In_DeleteUserLoginLogs.Size(m)
}
func (m *In_DeleteUserLoginLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteUserLoginLogs.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteUserLoginLogs proto.InternalMessageInfo

func (m *In_DeleteUserLoginLogs) GetUserLoginLogList() []int64 {
	if m != nil {
		return m.UserLoginLogList
	}
	return nil
}

type Out_DeleteUserLoginLogs struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteUserLoginLogs) Reset()         { *m = Out_DeleteUserLoginLogs{} }
func (m *Out_DeleteUserLoginLogs) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteUserLoginLogs) ProtoMessage()    {}
func (*Out_DeleteUserLoginLogs) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{9}
}

func (m *Out_DeleteUserLoginLogs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteUserLoginLogs.Unmarshal(m, b)
}
func (m *Out_DeleteUserLoginLogs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteUserLoginLogs.Marshal(b, m, deterministic)
}
func (m *Out_DeleteUserLoginLogs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteUserLoginLogs.Merge(m, src)
}
func (m *Out_DeleteUserLoginLogs) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteUserLoginLogs.Size(m)
}
func (m *Out_DeleteUserLoginLogs) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteUserLoginLogs.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteUserLoginLogs proto.InternalMessageInfo

func (m *Out_DeleteUserLoginLogs) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateUserLoginLog struct {
	UserLoginLog         *UserLoginLog `protobuf:"bytes,1,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *In_CreateUserLoginLog) Reset()         { *m = In_CreateUserLoginLog{} }
func (m *In_CreateUserLoginLog) String() string { return proto.CompactTextString(m) }
func (*In_CreateUserLoginLog) ProtoMessage()    {}
func (*In_CreateUserLoginLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{10}
}

func (m *In_CreateUserLoginLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateUserLoginLog.Unmarshal(m, b)
}
func (m *In_CreateUserLoginLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateUserLoginLog.Marshal(b, m, deterministic)
}
func (m *In_CreateUserLoginLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateUserLoginLog.Merge(m, src)
}
func (m *In_CreateUserLoginLog) XXX_Size() int {
	return xxx_messageInfo_In_CreateUserLoginLog.Size(m)
}
func (m *In_CreateUserLoginLog) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateUserLoginLog.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateUserLoginLog proto.InternalMessageInfo

func (m *In_CreateUserLoginLog) GetUserLoginLog() *UserLoginLog {
	if m != nil {
		return m.UserLoginLog
	}
	return nil
}

type Out_CreateUserLoginLog struct {
	Error                *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLoginLog         *UserLoginLog `protobuf:"bytes,2,opt,name=user_login_log,json=userLoginLog,proto3" json:"user_login_log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_CreateUserLoginLog) Reset()         { *m = Out_CreateUserLoginLog{} }
func (m *Out_CreateUserLoginLog) String() string { return proto.CompactTextString(m) }
func (*Out_CreateUserLoginLog) ProtoMessage()    {}
func (*Out_CreateUserLoginLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e2963931bd6106c, []int{11}
}

func (m *Out_CreateUserLoginLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateUserLoginLog.Unmarshal(m, b)
}
func (m *Out_CreateUserLoginLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateUserLoginLog.Marshal(b, m, deterministic)
}
func (m *Out_CreateUserLoginLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateUserLoginLog.Merge(m, src)
}
func (m *Out_CreateUserLoginLog) XXX_Size() int {
	return xxx_messageInfo_Out_CreateUserLoginLog.Size(m)
}
func (m *Out_CreateUserLoginLog) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateUserLoginLog.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateUserLoginLog proto.InternalMessageInfo

func (m *Out_CreateUserLoginLog) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateUserLoginLog) GetUserLoginLog() *UserLoginLog {
	if m != nil {
		return m.UserLoginLog
	}
	return nil
}

func init() {
	proto.RegisterType((*UserLoginLog)(nil), "user_login_log.User_login_log")
	proto.RegisterType((*Error)(nil), "user_login_log.Error")
	proto.RegisterType((*In_GetUserLoginLogInfoById)(nil), "user_login_log.In_GetUserLoginLogInfoById")
	proto.RegisterType((*Out_GetUserLoginLogInfoById)(nil), "user_login_log.Out_GetUserLoginLogInfoById")
	proto.RegisterType((*Out_UpdateUserLoginLogInfo)(nil), "user_login_log.Out_UpdateUserLoginLogInfo")
	proto.RegisterType((*In_UpdateUserLoginLogInfo)(nil), "user_login_log.In_UpdateUserLoginLogInfo")
	proto.RegisterType((*In_GetUserLoginLogs)(nil), "user_login_log.In_GetUserLoginLogs")
	proto.RegisterType((*Out_GetUserLoginLogs)(nil), "user_login_log.Out_GetUserLoginLogs")
	proto.RegisterType((*In_DeleteUserLoginLogs)(nil), "user_login_log.In_DeleteUserLoginLogs")
	proto.RegisterType((*Out_DeleteUserLoginLogs)(nil), "user_login_log.Out_DeleteUserLoginLogs")
	proto.RegisterType((*In_CreateUserLoginLog)(nil), "user_login_log.In_CreateUserLoginLog")
	proto.RegisterType((*Out_CreateUserLoginLog)(nil), "user_login_log.Out_CreateUserLoginLog")
}

func init() { proto.RegisterFile("user_login_log.proto", fileDescriptor_1e2963931bd6106c) }

var fileDescriptor_1e2963931bd6106c = []byte{
	// 582 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xae, 0x97, 0x66, 0xa5, 0x67, 0x68, 0x9a, 0xdc, 0xae, 0xcd, 0x82, 0x40, 0x95, 0x81, 0x51,
	0x36, 0xb1, 0x8b, 0x22, 0xc4, 0x3d, 0x0c, 0xa6, 0x88, 0x22, 0xa4, 0xc0, 0x2e, 0x51, 0x14, 0x9a,
	0x43, 0x17, 0xd1, 0x26, 0x21, 0x76, 0x91, 0xfa, 0x0c, 0x5c, 0xc0, 0x35, 0x12, 0xef, 0xc0, 0xc3,
	0xf0, 0x40, 0xc8, 0x76, 0x8b, 0xd2, 0xd4, 0x19, 0x1b, 0x42, 0xec, 0xa6, 0xea, 0xf9, 0xfd, 0xbe,
	0x73, 0xfc, 0xd9, 0x81, 0xf6, 0x8c, 0x63, 0x1e, 0x4c, 0xd2, 0x71, 0x9c, 0xc8, 0xdf, 0xa3, 0x2c,
	0x4f, 0x45, 0x4a, 0xb7, 0x57, 0xbd, 0xec, 0x3b, 0x81, 0xed, 0xd3, 0x15, 0x17, 0xdd, 0x83, 0x6b,
	0xda, 0x88, 0x23, 0x87, 0xf4, 0x48, 0xdf, 0xf2, 0x1b, 0xca, 0xf6, 0x22, 0xda, 0x85, 0x86, 0xaa,
	0x8f, 0x23, 0x67, 0x43, 0x45, 0x36, 0xa5, 0xe9, 0x45, 0xf4, 0x26, 0x80, 0xae, 0x11, 0xf1, 0x14,
	0x1d, 0xab, 0x47, 0xfa, 0x4d, 0xbf, 0xa9, 0x3c, 0x6f, 0xe2, 0x29, 0x16, 0x5a, 0x66, 0x4e, 0x5d,
	0x05, 0x17, 0x2d, 0xb3, 0x42, 0xe5, 0x3c, 0x43, 0xc7, 0x56, 0x5d, 0x17, 0x95, 0xf3, 0x0c, 0xd9,
	0x23, 0xb0, 0x9f, 0xe5, 0x79, 0x9a, 0x53, 0x0a, 0xf5, 0x51, 0x1a, 0xa1, 0x62, 0x64, 0xfb, 0xea,
	0x3f, 0x75, 0xa0, 0x31, 0x45, 0xce, 0xc3, 0x31, 0x2a, 0x3a, 0x4d, 0x7f, 0x69, 0xb2, 0xc7, 0xe0,
	0x7a, 0x49, 0x70, 0x82, 0x42, 0xce, 0x36, 0x94, 0xdd, 0x86, 0xe9, 0xd8, 0x4b, 0xde, 0xa7, 0x4f,
	0xe6, 0x5e, 0x74, 0xce, 0x84, 0xec, 0x2b, 0x81, 0x1b, 0xaf, 0x66, 0xa2, 0xb2, 0xf4, 0x10, 0x6c,
	0x94, 0x7c, 0x54, 0xdd, 0xd6, 0x60, 0xf7, 0xa8, 0xb4, 0x65, 0x45, 0xd6, 0xd7, 0x39, 0xf4, 0x18,
	0x4a, 0xeb, 0x56, 0x34, 0xb7, 0x06, 0xb7, 0xca, 0x55, 0xab, 0x27, 0xe0, 0x5f, 0x9f, 0x15, 0xa0,
	0xd9, 0x17, 0x02, 0xae, 0xa4, 0x74, 0x9a, 0x45, 0xa1, 0xc0, 0x32, 0xab, 0xab, 0x60, 0x14, 0xc2,
	0x9e, 0x97, 0x54, 0xf1, 0x59, 0x87, 0x20, 0x7f, 0x01, 0xf1, 0x8d, 0x40, 0x6b, 0xfd, 0x04, 0x39,
	0x6d, 0x83, 0x3d, 0x89, 0xa7, 0xb1, 0x58, 0x9c, 0x9b, 0x36, 0xa4, 0x37, 0x0b, 0xc7, 0xc8, 0x17,
	0xaa, 0xd4, 0x86, 0x94, 0x16, 0xc7, 0x30, 0x1f, 0x9d, 0x05, 0x1f, 0x70, 0xbe, 0x14, 0xa5, 0xf6,
	0xbc, 0xc0, 0xb9, 0x0a, 0x8b, 0x30, 0x17, 0x5a, 0xb3, 0xf5, 0x45, 0x58, 0x7a, 0x96, 0x9a, 0xc5,
	0x24, 0xd2, 0x41, 0x5b, 0xab, 0x0b, 0x93, 0x48, 0x86, 0xd8, 0x4f, 0x02, 0x6d, 0x83, 0x48, 0xf8,
	0xe5, 0xce, 0xe2, 0xf7, 0x28, 0x1b, 0xc6, 0x51, 0xac, 0xe2, 0x28, 0x6d, 0xb0, 0x45, 0x2a, 0xc2,
	0x89, 0xa2, 0x69, 0xf9, 0xda, 0xa0, 0x2f, 0xa1, 0xb5, 0x0a, 0x10, 0x4c, 0x62, 0x2e, 0x1c, 0xbb,
	0x67, 0x5d, 0x60, 0xdf, 0x3b, 0xc5, 0x7d, 0x0f, 0x63, 0x2e, 0xd8, 0x09, 0x74, 0xbc, 0x24, 0x38,
	0xc6, 0x09, 0xae, 0x1e, 0x2b, 0xa7, 0x0f, 0xcc, 0x40, 0xa4, 0x67, 0xf5, 0x2d, 0x43, 0xa3, 0xe7,
	0xd0, 0x95, 0xeb, 0x31, 0x75, 0xba, 0xcc, 0x86, 0xd8, 0x5b, 0xd8, 0xf5, 0x92, 0xe0, 0x69, 0x8e,
	0x25, 0x9d, 0xfd, 0x23, 0x8d, 0x7d, 0x26, 0xd0, 0x91, 0x3c, 0x0d, 0x00, 0xff, 0xff, 0x52, 0x0d,
	0x7e, 0xd4, 0xa1, 0x55, 0xe4, 0xf0, 0x1a, 0xf3, 0x4f, 0xf1, 0x08, 0xa9, 0x80, 0x6e, 0xd5, 0x63,
	0x74, 0x50, 0x06, 0xa8, 0x7e, 0xf3, 0xdc, 0xc3, 0x72, 0xee, 0x39, 0xaf, 0x1c, 0xab, 0xd1, 0x8f,
	0xd0, 0xa9, 0xb8, 0xdf, 0xf7, 0x0d, 0xa0, 0xe6, 0x54, 0xf7, 0xc0, 0x84, 0x69, 0xce, 0x65, 0x35,
	0x1a, 0xc0, 0xce, 0xda, 0x85, 0xba, 0xfd, 0xe7, 0x09, 0xb9, 0x7b, 0xe7, 0x02, 0xa3, 0x71, 0x56,
	0xa3, 0x67, 0xd0, 0x32, 0x49, 0x72, 0xdf, 0x80, 0x61, 0xc8, 0x73, 0xef, 0x99, 0x60, 0x0c, 0x89,
	0xac, 0x46, 0x11, 0xa8, 0x41, 0x54, 0x77, 0x0d, 0x40, 0xeb, 0x69, 0xee, 0xbe, 0x09, 0x67, 0x3d,
	0x8f, 0xd5, 0xde, 0x6d, 0xaa, 0x6f, 0xfa, 0xc3, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4c, 0x53,
	0x9c, 0x62, 0xeb, 0x07, 0x00, 0x00,
}
