// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_level.proto

package user_level

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//用户等级
type UserLevelInf struct {
	Id                    int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                  string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GrowthPoint           int64    `protobuf:"varint,3,opt,name=growth_point,json=growthPoint,proto3" json:"growth_point,omitempty"`
	DefaultStatus         int64    `protobuf:"varint,4,opt,name=default_status,json=defaultStatus,proto3" json:"default_status,omitempty"`
	FreeFreightPoint      float32  `protobuf:"fixed32,5,opt,name=free_freight_point,json=freeFreightPoint,proto3" json:"free_freight_point,omitempty"`
	CommentGrowthPoint    int64    `protobuf:"varint,6,opt,name=comment_growth_point,json=commentGrowthPoint,proto3" json:"comment_growth_point,omitempty"`
	PriviledgeFreeFreight int64    `protobuf:"varint,7,opt,name=priviledge_free_freight,json=priviledgeFreeFreight,proto3" json:"priviledge_free_freight,omitempty"`
	PriviledgeSignIn      int64    `protobuf:"varint,8,opt,name=priviledge_sign_in,json=priviledgeSignIn,proto3" json:"priviledge_sign_in,omitempty"`
	PriviledgeComment     int64    `protobuf:"varint,9,opt,name=priviledge_comment,json=priviledgeComment,proto3" json:"priviledge_comment,omitempty"`
	PriviledgePromotion   int64    `protobuf:"varint,10,opt,name=priviledge_promotion,json=priviledgePromotion,proto3" json:"priviledge_promotion,omitempty"`
	PriviledgeMemberPrice int64    `protobuf:"varint,11,opt,name=priviledge_member_price,json=priviledgeMemberPrice,proto3" json:"priviledge_member_price,omitempty"`
	PriviledgeBirthday    int64    `protobuf:"varint,12,opt,name=priviledge_birthday,json=priviledgeBirthday,proto3" json:"priviledge_birthday,omitempty"`
	Note                  string   `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *UserLevelInf) Reset()         { *m = UserLevelInf{} }
func (m *UserLevelInf) String() string { return proto.CompactTextString(m) }
func (*UserLevelInf) ProtoMessage()    {}
func (*UserLevelInf) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{1}
}

func (m *UserLevelInf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserLevelInf.Unmarshal(m, b)
}
func (m *UserLevelInf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserLevelInf.Marshal(b, m, deterministic)
}
func (m *UserLevelInf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserLevelInf.Merge(m, src)
}
func (m *UserLevelInf) XXX_Size() int {
	return xxx_messageInfo_UserLevelInf.Size(m)
}
func (m *UserLevelInf) XXX_DiscardUnknown() {
	xxx_messageInfo_UserLevelInf.DiscardUnknown(m)
}

var xxx_messageInfo_UserLevelInf proto.InternalMessageInfo

func (m *UserLevelInf) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserLevelInf) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserLevelInf) GetGrowthPoint() int64 {
	if m != nil {
		return m.GrowthPoint
	}
	return 0
}

func (m *UserLevelInf) GetDefaultStatus() int64 {
	if m != nil {
		return m.DefaultStatus
	}
	return 0
}

func (m *UserLevelInf) GetFreeFreightPoint() float32 {
	if m != nil {
		return m.FreeFreightPoint
	}
	return 0
}

func (m *UserLevelInf) GetCommentGrowthPoint() int64 {
	if m != nil {
		return m.CommentGrowthPoint
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgeFreeFreight() int64 {
	if m != nil {
		return m.PriviledgeFreeFreight
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgeSignIn() int64 {
	if m != nil {
		return m.PriviledgeSignIn
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgeComment() int64 {
	if m != nil {
		return m.PriviledgeComment
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgePromotion() int64 {
	if m != nil {
		return m.PriviledgePromotion
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgeMemberPrice() int64 {
	if m != nil {
		return m.PriviledgeMemberPrice
	}
	return 0
}

func (m *UserLevelInf) GetPriviledgeBirthday() int64 {
	if m != nil {
		return m.PriviledgeBirthday
	}
	return 0
}

func (m *UserLevelInf) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

type In_GetUserLevelInfo struct {
	UserLevel            int64    `protobuf:"varint,1,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	UserPoint            uint64   `protobuf:"varint,2,opt,name=user_point,json=userPoint,proto3" json:"user_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserLevelInfo) Reset()         { *m = In_GetUserLevelInfo{} }
func (m *In_GetUserLevelInfo) String() string { return proto.CompactTextString(m) }
func (*In_GetUserLevelInfo) ProtoMessage()    {}
func (*In_GetUserLevelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{2}
}

func (m *In_GetUserLevelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserLevelInfo.Unmarshal(m, b)
}
func (m *In_GetUserLevelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserLevelInfo.Marshal(b, m, deterministic)
}
func (m *In_GetUserLevelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserLevelInfo.Merge(m, src)
}
func (m *In_GetUserLevelInfo) XXX_Size() int {
	return xxx_messageInfo_In_GetUserLevelInfo.Size(m)
}
func (m *In_GetUserLevelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserLevelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserLevelInfo proto.InternalMessageInfo

func (m *In_GetUserLevelInfo) GetUserLevel() int64 {
	if m != nil {
		return m.UserLevel
	}
	return 0
}

func (m *In_GetUserLevelInfo) GetUserPoint() uint64 {
	if m != nil {
		return m.UserPoint
	}
	return 0
}

type Out_GetUserLevelInfo struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserLevelInf         *UserLevelInf `protobuf:"bytes,3,opt,name=user_level_inf,json=userLevelInf,proto3" json:"user_level_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_GetUserLevelInfo) Reset()         { *m = Out_GetUserLevelInfo{} }
func (m *Out_GetUserLevelInfo) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserLevelInfo) ProtoMessage()    {}
func (*Out_GetUserLevelInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{3}
}

func (m *Out_GetUserLevelInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserLevelInfo.Unmarshal(m, b)
}
func (m *Out_GetUserLevelInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserLevelInfo.Marshal(b, m, deterministic)
}
func (m *Out_GetUserLevelInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserLevelInfo.Merge(m, src)
}
func (m *Out_GetUserLevelInfo) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserLevelInfo.Size(m)
}
func (m *Out_GetUserLevelInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserLevelInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserLevelInfo proto.InternalMessageInfo

func (m *Out_GetUserLevelInfo) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Out_GetUserLevelInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserLevelInfo) GetUserLevelInf() *UserLevelInf {
	if m != nil {
		return m.UserLevelInf
	}
	return nil
}

type In_UpdateUserLevel struct {
	UserLevelInf         *UserLevelInf `protobuf:"bytes,1,opt,name=user_level_inf,json=userLevelInf,proto3" json:"user_level_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *In_UpdateUserLevel) Reset()         { *m = In_UpdateUserLevel{} }
func (m *In_UpdateUserLevel) String() string { return proto.CompactTextString(m) }
func (*In_UpdateUserLevel) ProtoMessage()    {}
func (*In_UpdateUserLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{4}
}

func (m *In_UpdateUserLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateUserLevel.Unmarshal(m, b)
}
func (m *In_UpdateUserLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateUserLevel.Marshal(b, m, deterministic)
}
func (m *In_UpdateUserLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateUserLevel.Merge(m, src)
}
func (m *In_UpdateUserLevel) XXX_Size() int {
	return xxx_messageInfo_In_UpdateUserLevel.Size(m)
}
func (m *In_UpdateUserLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateUserLevel.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateUserLevel proto.InternalMessageInfo

func (m *In_UpdateUserLevel) GetUserLevelInf() *UserLevelInf {
	if m != nil {
		return m.UserLevelInf
	}
	return nil
}

type Out_UpdateUserLevel struct {
	Success              bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	UserLevelInf         *UserLevelInf `protobuf:"bytes,3,opt,name=user_level_inf,json=userLevelInf,proto3" json:"user_level_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_UpdateUserLevel) Reset()         { *m = Out_UpdateUserLevel{} }
func (m *Out_UpdateUserLevel) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateUserLevel) ProtoMessage()    {}
func (*Out_UpdateUserLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{5}
}

func (m *Out_UpdateUserLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateUserLevel.Unmarshal(m, b)
}
func (m *Out_UpdateUserLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateUserLevel.Marshal(b, m, deterministic)
}
func (m *Out_UpdateUserLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateUserLevel.Merge(m, src)
}
func (m *Out_UpdateUserLevel) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateUserLevel.Size(m)
}
func (m *Out_UpdateUserLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateUserLevel.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateUserLevel proto.InternalMessageInfo

func (m *Out_UpdateUserLevel) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Out_UpdateUserLevel) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateUserLevel) GetUserLevelInf() *UserLevelInf {
	if m != nil {
		return m.UserLevelInf
	}
	return nil
}

type In_GetUserLevels struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserLevels) Reset()         { *m = In_GetUserLevels{} }
func (m *In_GetUserLevels) String() string { return proto.CompactTextString(m) }
func (*In_GetUserLevels) ProtoMessage()    {}
func (*In_GetUserLevels) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{6}
}

func (m *In_GetUserLevels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserLevels.Unmarshal(m, b)
}
func (m *In_GetUserLevels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserLevels.Marshal(b, m, deterministic)
}
func (m *In_GetUserLevels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserLevels.Merge(m, src)
}
func (m *In_GetUserLevels) XXX_Size() int {
	return xxx_messageInfo_In_GetUserLevels.Size(m)
}
func (m *In_GetUserLevels) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserLevels.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserLevels proto.InternalMessageInfo

func (m *In_GetUserLevels) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetUserLevels) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetUserLevels) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetUserLevels) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetUserLevels) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetUserLevels struct {
	Error                *Error          `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64           `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64           `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserLevelInfList     []*UserLevelInf `protobuf:"bytes,5,rep,name=user_level_inf_list,json=userLevelInfList,proto3" json:"user_level_inf_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Out_GetUserLevels) Reset()         { *m = Out_GetUserLevels{} }
func (m *Out_GetUserLevels) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserLevels) ProtoMessage()    {}
func (*Out_GetUserLevels) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{7}
}

func (m *Out_GetUserLevels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserLevels.Unmarshal(m, b)
}
func (m *Out_GetUserLevels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserLevels.Marshal(b, m, deterministic)
}
func (m *Out_GetUserLevels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserLevels.Merge(m, src)
}
func (m *Out_GetUserLevels) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserLevels.Size(m)
}
func (m *Out_GetUserLevels) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserLevels.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserLevels proto.InternalMessageInfo

func (m *Out_GetUserLevels) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserLevels) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetUserLevels) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetUserLevels) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetUserLevels) GetUserLevelInfList() []*UserLevelInf {
	if m != nil {
		return m.UserLevelInfList
	}
	return nil
}

type In_DeleteUserLevels struct {
	UserLevels           []int64  `protobuf:"varint,1,rep,packed,name=user_levels,json=userLevels,proto3" json:"user_levels,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_DeleteUserLevels) Reset()         { *m = In_DeleteUserLevels{} }
func (m *In_DeleteUserLevels) String() string { return proto.CompactTextString(m) }
func (*In_DeleteUserLevels) ProtoMessage()    {}
func (*In_DeleteUserLevels) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{8}
}

func (m *In_DeleteUserLevels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteUserLevels.Unmarshal(m, b)
}
func (m *In_DeleteUserLevels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteUserLevels.Marshal(b, m, deterministic)
}
func (m *In_DeleteUserLevels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteUserLevels.Merge(m, src)
}
func (m *In_DeleteUserLevels) XXX_Size() int {
	return xxx_messageInfo_In_DeleteUserLevels.Size(m)
}
func (m *In_DeleteUserLevels) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteUserLevels.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteUserLevels proto.InternalMessageInfo

func (m *In_DeleteUserLevels) GetUserLevels() []int64 {
	if m != nil {
		return m.UserLevels
	}
	return nil
}

type Out_DeleteUserLevels struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteUserLevels) Reset()         { *m = Out_DeleteUserLevels{} }
func (m *Out_DeleteUserLevels) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteUserLevels) ProtoMessage()    {}
func (*Out_DeleteUserLevels) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{9}
}

func (m *Out_DeleteUserLevels) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteUserLevels.Unmarshal(m, b)
}
func (m *Out_DeleteUserLevels) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteUserLevels.Marshal(b, m, deterministic)
}
func (m *Out_DeleteUserLevels) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteUserLevels.Merge(m, src)
}
func (m *Out_DeleteUserLevels) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteUserLevels.Size(m)
}
func (m *Out_DeleteUserLevels) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteUserLevels.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteUserLevels proto.InternalMessageInfo

func (m *Out_DeleteUserLevels) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateUserLevel struct {
	UserLevel            *UserLevelInf `protobuf:"bytes,1,opt,name=user_level,json=userLevel,proto3" json:"user_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *In_CreateUserLevel) Reset()         { *m = In_CreateUserLevel{} }
func (m *In_CreateUserLevel) String() string { return proto.CompactTextString(m) }
func (*In_CreateUserLevel) ProtoMessage()    {}
func (*In_CreateUserLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{10}
}

func (m *In_CreateUserLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateUserLevel.Unmarshal(m, b)
}
func (m *In_CreateUserLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateUserLevel.Marshal(b, m, deterministic)
}
func (m *In_CreateUserLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateUserLevel.Merge(m, src)
}
func (m *In_CreateUserLevel) XXX_Size() int {
	return xxx_messageInfo_In_CreateUserLevel.Size(m)
}
func (m *In_CreateUserLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateUserLevel.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateUserLevel proto.InternalMessageInfo

func (m *In_CreateUserLevel) GetUserLevel() *UserLevelInf {
	if m != nil {
		return m.UserLevel
	}
	return nil
}

type Out_CreateUserLevel struct {
	Error                *Error        `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserLevelInf         *UserLevelInf `protobuf:"bytes,2,opt,name=user_level_inf,json=userLevelInf,proto3" json:"user_level_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Out_CreateUserLevel) Reset()         { *m = Out_CreateUserLevel{} }
func (m *Out_CreateUserLevel) String() string { return proto.CompactTextString(m) }
func (*Out_CreateUserLevel) ProtoMessage()    {}
func (*Out_CreateUserLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f60c8be9389da1f, []int{11}
}

func (m *Out_CreateUserLevel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateUserLevel.Unmarshal(m, b)
}
func (m *Out_CreateUserLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateUserLevel.Marshal(b, m, deterministic)
}
func (m *Out_CreateUserLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateUserLevel.Merge(m, src)
}
func (m *Out_CreateUserLevel) XXX_Size() int {
	return xxx_messageInfo_Out_CreateUserLevel.Size(m)
}
func (m *Out_CreateUserLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateUserLevel.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateUserLevel proto.InternalMessageInfo

func (m *Out_CreateUserLevel) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateUserLevel) GetUserLevelInf() *UserLevelInf {
	if m != nil {
		return m.UserLevelInf
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "user_level.Error")
	proto.RegisterType((*UserLevelInf)(nil), "user_level.User_level_inf")
	proto.RegisterType((*In_GetUserLevelInfo)(nil), "user_level.In_GetUserLevelInfo")
	proto.RegisterType((*Out_GetUserLevelInfo)(nil), "user_level.Out_GetUserLevelInfo")
	proto.RegisterType((*In_UpdateUserLevel)(nil), "user_level.In_UpdateUserLevel")
	proto.RegisterType((*Out_UpdateUserLevel)(nil), "user_level.Out_UpdateUserLevel")
	proto.RegisterType((*In_GetUserLevels)(nil), "user_level.In_GetUserLevels")
	proto.RegisterType((*Out_GetUserLevels)(nil), "user_level.Out_GetUserLevels")
	proto.RegisterType((*In_DeleteUserLevels)(nil), "user_level.In_DeleteUserLevels")
	proto.RegisterType((*Out_DeleteUserLevels)(nil), "user_level.Out_DeleteUserLevels")
	proto.RegisterType((*In_CreateUserLevel)(nil), "user_level.In_CreateUserLevel")
	proto.RegisterType((*Out_CreateUserLevel)(nil), "user_level.Out_CreateUserLevel")
}

func init() { proto.RegisterFile("user_level.proto", fileDescriptor_4f60c8be9389da1f) }

var fileDescriptor_4f60c8be9389da1f = []byte{
	// 784 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcd, 0x6e, 0xeb, 0x44,
	0x14, 0x8e, 0xe3, 0xa4, 0x6d, 0x4e, 0xda, 0x90, 0x4e, 0x82, 0x30, 0x11, 0xa5, 0xc1, 0x12, 0x22,
	0x0b, 0x28, 0x50, 0x44, 0x25, 0x56, 0x20, 0x0a, 0xad, 0x22, 0x0a, 0xad, 0xdc, 0x16, 0x96, 0x96,
	0x1b, 0x9f, 0x24, 0x23, 0xfc, 0x13, 0xcd, 0x8c, 0x8b, 0xba, 0xe3, 0x2d, 0x90, 0xb8, 0xcb, 0xfb,
	0x14, 0xf7, 0x11, 0xee, 0x5b, 0x5d, 0xcd, 0x8c, 0x13, 0x3b, 0xe3, 0xa8, 0x3f, 0xbb, 0xbb, 0xf3,
	0x9c, 0xef, 0x9c, 0x6f, 0xce, 0xcf, 0x37, 0x47, 0x86, 0x6e, 0xc6, 0x91, 0xf9, 0x11, 0xde, 0x63,
	0x74, 0xb4, 0x60, 0xa9, 0x48, 0x09, 0x14, 0x16, 0xf7, 0x7b, 0x68, 0xfe, 0xca, 0x58, 0xca, 0x08,
	0x81, 0xc6, 0x24, 0x0d, 0xd1, 0xb1, 0x86, 0xd6, 0xa8, 0xe9, 0xa9, 0x6f, 0xe2, 0xc0, 0x76, 0x8c,
	0x9c, 0x07, 0x33, 0x74, 0xea, 0x43, 0x6b, 0xd4, 0xf2, 0x96, 0x47, 0xf7, 0x75, 0x03, 0x3a, 0xb7,
	0x2b, 0x16, 0x9f, 0x26, 0x53, 0xd2, 0x81, 0x3a, 0x0d, 0x55, 0xb8, 0xed, 0xd5, 0x69, 0x28, 0x09,
	0x93, 0x20, 0x5e, 0x46, 0xaa, 0x6f, 0xf2, 0x19, 0xec, 0xce, 0x58, 0xfa, 0x8f, 0x98, 0xfb, 0x8b,
	0x94, 0x26, 0xc2, 0xb1, 0x95, 0x77, 0x5b, 0xdb, 0xae, 0xa4, 0x89, 0x7c, 0x0e, 0x9d, 0x10, 0xa7,
	0x41, 0x16, 0x09, 0x9f, 0x8b, 0x40, 0x64, 0xdc, 0x69, 0x28, 0xa7, 0xbd, 0xdc, 0x7a, 0xad, 0x8c,
	0xe4, 0x4b, 0x20, 0x53, 0x86, 0xe8, 0x4f, 0x19, 0xd2, 0xd9, 0x5c, 0xe4, 0x7c, 0xcd, 0xa1, 0x35,
	0xaa, 0x7b, 0x5d, 0x89, 0x9c, 0x69, 0x40, 0x93, 0x7e, 0x03, 0xfd, 0x49, 0x1a, 0xc7, 0x98, 0x08,
	0x7f, 0xed, 0xfe, 0x2d, 0x45, 0x4d, 0x72, 0xec, 0xbc, 0x94, 0xc6, 0x09, 0x7c, 0xb4, 0x60, 0xf4,
	0x9e, 0x46, 0x18, 0xce, 0xd4, 0x2d, 0xab, 0xab, 0x9c, 0x6d, 0x15, 0xf4, 0x61, 0x01, 0x9f, 0x15,
	0xd7, 0xc9, 0xbc, 0x4a, 0x71, 0x9c, 0xce, 0x12, 0x9f, 0x26, 0xce, 0x8e, 0x0a, 0xe9, 0x16, 0xc8,
	0x35, 0x9d, 0x25, 0xe3, 0x84, 0x7c, 0xb5, 0xe6, 0x9d, 0xa7, 0xe1, 0xb4, 0x94, 0xf7, 0x7e, 0x81,
	0x9c, 0x6a, 0x80, 0x7c, 0x0b, 0xfd, 0x92, 0xfb, 0x82, 0xa5, 0x71, 0x2a, 0x68, 0x9a, 0x38, 0xa0,
	0x02, 0x7a, 0x05, 0x76, 0xb5, 0x84, 0x8c, 0x3a, 0x62, 0x8c, 0xef, 0x90, 0xf9, 0x0b, 0x46, 0x27,
	0xe8, 0xb4, 0xcd, 0x3a, 0x7e, 0x57, 0xe8, 0x95, 0x04, 0xc9, 0xd7, 0x50, 0xa2, 0xf3, 0xef, 0x28,
	0x13, 0xf3, 0x30, 0x78, 0x70, 0x76, 0x75, 0xc3, 0x0a, 0xe8, 0xe7, 0x1c, 0x51, 0xe3, 0x4e, 0x05,
	0x3a, 0x7b, 0xf9, 0xb8, 0x53, 0x81, 0xee, 0x35, 0xf4, 0xc6, 0x89, 0x7f, 0x8e, 0x42, 0x4a, 0xe5,
	0x42, 0x2a, 0x65, 0x9c, 0x4c, 0x53, 0x72, 0x00, 0x25, 0x05, 0xe6, 0x8a, 0x69, 0x65, 0x4b, 0x97,
	0x15, 0xac, 0x47, 0x24, 0xe5, 0xd3, 0xd0, 0xb0, 0x9a, 0x8c, 0xfb, 0xca, 0x82, 0xfe, 0x65, 0x26,
	0xaa, 0xb4, 0x0e, 0x6c, 0xf3, 0x6c, 0x32, 0x41, 0xce, 0x15, 0xe7, 0x8e, 0xb7, 0x3c, 0x92, 0x2f,
	0xa0, 0x89, 0x52, 0xe4, 0x8a, 0xac, 0x7d, 0xbc, 0x7f, 0x54, 0x7a, 0x12, 0x4a, 0xfd, 0x9e, 0xc6,
	0xc9, 0x4f, 0xd0, 0xc9, 0xd6, 0x54, 0xad, 0x14, 0xda, 0x3e, 0x1e, 0x94, 0x23, 0xd6, 0x75, 0xef,
	0xed, 0x66, 0xa5, 0x2c, 0xdc, 0x3f, 0x81, 0x8c, 0x13, 0xff, 0x76, 0x11, 0x06, 0x02, 0x57, 0xe9,
	0x6d, 0xe0, 0xb5, 0x5e, 0xc8, 0xfb, 0xbf, 0x05, 0x3d, 0x59, 0xb5, 0xc9, 0xfc, 0x5e, 0x14, 0xfd,
	0x9f, 0x05, 0x5d, 0x63, 0xd0, 0x9c, 0xf4, 0xa1, 0x19, 0xd1, 0x98, 0x8a, 0x7c, 0xc0, 0xfa, 0x20,
	0xad, 0x8b, 0x60, 0x86, 0x5c, 0x65, 0x65, 0x7b, 0xfa, 0x20, 0x47, 0xce, 0x31, 0x60, 0x93, 0xb9,
	0xff, 0x37, 0x3e, 0xa8, 0xeb, 0x5b, 0x5e, 0x4b, 0x5b, 0x7e, 0xc3, 0x07, 0x05, 0x8b, 0x80, 0x09,
	0x5f, 0xd0, 0x18, 0xd5, 0x3e, 0x90, 0xb0, 0xb4, 0xdc, 0xd0, 0x18, 0xc9, 0xc7, 0xb0, 0x83, 0x49,
	0xa8, 0xc1, 0xa6, 0xde, 0x53, 0x98, 0x84, 0x12, 0x72, 0xdf, 0x5a, 0xb0, 0x6f, 0x8a, 0xa5, 0xd4,
	0x1a, 0xeb, 0x89, 0xd6, 0xac, 0x6a, 0xa8, 0x6f, 0xac, 0xc1, 0x2e, 0xd7, 0xd0, 0x87, 0xa6, 0x48,
	0x45, 0x10, 0xe5, 0xfb, 0x4a, 0x1f, 0xc8, 0x18, 0x7a, 0xeb, 0xcd, 0xf5, 0x23, 0xca, 0xe5, 0xa2,
	0xb2, 0x9f, 0xe8, 0x70, 0xb7, 0xdc, 0xe1, 0x0b, 0xca, 0x85, 0x7b, 0xa2, 0x5e, 0xd3, 0x2f, 0x18,
	0x61, 0x49, 0x00, 0x9c, 0x1c, 0x42, 0xbb, 0x60, 0x91, 0x2a, 0xb0, 0x47, 0xb6, 0x07, 0xab, 0x68,
	0xee, 0xfe, 0xa8, 0xdf, 0x4b, 0x25, 0xf0, 0xb9, 0x5d, 0x70, 0x2f, 0x95, 0xa6, 0x4f, 0x19, 0xae,
	0x29, 0xef, 0x87, 0xca, 0x2b, 0x7e, 0xbc, 0xa0, 0xe2, 0x85, 0xbb, 0xff, 0xe6, 0x62, 0x36, 0x29,
	0x9f, 0x3d, 0x97, 0xaa, 0x64, 0xeb, 0x2f, 0x93, 0xec, 0xf1, 0x1b, 0x1b, 0x5a, 0xc5, 0xc5, 0x7f,
	0x41, 0xb7, 0xb2, 0x4e, 0x0e, 0xcb, 0x5c, 0x1b, 0xd6, 0xd8, 0x60, 0x58, 0x76, 0xd8, 0xb4, 0x91,
	0xdc, 0x1a, 0xb9, 0x81, 0x0f, 0xcc, 0x17, 0xfb, 0xa9, 0xc1, 0x6b, 0xe0, 0x83, 0x43, 0x93, 0xd6,
	0x70, 0x70, 0x6b, 0xe4, 0x0f, 0xd8, 0x5b, 0x17, 0xf4, 0x27, 0x8f, 0xe4, 0xca, 0x07, 0x07, 0x8f,
	0x25, 0xca, 0xdd, 0x9a, 0x2c, 0xbf, 0x2a, 0x2b, 0x83, 0xd2, 0x74, 0xa8, 0x96, 0x6f, 0x7a, 0xe8,
	0xf2, 0xcd, 0x19, 0x9b, 0xe5, 0x1b, 0x78, 0xb5, 0x7c, 0xc3, 0xc1, 0xad, 0xdd, 0x6d, 0xa9, 0xdf,
	0x98, 0xef, 0xde, 0x05, 0x00, 0x00, 0xff, 0xff, 0x03, 0x52, 0xf3, 0xef, 0xda, 0x08, 0x00, 0x00,
}
