// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_full_reduction.proto

package product_full_reduction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProductFullReduction struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	FullPrice            float32  `protobuf:"fixed32,3,opt,name=full_price,json=fullPrice,proto3" json:"full_price,omitempty"`
	ReducePrice          int64    `protobuf:"varint,4,opt,name=reduce_price,json=reducePrice,proto3" json:"reduce_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductFullReduction) Reset()         { *m = ProductFullReduction{} }
func (m *ProductFullReduction) String() string { return proto.CompactTextString(m) }
func (*ProductFullReduction) ProtoMessage()    {}
func (*ProductFullReduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{0}
}

func (m *ProductFullReduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductFullReduction.Unmarshal(m, b)
}
func (m *ProductFullReduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductFullReduction.Marshal(b, m, deterministic)
}
func (m *ProductFullReduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductFullReduction.Merge(m, src)
}
func (m *ProductFullReduction) XXX_Size() int {
	return xxx_messageInfo_ProductFullReduction.Size(m)
}
func (m *ProductFullReduction) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductFullReduction.DiscardUnknown(m)
}

var xxx_messageInfo_ProductFullReduction proto.InternalMessageInfo

func (m *ProductFullReduction) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductFullReduction) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductFullReduction) GetFullPrice() float32 {
	if m != nil {
		return m.FullPrice
	}
	return 0
}

func (m *ProductFullReduction) GetReducePrice() int64 {
	if m != nil {
		return m.ReducePrice
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetProductFullReductionById struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductFullReductionById) Reset()         { *m = In_GetProductFullReductionById{} }
func (m *In_GetProductFullReductionById) String() string { return proto.CompactTextString(m) }
func (*In_GetProductFullReductionById) ProtoMessage()    {}
func (*In_GetProductFullReductionById) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{2}
}

func (m *In_GetProductFullReductionById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductFullReductionById.Unmarshal(m, b)
}
func (m *In_GetProductFullReductionById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductFullReductionById.Marshal(b, m, deterministic)
}
func (m *In_GetProductFullReductionById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductFullReductionById.Merge(m, src)
}
func (m *In_GetProductFullReductionById) XXX_Size() int {
	return xxx_messageInfo_In_GetProductFullReductionById.Size(m)
}
func (m *In_GetProductFullReductionById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductFullReductionById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductFullReductionById proto.InternalMessageInfo

func (m *In_GetProductFullReductionById) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Out_GetProductFullReductionById struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_GetProductFullReductionById) Reset()         { *m = Out_GetProductFullReductionById{} }
func (m *Out_GetProductFullReductionById) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductFullReductionById) ProtoMessage()    {}
func (*Out_GetProductFullReductionById) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{3}
}

func (m *Out_GetProductFullReductionById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductFullReductionById.Unmarshal(m, b)
}
func (m *Out_GetProductFullReductionById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductFullReductionById.Marshal(b, m, deterministic)
}
func (m *Out_GetProductFullReductionById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductFullReductionById.Merge(m, src)
}
func (m *Out_GetProductFullReductionById) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductFullReductionById.Size(m)
}
func (m *Out_GetProductFullReductionById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductFullReductionById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductFullReductionById proto.InternalMessageInfo

func (m *Out_GetProductFullReductionById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductFullReductionById) GetProductFullReduction() *ProductFullReduction {
	if m != nil {
		return m.ProductFullReduction
	}
	return nil
}

type Out_UpdateProductFullReductionInfo struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_UpdateProductFullReductionInfo) Reset()         { *m = Out_UpdateProductFullReductionInfo{} }
func (m *Out_UpdateProductFullReductionInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateProductFullReductionInfo) ProtoMessage()    {}
func (*Out_UpdateProductFullReductionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{4}
}

func (m *Out_UpdateProductFullReductionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateProductFullReductionInfo.Unmarshal(m, b)
}
func (m *Out_UpdateProductFullReductionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateProductFullReductionInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateProductFullReductionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateProductFullReductionInfo.Merge(m, src)
}
func (m *Out_UpdateProductFullReductionInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateProductFullReductionInfo.Size(m)
}
func (m *Out_UpdateProductFullReductionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateProductFullReductionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateProductFullReductionInfo proto.InternalMessageInfo

func (m *Out_UpdateProductFullReductionInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateProductFullReductionInfo) GetProductFullReduction() *ProductFullReduction {
	if m != nil {
		return m.ProductFullReduction
	}
	return nil
}

type In_UpdateProductFullReductionInfo struct {
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,1,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *In_UpdateProductFullReductionInfo) Reset()         { *m = In_UpdateProductFullReductionInfo{} }
func (m *In_UpdateProductFullReductionInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateProductFullReductionInfo) ProtoMessage()    {}
func (*In_UpdateProductFullReductionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{5}
}

func (m *In_UpdateProductFullReductionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateProductFullReductionInfo.Unmarshal(m, b)
}
func (m *In_UpdateProductFullReductionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateProductFullReductionInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateProductFullReductionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateProductFullReductionInfo.Merge(m, src)
}
func (m *In_UpdateProductFullReductionInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateProductFullReductionInfo.Size(m)
}
func (m *In_UpdateProductFullReductionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateProductFullReductionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateProductFullReductionInfo proto.InternalMessageInfo

func (m *In_UpdateProductFullReductionInfo) GetProductFullReduction() *ProductFullReduction {
	if m != nil {
		return m.ProductFullReduction
	}
	return nil
}

type In_GetProductFullReductions struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductFullReductions) Reset()         { *m = In_GetProductFullReductions{} }
func (m *In_GetProductFullReductions) String() string { return proto.CompactTextString(m) }
func (*In_GetProductFullReductions) ProtoMessage()    {}
func (*In_GetProductFullReductions) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{6}
}

func (m *In_GetProductFullReductions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductFullReductions.Unmarshal(m, b)
}
func (m *In_GetProductFullReductions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductFullReductions.Marshal(b, m, deterministic)
}
func (m *In_GetProductFullReductions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductFullReductions.Merge(m, src)
}
func (m *In_GetProductFullReductions) XXX_Size() int {
	return xxx_messageInfo_In_GetProductFullReductions.Size(m)
}
func (m *In_GetProductFullReductions) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductFullReductions.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductFullReductions proto.InternalMessageInfo

func (m *In_GetProductFullReductions) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetProductFullReductions) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetProductFullReductions) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetProductFullReductions) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetProductFullReductions) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetProductFullReductions struct {
	Error                    *Error                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                    int64                   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                    int64                   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                    int64                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductFullReductionList []*ProductFullReduction `protobuf:"bytes,5,rep,name=productFullReduction_list,json=productFullReductionList,proto3" json:"productFullReduction_list,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                `json:"-"`
	XXX_unrecognized         []byte                  `json:"-"`
	XXX_sizecache            int32                   `json:"-"`
}

func (m *Out_GetProductFullReductions) Reset()         { *m = Out_GetProductFullReductions{} }
func (m *Out_GetProductFullReductions) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductFullReductions) ProtoMessage()    {}
func (*Out_GetProductFullReductions) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{7}
}

func (m *Out_GetProductFullReductions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductFullReductions.Unmarshal(m, b)
}
func (m *Out_GetProductFullReductions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductFullReductions.Marshal(b, m, deterministic)
}
func (m *Out_GetProductFullReductions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductFullReductions.Merge(m, src)
}
func (m *Out_GetProductFullReductions) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductFullReductions.Size(m)
}
func (m *Out_GetProductFullReductions) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductFullReductions.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductFullReductions proto.InternalMessageInfo

func (m *Out_GetProductFullReductions) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductFullReductions) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetProductFullReductions) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetProductFullReductions) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetProductFullReductions) GetProductFullReductionList() []*ProductFullReduction {
	if m != nil {
		return m.ProductFullReductionList
	}
	return nil
}

type In_DeleteProductFullReductions struct {
	ProductFullReductionList []int64  `protobuf:"varint,1,rep,packed,name=ProductFullReduction_list,json=ProductFullReductionList,proto3" json:"ProductFullReduction_list,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *In_DeleteProductFullReductions) Reset()         { *m = In_DeleteProductFullReductions{} }
func (m *In_DeleteProductFullReductions) String() string { return proto.CompactTextString(m) }
func (*In_DeleteProductFullReductions) ProtoMessage()    {}
func (*In_DeleteProductFullReductions) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{8}
}

func (m *In_DeleteProductFullReductions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteProductFullReductions.Unmarshal(m, b)
}
func (m *In_DeleteProductFullReductions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteProductFullReductions.Marshal(b, m, deterministic)
}
func (m *In_DeleteProductFullReductions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteProductFullReductions.Merge(m, src)
}
func (m *In_DeleteProductFullReductions) XXX_Size() int {
	return xxx_messageInfo_In_DeleteProductFullReductions.Size(m)
}
func (m *In_DeleteProductFullReductions) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteProductFullReductions.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteProductFullReductions proto.InternalMessageInfo

func (m *In_DeleteProductFullReductions) GetProductFullReductionList() []int64 {
	if m != nil {
		return m.ProductFullReductionList
	}
	return nil
}

type Out_DeleteProductFullReductions struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteProductFullReductions) Reset()         { *m = Out_DeleteProductFullReductions{} }
func (m *Out_DeleteProductFullReductions) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteProductFullReductions) ProtoMessage()    {}
func (*Out_DeleteProductFullReductions) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{9}
}

func (m *Out_DeleteProductFullReductions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteProductFullReductions.Unmarshal(m, b)
}
func (m *Out_DeleteProductFullReductions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteProductFullReductions.Marshal(b, m, deterministic)
}
func (m *Out_DeleteProductFullReductions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteProductFullReductions.Merge(m, src)
}
func (m *Out_DeleteProductFullReductions) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteProductFullReductions.Size(m)
}
func (m *Out_DeleteProductFullReductions) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteProductFullReductions.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteProductFullReductions proto.InternalMessageInfo

func (m *Out_DeleteProductFullReductions) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateProductFullReduction struct {
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,1,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *In_CreateProductFullReduction) Reset()         { *m = In_CreateProductFullReduction{} }
func (m *In_CreateProductFullReduction) String() string { return proto.CompactTextString(m) }
func (*In_CreateProductFullReduction) ProtoMessage()    {}
func (*In_CreateProductFullReduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{10}
}

func (m *In_CreateProductFullReduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateProductFullReduction.Unmarshal(m, b)
}
func (m *In_CreateProductFullReduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateProductFullReduction.Marshal(b, m, deterministic)
}
func (m *In_CreateProductFullReduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateProductFullReduction.Merge(m, src)
}
func (m *In_CreateProductFullReduction) XXX_Size() int {
	return xxx_messageInfo_In_CreateProductFullReduction.Size(m)
}
func (m *In_CreateProductFullReduction) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateProductFullReduction.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateProductFullReduction proto.InternalMessageInfo

func (m *In_CreateProductFullReduction) GetProductFullReduction() *ProductFullReduction {
	if m != nil {
		return m.ProductFullReduction
	}
	return nil
}

type Out_CreateProductFullReduction struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductFullReduction *ProductFullReduction `protobuf:"bytes,2,opt,name=productFullReduction,proto3" json:"productFullReduction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_CreateProductFullReduction) Reset()         { *m = Out_CreateProductFullReduction{} }
func (m *Out_CreateProductFullReduction) String() string { return proto.CompactTextString(m) }
func (*Out_CreateProductFullReduction) ProtoMessage()    {}
func (*Out_CreateProductFullReduction) Descriptor() ([]byte, []int) {
	return fileDescriptor_25d7ce29dc5df301, []int{11}
}

func (m *Out_CreateProductFullReduction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateProductFullReduction.Unmarshal(m, b)
}
func (m *Out_CreateProductFullReduction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateProductFullReduction.Marshal(b, m, deterministic)
}
func (m *Out_CreateProductFullReduction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateProductFullReduction.Merge(m, src)
}
func (m *Out_CreateProductFullReduction) XXX_Size() int {
	return xxx_messageInfo_Out_CreateProductFullReduction.Size(m)
}
func (m *Out_CreateProductFullReduction) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateProductFullReduction.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateProductFullReduction proto.InternalMessageInfo

func (m *Out_CreateProductFullReduction) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateProductFullReduction) GetProductFullReduction() *ProductFullReduction {
	if m != nil {
		return m.ProductFullReduction
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductFullReduction)(nil), "product_full_reduction.Product_full_reduction")
	proto.RegisterType((*Error)(nil), "product_full_reduction.Error")
	proto.RegisterType((*In_GetProductFullReductionById)(nil), "product_full_reduction.In_GetProductFullReductionById")
	proto.RegisterType((*Out_GetProductFullReductionById)(nil), "product_full_reduction.Out_GetProductFullReductionById")
	proto.RegisterType((*Out_UpdateProductFullReductionInfo)(nil), "product_full_reduction.Out_UpdateProductFullReductionInfo")
	proto.RegisterType((*In_UpdateProductFullReductionInfo)(nil), "product_full_reduction.In_UpdateProductFullReductionInfo")
	proto.RegisterType((*In_GetProductFullReductions)(nil), "product_full_reduction.In_GetProductFullReductions")
	proto.RegisterType((*Out_GetProductFullReductions)(nil), "product_full_reduction.Out_GetProductFullReductions")
	proto.RegisterType((*In_DeleteProductFullReductions)(nil), "product_full_reduction.In_DeleteProductFullReductions")
	proto.RegisterType((*Out_DeleteProductFullReductions)(nil), "product_full_reduction.Out_DeleteProductFullReductions")
	proto.RegisterType((*In_CreateProductFullReduction)(nil), "product_full_reduction.In_CreateProductFullReduction")
	proto.RegisterType((*Out_CreateProductFullReduction)(nil), "product_full_reduction.Out_CreateProductFullReduction")
}

func init() { proto.RegisterFile("product_full_reduction.proto", fileDescriptor_25d7ce29dc5df301) }

var fileDescriptor_25d7ce29dc5df301 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x8f, 0xd3, 0x3e,
	0x10, 0xad, 0x93, 0xcd, 0xef, 0x47, 0x67, 0x11, 0x07, 0xab, 0x5a, 0xa5, 0xed, 0xb6, 0x74, 0x7d,
	0xea, 0xa9, 0x42, 0x5d, 0x76, 0x11, 0x70, 0xe3, 0x7f, 0x04, 0x12, 0x55, 0x04, 0xdc, 0x50, 0x94,
	0x6d, 0xbc, 0x8b, 0xb5, 0x69, 0x12, 0xd9, 0xee, 0xa1, 0x57, 0x38, 0xac, 0x38, 0x20, 0x71, 0xe5,
	0xca, 0xb7, 0x00, 0x89, 0x0f, 0xc6, 0x0d, 0xd9, 0x49, 0x11, 0x42, 0xb6, 0x2b, 0x2a, 0x84, 0xf6,
	0x16, 0xcf, 0xf8, 0xbd, 0xbc, 0x99, 0x79, 0x76, 0x02, 0xfb, 0x15, 0x2f, 0xb3, 0xe5, 0x5c, 0x26,
	0xa7, 0xcb, 0x3c, 0x4f, 0x38, 0x55, 0xcf, 0xac, 0x2c, 0x26, 0x15, 0x2f, 0x65, 0x89, 0xf7, 0xcc,
	0x59, 0xf2, 0x1e, 0xc1, 0xde, 0xcc, 0x98, 0xc2, 0xd7, 0xc0, 0x63, 0x59, 0x88, 0x46, 0x68, 0xec,
	0xc7, 0x1e, 0xcb, 0xf0, 0x00, 0x60, 0x4d, 0xc2, 0xb2, 0xd0, 0x1b, 0xa1, 0x71, 0x3b, 0x6e, 0x37,
	0x91, 0x48, 0xa7, 0x35, 0x41, 0xc5, 0xd9, 0x9c, 0x86, 0xfe, 0x08, 0x8d, 0xbd, 0xb8, 0xad, 0x22,
	0x33, 0x15, 0xc0, 0x07, 0x70, 0x55, 0x53, 0xd3, 0x66, 0xc3, 0x8e, 0xe6, 0xdd, 0xad, 0x63, 0x7a,
	0x0b, 0x39, 0x82, 0xe0, 0x21, 0xe7, 0x25, 0xc7, 0x18, 0x76, 0xe6, 0x65, 0x46, 0xf5, 0xbb, 0x83,
	0x58, 0x3f, 0xe3, 0x10, 0xfe, 0x5f, 0x50, 0x21, 0xd2, 0x33, 0xda, 0xbc, 0x7a, 0xbd, 0x24, 0x37,
	0x60, 0x18, 0x15, 0xc9, 0x63, 0x2a, 0x9b, 0x3a, 0x1e, 0x2d, 0xf3, 0x3c, 0x5e, 0x57, 0x71, 0x6f,
	0x15, 0x65, 0xbf, 0x57, 0x42, 0xbe, 0x22, 0xb8, 0xfe, 0x7c, 0x29, 0x9d, 0x98, 0x43, 0x08, 0xa8,
	0x12, 0xa3, 0x61, 0xbb, 0xd3, 0xc1, 0xc4, 0xd2, 0x5e, 0xad, 0x38, 0xae, 0xf7, 0xe2, 0x13, 0xe8,
	0x54, 0x06, 0x42, 0xad, 0x78, 0x77, 0x3a, 0xb1, 0x71, 0x98, 0x07, 0x10, 0x1b, 0xb9, 0xc8, 0x37,
	0x04, 0x44, 0x89, 0x7f, 0x59, 0x65, 0xa9, 0xa4, 0x26, 0xfd, 0x51, 0x71, 0x5a, 0x5e, 0x5e, 0xfd,
	0x17, 0x08, 0x0e, 0xa2, 0x62, 0x93, 0x7c, 0x9b, 0x12, 0xf4, 0x17, 0x95, 0x7c, 0x46, 0xd0, 0xb7,
	0x3b, 0x47, 0xe0, 0x0e, 0x04, 0x39, 0x5b, 0x30, 0xd9, 0x38, 0xa7, 0x5e, 0xa8, 0x68, 0x95, 0x9e,
	0x51, 0xa1, 0x9b, 0xe2, 0xc7, 0xf5, 0x42, 0xb9, 0x5f, 0xd0, 0x94, 0xcf, 0xdf, 0x24, 0xe7, 0x74,
	0xa5, 0xdd, 0xdf, 0x8e, 0xdb, 0x75, 0xe4, 0x29, 0x5d, 0xe9, 0xb4, 0x4c, 0xb9, 0x4c, 0x24, 0x5b,
	0xd4, 0xde, 0x57, 0x69, 0x15, 0x79, 0xc1, 0x16, 0x14, 0x77, 0xe1, 0x0a, 0x2d, 0xb2, 0x3a, 0x19,
	0xd4, 0xee, 0xa6, 0x45, 0xa6, 0x52, 0xe4, 0xad, 0x07, 0xfb, 0x0e, 0xaf, 0x8a, 0xed, 0x06, 0xfd,
	0xb3, 0x34, 0xcf, 0x58, 0x9a, 0xff, 0x6b, 0x69, 0x1d, 0x08, 0x64, 0x29, 0xd3, 0xbc, 0x39, 0xb2,
	0xf5, 0x02, 0x9f, 0x43, 0xd7, 0xd4, 0xd4, 0x24, 0x67, 0x42, 0x86, 0xc1, 0xc8, 0xdf, 0x62, 0x4a,
	0xa1, 0x89, 0xf0, 0x19, 0x13, 0x92, 0xbc, 0xd6, 0x47, 0xfc, 0x01, 0xcd, 0xa9, 0xd9, 0x32, 0x02,
	0xdf, 0x85, 0xee, 0xcc, 0x2a, 0x07, 0x8d, 0xfc, 0xb1, 0x1f, 0x87, 0x33, 0x1b, 0xfd, 0xab, 0xfa,
	0x3a, 0x70, 0xf1, 0x6f, 0xd3, 0x65, 0xf2, 0x0e, 0xc1, 0x20, 0x2a, 0x92, 0xfb, 0x9c, 0x5a, 0xac,
	0xfe, 0x4f, 0x6c, 0xfe, 0x05, 0xc1, 0x50, 0x95, 0xe7, 0x90, 0x71, 0x59, 0x2f, 0x8b, 0xe9, 0xf7,
	0x00, 0xfa, 0x26, 0xc5, 0x4f, 0xd2, 0x22, 0xcb, 0x29, 0xc7, 0x1f, 0x11, 0xf4, 0x5d, 0xb7, 0xf8,
	0xb1, 0x4d, 0x85, 0xfb, 0x8b, 0xd1, 0xbb, 0x65, 0xc3, 0x6d, 0xf8, 0x6c, 0x90, 0x16, 0xfe, 0x84,
	0x60, 0xb8, 0xe1, 0x72, 0xbb, 0xed, 0x50, 0xe5, 0x86, 0xf6, 0xee, 0xb8, 0x84, 0xb9, 0xb1, 0xa4,
	0x85, 0x2f, 0x10, 0x84, 0xf6, 0x8b, 0xe4, 0xcf, 0x7b, 0x25, 0x7a, 0x37, 0xb7, 0x68, 0x94, 0x20,
	0x2d, 0x3d, 0x38, 0xd7, 0x79, 0x73, 0x0d, 0xce, 0x81, 0x73, 0x0f, 0xce, 0x01, 0x24, 0x2d, 0xfc,
	0x01, 0x41, 0xcf, 0x71, 0x46, 0x8e, 0x1c, 0x8a, 0xec, 0xb0, 0xde, 0xb1, 0x4b, 0x90, 0x1d, 0x47,
	0x5a, 0x27, 0xff, 0xe9, 0x3f, 0xb7, 0xc3, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x45, 0x21,
	0xce, 0xd9, 0x09, 0x00, 0x00,
}
