// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_attribute.proto

package product_attribute

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//商品信息
type ProductAttribute struct {
	Id                         int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductAttributeCategoryId int64    `protobuf:"varint,2,opt,name=product_attribute_category_id,json=productAttributeCategoryId,proto3" json:"product_attribute_category_id,omitempty"`
	Name                       string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SelectType                 int64    `protobuf:"varint,4,opt,name=select_type,json=selectType,proto3" json:"select_type,omitempty"`
	InputType                  int64    `protobuf:"varint,5,opt,name=input_type,json=inputType,proto3" json:"input_type,omitempty"`
	InputList                  string   `protobuf:"bytes,6,opt,name=input_list,json=inputList,proto3" json:"input_list,omitempty"`
	Sort                       int64    `protobuf:"varint,7,opt,name=sort,proto3" json:"sort,omitempty"`
	FilterType                 int64    `protobuf:"varint,8,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	SearchType                 int64    `protobuf:"varint,9,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	RelatedStatus              int64    `protobuf:"varint,10,opt,name=related_status,json=relatedStatus,proto3" json:"related_status,omitempty"`
	HandAddStatus              int64    `protobuf:"varint,11,opt,name=hand_add_status,json=handAddStatus,proto3" json:"hand_add_status,omitempty"`
	Type                       int64    `protobuf:"varint,12,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *ProductAttribute) Reset()         { *m = ProductAttribute{} }
func (m *ProductAttribute) String() string { return proto.CompactTextString(m) }
func (*ProductAttribute) ProtoMessage()    {}
func (*ProductAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{0}
}

func (m *ProductAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductAttribute.Unmarshal(m, b)
}
func (m *ProductAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductAttribute.Marshal(b, m, deterministic)
}
func (m *ProductAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductAttribute.Merge(m, src)
}
func (m *ProductAttribute) XXX_Size() int {
	return xxx_messageInfo_ProductAttribute.Size(m)
}
func (m *ProductAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_ProductAttribute proto.InternalMessageInfo

func (m *ProductAttribute) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductAttribute) GetProductAttributeCategoryId() int64 {
	if m != nil {
		return m.ProductAttributeCategoryId
	}
	return 0
}

func (m *ProductAttribute) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductAttribute) GetSelectType() int64 {
	if m != nil {
		return m.SelectType
	}
	return 0
}

func (m *ProductAttribute) GetInputType() int64 {
	if m != nil {
		return m.InputType
	}
	return 0
}

func (m *ProductAttribute) GetInputList() string {
	if m != nil {
		return m.InputList
	}
	return ""
}

func (m *ProductAttribute) GetSort() int64 {
	if m != nil {
		return m.Sort
	}
	return 0
}

func (m *ProductAttribute) GetFilterType() int64 {
	if m != nil {
		return m.FilterType
	}
	return 0
}

func (m *ProductAttribute) GetSearchType() int64 {
	if m != nil {
		return m.SearchType
	}
	return 0
}

func (m *ProductAttribute) GetRelatedStatus() int64 {
	if m != nil {
		return m.RelatedStatus
	}
	return 0
}

func (m *ProductAttribute) GetHandAddStatus() int64 {
	if m != nil {
		return m.HandAddStatus
	}
	return 0
}

func (m *ProductAttribute) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetProductAttributeById struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductAttributeById) Reset()         { *m = In_GetProductAttributeById{} }
func (m *In_GetProductAttributeById) String() string { return proto.CompactTextString(m) }
func (*In_GetProductAttributeById) ProtoMessage()    {}
func (*In_GetProductAttributeById) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{2}
}

func (m *In_GetProductAttributeById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductAttributeById.Unmarshal(m, b)
}
func (m *In_GetProductAttributeById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductAttributeById.Marshal(b, m, deterministic)
}
func (m *In_GetProductAttributeById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductAttributeById.Merge(m, src)
}
func (m *In_GetProductAttributeById) XXX_Size() int {
	return xxx_messageInfo_In_GetProductAttributeById.Size(m)
}
func (m *In_GetProductAttributeById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductAttributeById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductAttributeById proto.InternalMessageInfo

func (m *In_GetProductAttributeById) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Out_GetProductAttributeById struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttribute     *ProductAttribute `protobuf:"bytes,2,opt,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Out_GetProductAttributeById) Reset()         { *m = Out_GetProductAttributeById{} }
func (m *Out_GetProductAttributeById) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductAttributeById) ProtoMessage()    {}
func (*Out_GetProductAttributeById) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{3}
}

func (m *Out_GetProductAttributeById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductAttributeById.Unmarshal(m, b)
}
func (m *Out_GetProductAttributeById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductAttributeById.Marshal(b, m, deterministic)
}
func (m *Out_GetProductAttributeById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductAttributeById.Merge(m, src)
}
func (m *Out_GetProductAttributeById) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductAttributeById.Size(m)
}
func (m *Out_GetProductAttributeById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductAttributeById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductAttributeById proto.InternalMessageInfo

func (m *Out_GetProductAttributeById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductAttributeById) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type Out_UpdateProductAttributeInfo struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttribute     *ProductAttribute `protobuf:"bytes,2,opt,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Out_UpdateProductAttributeInfo) Reset()         { *m = Out_UpdateProductAttributeInfo{} }
func (m *Out_UpdateProductAttributeInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateProductAttributeInfo) ProtoMessage()    {}
func (*Out_UpdateProductAttributeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{4}
}

func (m *Out_UpdateProductAttributeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateProductAttributeInfo.Unmarshal(m, b)
}
func (m *Out_UpdateProductAttributeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateProductAttributeInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateProductAttributeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateProductAttributeInfo.Merge(m, src)
}
func (m *Out_UpdateProductAttributeInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateProductAttributeInfo.Size(m)
}
func (m *Out_UpdateProductAttributeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateProductAttributeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateProductAttributeInfo proto.InternalMessageInfo

func (m *Out_UpdateProductAttributeInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateProductAttributeInfo) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type In_UpdateProductAttributeInfo struct {
	ProductAttribute     *ProductAttribute `protobuf:"bytes,1,opt,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *In_UpdateProductAttributeInfo) Reset()         { *m = In_UpdateProductAttributeInfo{} }
func (m *In_UpdateProductAttributeInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateProductAttributeInfo) ProtoMessage()    {}
func (*In_UpdateProductAttributeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{5}
}

func (m *In_UpdateProductAttributeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateProductAttributeInfo.Unmarshal(m, b)
}
func (m *In_UpdateProductAttributeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateProductAttributeInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateProductAttributeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateProductAttributeInfo.Merge(m, src)
}
func (m *In_UpdateProductAttributeInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateProductAttributeInfo.Size(m)
}
func (m *In_UpdateProductAttributeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateProductAttributeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateProductAttributeInfo proto.InternalMessageInfo

func (m *In_UpdateProductAttributeInfo) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type In_GetProductAttributeList struct {
	Cid                  int64    `protobuf:"varint,1,opt,name=cid,proto3" json:"cid,omitempty"`
	TypeValue            int64    `protobuf:"varint,2,opt,name=type_value,json=typeValue,proto3" json:"type_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductAttributeList) Reset()         { *m = In_GetProductAttributeList{} }
func (m *In_GetProductAttributeList) String() string { return proto.CompactTextString(m) }
func (*In_GetProductAttributeList) ProtoMessage()    {}
func (*In_GetProductAttributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{6}
}

func (m *In_GetProductAttributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductAttributeList.Unmarshal(m, b)
}
func (m *In_GetProductAttributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductAttributeList.Marshal(b, m, deterministic)
}
func (m *In_GetProductAttributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductAttributeList.Merge(m, src)
}
func (m *In_GetProductAttributeList) XXX_Size() int {
	return xxx_messageInfo_In_GetProductAttributeList.Size(m)
}
func (m *In_GetProductAttributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductAttributeList.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductAttributeList proto.InternalMessageInfo

func (m *In_GetProductAttributeList) GetCid() int64 {
	if m != nil {
		return m.Cid
	}
	return 0
}

func (m *In_GetProductAttributeList) GetTypeValue() int64 {
	if m != nil {
		return m.TypeValue
	}
	return 0
}

type In_GetProductAttributes struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductAttributes) Reset()         { *m = In_GetProductAttributes{} }
func (m *In_GetProductAttributes) String() string { return proto.CompactTextString(m) }
func (*In_GetProductAttributes) ProtoMessage()    {}
func (*In_GetProductAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{7}
}

func (m *In_GetProductAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductAttributes.Unmarshal(m, b)
}
func (m *In_GetProductAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductAttributes.Marshal(b, m, deterministic)
}
func (m *In_GetProductAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductAttributes.Merge(m, src)
}
func (m *In_GetProductAttributes) XXX_Size() int {
	return xxx_messageInfo_In_GetProductAttributes.Size(m)
}
func (m *In_GetProductAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductAttributes proto.InternalMessageInfo

func (m *In_GetProductAttributes) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetProductAttributes) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetProductAttributes) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetProductAttributes) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetProductAttributes) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetProductAttributes struct {
	Error                *Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64               `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64               `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64               `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductAttributeList []*ProductAttribute `protobuf:"bytes,5,rep,name=product_attribute_list,json=productAttributeList,proto3" json:"product_attribute_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Out_GetProductAttributes) Reset()         { *m = Out_GetProductAttributes{} }
func (m *Out_GetProductAttributes) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductAttributes) ProtoMessage()    {}
func (*Out_GetProductAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{8}
}

func (m *Out_GetProductAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductAttributes.Unmarshal(m, b)
}
func (m *Out_GetProductAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductAttributes.Marshal(b, m, deterministic)
}
func (m *Out_GetProductAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductAttributes.Merge(m, src)
}
func (m *Out_GetProductAttributes) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductAttributes.Size(m)
}
func (m *Out_GetProductAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductAttributes proto.InternalMessageInfo

func (m *Out_GetProductAttributes) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductAttributes) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetProductAttributes) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetProductAttributes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetProductAttributes) GetProductAttributeList() []*ProductAttribute {
	if m != nil {
		return m.ProductAttributeList
	}
	return nil
}

type Out_GetProductAttributeList struct {
	Error                *Error              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64               `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64               `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64               `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductAttributeList []*ProductAttribute `protobuf:"bytes,5,rep,name=product_attribute_list,json=productAttributeList,proto3" json:"product_attribute_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Out_GetProductAttributeList) Reset()         { *m = Out_GetProductAttributeList{} }
func (m *Out_GetProductAttributeList) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductAttributeList) ProtoMessage()    {}
func (*Out_GetProductAttributeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{9}
}

func (m *Out_GetProductAttributeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductAttributeList.Unmarshal(m, b)
}
func (m *Out_GetProductAttributeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductAttributeList.Marshal(b, m, deterministic)
}
func (m *Out_GetProductAttributeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductAttributeList.Merge(m, src)
}
func (m *Out_GetProductAttributeList) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductAttributeList.Size(m)
}
func (m *Out_GetProductAttributeList) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductAttributeList.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductAttributeList proto.InternalMessageInfo

func (m *Out_GetProductAttributeList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductAttributeList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetProductAttributeList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetProductAttributeList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetProductAttributeList) GetProductAttributeList() []*ProductAttribute {
	if m != nil {
		return m.ProductAttributeList
	}
	return nil
}

type In_DeleteProductAttributes struct {
	ProductAttributeList []int64  `protobuf:"varint,1,rep,packed,name=product_attribute_list,json=productAttributeList,proto3" json:"product_attribute_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_DeleteProductAttributes) Reset()         { *m = In_DeleteProductAttributes{} }
func (m *In_DeleteProductAttributes) String() string { return proto.CompactTextString(m) }
func (*In_DeleteProductAttributes) ProtoMessage()    {}
func (*In_DeleteProductAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{10}
}

func (m *In_DeleteProductAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteProductAttributes.Unmarshal(m, b)
}
func (m *In_DeleteProductAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteProductAttributes.Marshal(b, m, deterministic)
}
func (m *In_DeleteProductAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteProductAttributes.Merge(m, src)
}
func (m *In_DeleteProductAttributes) XXX_Size() int {
	return xxx_messageInfo_In_DeleteProductAttributes.Size(m)
}
func (m *In_DeleteProductAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteProductAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteProductAttributes proto.InternalMessageInfo

func (m *In_DeleteProductAttributes) GetProductAttributeList() []int64 {
	if m != nil {
		return m.ProductAttributeList
	}
	return nil
}

type Out_DeleteProductAttributes struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteProductAttributes) Reset()         { *m = Out_DeleteProductAttributes{} }
func (m *Out_DeleteProductAttributes) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteProductAttributes) ProtoMessage()    {}
func (*Out_DeleteProductAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{11}
}

func (m *Out_DeleteProductAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteProductAttributes.Unmarshal(m, b)
}
func (m *Out_DeleteProductAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteProductAttributes.Marshal(b, m, deterministic)
}
func (m *Out_DeleteProductAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteProductAttributes.Merge(m, src)
}
func (m *Out_DeleteProductAttributes) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteProductAttributes.Size(m)
}
func (m *Out_DeleteProductAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteProductAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteProductAttributes proto.InternalMessageInfo

func (m *Out_DeleteProductAttributes) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateProductAttribute struct {
	ProductAttribute     *ProductAttribute `protobuf:"bytes,1,opt,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *In_CreateProductAttribute) Reset()         { *m = In_CreateProductAttribute{} }
func (m *In_CreateProductAttribute) String() string { return proto.CompactTextString(m) }
func (*In_CreateProductAttribute) ProtoMessage()    {}
func (*In_CreateProductAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{12}
}

func (m *In_CreateProductAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateProductAttribute.Unmarshal(m, b)
}
func (m *In_CreateProductAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateProductAttribute.Marshal(b, m, deterministic)
}
func (m *In_CreateProductAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateProductAttribute.Merge(m, src)
}
func (m *In_CreateProductAttribute) XXX_Size() int {
	return xxx_messageInfo_In_CreateProductAttribute.Size(m)
}
func (m *In_CreateProductAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateProductAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateProductAttribute proto.InternalMessageInfo

func (m *In_CreateProductAttribute) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

type Out_CreateProductAttribute struct {
	Error                *Error            `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductAttribute     *ProductAttribute `protobuf:"bytes,2,opt,name=product_attribute,json=productAttribute,proto3" json:"product_attribute,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Out_CreateProductAttribute) Reset()         { *m = Out_CreateProductAttribute{} }
func (m *Out_CreateProductAttribute) String() string { return proto.CompactTextString(m) }
func (*Out_CreateProductAttribute) ProtoMessage()    {}
func (*Out_CreateProductAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_6749a7202100aba5, []int{13}
}

func (m *Out_CreateProductAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateProductAttribute.Unmarshal(m, b)
}
func (m *Out_CreateProductAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateProductAttribute.Marshal(b, m, deterministic)
}
func (m *Out_CreateProductAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateProductAttribute.Merge(m, src)
}
func (m *Out_CreateProductAttribute) XXX_Size() int {
	return xxx_messageInfo_Out_CreateProductAttribute.Size(m)
}
func (m *Out_CreateProductAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateProductAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateProductAttribute proto.InternalMessageInfo

func (m *Out_CreateProductAttribute) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateProductAttribute) GetProductAttribute() *ProductAttribute {
	if m != nil {
		return m.ProductAttribute
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductAttribute)(nil), "product_attribute.Product_attribute")
	proto.RegisterType((*Error)(nil), "product_attribute.Error")
	proto.RegisterType((*In_GetProductAttributeById)(nil), "product_attribute.In_GetProductAttributeById")
	proto.RegisterType((*Out_GetProductAttributeById)(nil), "product_attribute.Out_GetProductAttributeById")
	proto.RegisterType((*Out_UpdateProductAttributeInfo)(nil), "product_attribute.Out_UpdateProductAttributeInfo")
	proto.RegisterType((*In_UpdateProductAttributeInfo)(nil), "product_attribute.In_UpdateProductAttributeInfo")
	proto.RegisterType((*In_GetProductAttributeList)(nil), "product_attribute.In_GetProductAttributeList")
	proto.RegisterType((*In_GetProductAttributes)(nil), "product_attribute.In_GetProductAttributes")
	proto.RegisterType((*Out_GetProductAttributes)(nil), "product_attribute.Out_GetProductAttributes")
	proto.RegisterType((*Out_GetProductAttributeList)(nil), "product_attribute.Out_GetProductAttributeList")
	proto.RegisterType((*In_DeleteProductAttributes)(nil), "product_attribute.In_DeleteProductAttributes")
	proto.RegisterType((*Out_DeleteProductAttributes)(nil), "product_attribute.Out_DeleteProductAttributes")
	proto.RegisterType((*In_CreateProductAttribute)(nil), "product_attribute.In_CreateProductAttribute")
	proto.RegisterType((*Out_CreateProductAttribute)(nil), "product_attribute.Out_CreateProductAttribute")
}

func init() { proto.RegisterFile("product_attribute.proto", fileDescriptor_6749a7202100aba5) }

var fileDescriptor_6749a7202100aba5 = []byte{
	// 745 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xd1, 0x6e, 0xd3, 0x4a,
	0x10, 0x8d, 0xe3, 0xba, 0x6d, 0x26, 0xf7, 0xf6, 0xb6, 0xab, 0xa8, 0x71, 0x7d, 0xd5, 0x7b, 0x23,
	0x0b, 0x50, 0x05, 0x6d, 0x04, 0x05, 0x3e, 0xa0, 0x14, 0x04, 0x11, 0x54, 0x94, 0x50, 0x78, 0xe0,
	0xc5, 0xda, 0x66, 0xb7, 0xad, 0x85, 0x63, 0x9b, 0xdd, 0x0d, 0x28, 0xbc, 0xf2, 0x07, 0x7c, 0x00,
	0x20, 0xf1, 0x73, 0x48, 0x7c, 0x04, 0x68, 0x67, 0x9d, 0x0a, 0x62, 0x6f, 0x95, 0x0a, 0x21, 0x10,
	0x6f, 0xbb, 0x33, 0x67, 0x67, 0xce, 0xee, 0x9c, 0x19, 0x1b, 0xda, 0xb9, 0xc8, 0xd8, 0x68, 0xa0,
	0x22, 0xaa, 0x94, 0x88, 0x0f, 0x47, 0x8a, 0x77, 0x73, 0x91, 0xa9, 0x8c, 0xac, 0x94, 0x1c, 0xe1,
	0x5b, 0x17, 0x56, 0xf6, 0xa7, 0xad, 0x64, 0x09, 0xea, 0x31, 0xf3, 0x9d, 0x8e, 0xb3, 0xe1, 0xf6,
	0xeb, 0x31, 0x23, 0x3b, 0xb0, 0x5e, 0x3a, 0x1a, 0x0d, 0xa8, 0xe2, 0xc7, 0x99, 0x18, 0x47, 0x31,
	0xf3, 0xeb, 0x08, 0x0d, 0x0a, 0xd0, 0xce, 0x04, 0xb3, 0x5b, 0x40, 0x7a, 0x8c, 0x10, 0x98, 0x4b,
	0xe9, 0x90, 0xfb, 0x6e, 0xc7, 0xd9, 0x68, 0xf4, 0x71, 0x4d, 0xfe, 0x87, 0xa6, 0xe4, 0x09, 0x1f,
	0xa8, 0x48, 0x8d, 0x73, 0xee, 0xcf, 0x61, 0x10, 0x30, 0xa6, 0x83, 0x71, 0xce, 0xc9, 0x3a, 0x40,
	0x9c, 0xe6, 0xa3, 0xc2, 0xef, 0xa1, 0xbf, 0x81, 0x96, 0xef, 0xdd, 0x49, 0x2c, 0x95, 0x3f, 0x8f,
	0x91, 0x8d, 0xfb, 0x41, 0x2c, 0x95, 0x4e, 0x29, 0x33, 0xa1, 0xfc, 0x05, 0x3c, 0x87, 0x6b, 0x9d,
	0xf2, 0x28, 0x4e, 0x14, 0x17, 0x26, 0xe4, 0xa2, 0x49, 0x69, 0x4c, 0x18, 0x13, 0x39, 0x51, 0x31,
	0x38, 0x31, 0x80, 0xc6, 0x84, 0x93, 0x36, 0x21, 0xe0, 0x22, 0x2c, 0x09, 0x9e, 0x50, 0xc5, 0x59,
	0x24, 0x15, 0x55, 0x23, 0xe9, 0x03, 0x62, 0xfe, 0x2e, 0xac, 0x8f, 0xd1, 0x48, 0x2e, 0xc1, 0x3f,
	0x27, 0x34, 0x65, 0x11, 0x65, 0xa7, 0xb8, 0xa6, 0xc1, 0x69, 0xf3, 0x0e, 0x9b, 0xe0, 0x08, 0xcc,
	0x61, 0xa2, 0xbf, 0x0c, 0x49, 0xbd, 0x0e, 0x6f, 0x82, 0x77, 0x47, 0x88, 0x4c, 0x68, 0xe7, 0x20,
	0x63, 0x1c, 0x2b, 0xe1, 0xf5, 0x71, 0x4d, 0x7c, 0x58, 0x18, 0x72, 0x29, 0xe9, 0x31, 0xc7, 0x57,
	0x6f, 0xf4, 0x27, 0xdb, 0x70, 0x13, 0x82, 0x5e, 0x1a, 0xdd, 0xe5, 0x6a, 0x7f, 0xaa, 0x0c, 0xb7,
	0x74, 0x01, 0xa6, 0x6a, 0x1a, 0x7e, 0x70, 0xe0, 0xdf, 0x87, 0x23, 0x65, 0xc5, 0x77, 0xc1, 0xe3,
	0x9a, 0x04, 0x1e, 0x69, 0x6e, 0xfb, 0xdd, 0xb2, 0xaa, 0x90, 0x64, 0xdf, 0xc0, 0xc8, 0x23, 0x28,
	0xcb, 0x0b, 0x19, 0x36, 0xb7, 0x2f, 0x54, 0x9c, 0x2d, 0x89, 0xae, 0xbf, 0x3c, 0xad, 0x9e, 0xf0,
	0xa3, 0x03, 0xff, 0x69, 0x8a, 0x4f, 0x72, 0x46, 0x15, 0x9f, 0x66, 0xd9, 0x4b, 0x8f, 0xb2, 0xdf,
	0x81, 0xa5, 0x80, 0xf5, 0x5e, 0x7a, 0x16, 0xc7, 0xca, 0x9c, 0xce, 0x0f, 0xe5, 0xdc, 0xb3, 0x95,
	0x1a, 0x85, 0xbf, 0x0c, 0xee, 0xe0, 0xb4, 0xd6, 0x7a, 0xa9, 0x3b, 0x45, 0x2b, 0x2b, 0x7a, 0x49,
	0x93, 0x11, 0x2f, 0xba, 0xb5, 0xa1, 0x2d, 0x4f, 0xb5, 0x21, 0x7c, 0xe7, 0x40, 0xbb, 0x3a, 0x9e,
	0x24, 0x2d, 0xf0, 0x92, 0x78, 0x18, 0xab, 0x22, 0x9c, 0xd9, 0x68, 0x6b, 0x4e, 0x8f, 0xb9, 0x2c,
	0x62, 0x99, 0x8d, 0x4e, 0x53, 0x34, 0xcf, 0x73, 0x3e, 0x2e, 0x5a, 0xbd, 0x61, 0x2c, 0xf7, 0xf9,
	0x18, 0xdd, 0x8a, 0x0a, 0x15, 0xa9, 0x78, 0x68, 0xda, 0x5d, 0xbb, 0xb5, 0xe5, 0x20, 0x1e, 0x72,
	0xb2, 0x06, 0x8b, 0x3c, 0x65, 0xc6, 0xe9, 0x19, 0x69, 0xf3, 0x94, 0x69, 0x57, 0xf8, 0xc9, 0x01,
	0xdf, 0x22, 0x56, 0x79, 0x6e, 0x0d, 0x9c, 0xde, 0xa8, 0x5e, 0x79, 0x23, 0xf7, 0xdb, 0x1b, 0xb5,
	0xc0, 0x53, 0x99, 0xa2, 0x49, 0x31, 0x9c, 0xcc, 0x86, 0x3c, 0x83, 0xd5, 0xf2, 0x3c, 0xc4, 0x21,
	0xe4, 0x75, 0xdc, 0x99, 0xcb, 0xda, 0xca, 0x2b, 0x8a, 0x17, 0x7e, 0xb6, 0xf7, 0x25, 0x16, 0xf7,
	0xcf, 0xba, 0x6d, 0x1f, 0x85, 0x7c, 0x9b, 0x27, 0xbc, 0xdc, 0x3c, 0x92, 0xdc, 0xb0, 0x66, 0x76,
	0x3a, 0xee, 0x86, 0x6b, 0x89, 0xb9, 0x67, 0x1e, 0xd0, 0x16, 0xf4, 0x9c, 0x0f, 0x18, 0xa6, 0xb0,
	0xd6, 0x4b, 0xa3, 0x5d, 0xc1, 0x2b, 0xfa, 0xfb, 0x67, 0xf4, 0xf6, 0x7b, 0x07, 0x02, 0xcd, 0xdf,
	0x92, 0xf1, 0xd7, 0x4f, 0xbc, 0xed, 0x2f, 0x1e, 0xb4, 0xa7, 0x79, 0xdd, 0xa3, 0x29, 0x4b, 0xb8,
	0x20, 0xaf, 0xa1, 0x6d, 0xfb, 0xa2, 0x6c, 0x55, 0xa4, 0xb3, 0x7f, 0xb0, 0x82, 0x6e, 0x05, 0xfc,
	0x8c, 0x0f, 0x56, 0x58, 0x23, 0x6f, 0x1c, 0x08, 0xce, 0x98, 0xc3, 0x57, 0xab, 0xf3, 0xdb, 0x4f,
	0x04, 0xd7, 0x2c, 0x14, 0xec, 0x47, 0xc2, 0x1a, 0x79, 0x01, 0xad, 0xca, 0x31, 0x75, 0x79, 0xe6,
	0xeb, 0xcb, 0xe0, 0xca, 0xec, 0x77, 0x97, 0x61, 0x4d, 0x3f, 0xba, 0x4d, 0xed, 0x96, 0x47, 0xb7,
	0xc0, 0xad, 0x8f, 0x6e, 0xc1, 0x87, 0x35, 0xf2, 0x0a, 0x56, 0x2d, 0x4a, 0xdd, 0xac, 0x4e, 0x5d,
	0x8d, 0x0e, 0xb6, 0x2c, 0x99, 0xab, 0xe1, 0xe6, 0xd2, 0xb6, 0x19, 0x39, 0xbb, 0xd2, 0x34, 0xfc,
	0x3c, 0x4a, 0xc3, 0x01, 0x53, 0x3b, 0x9c, 0xc7, 0x1f, 0xea, 0xeb, 0x5f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x12, 0x60, 0xfa, 0xb7, 0x6b, 0x0b, 0x00, 0x00,
}
