// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product_vertify_record.proto

package product_vertify_record

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//商品审核记录
type ProductVertifyRecord struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId            string   `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CreateTime           string   `protobuf:"bytes,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	VertifyMan           string   `protobuf:"bytes,4,opt,name=vertify_man,json=vertifyMan,proto3" json:"vertify_man,omitempty"`
	Status               int64    `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	Detail               string   `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductVertifyRecord) Reset()         { *m = ProductVertifyRecord{} }
func (m *ProductVertifyRecord) String() string { return proto.CompactTextString(m) }
func (*ProductVertifyRecord) ProtoMessage()    {}
func (*ProductVertifyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{0}
}

func (m *ProductVertifyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductVertifyRecord.Unmarshal(m, b)
}
func (m *ProductVertifyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductVertifyRecord.Marshal(b, m, deterministic)
}
func (m *ProductVertifyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductVertifyRecord.Merge(m, src)
}
func (m *ProductVertifyRecord) XXX_Size() int {
	return xxx_messageInfo_ProductVertifyRecord.Size(m)
}
func (m *ProductVertifyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductVertifyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_ProductVertifyRecord proto.InternalMessageInfo

func (m *ProductVertifyRecord) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductVertifyRecord) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *ProductVertifyRecord) GetCreateTime() string {
	if m != nil {
		return m.CreateTime
	}
	return ""
}

func (m *ProductVertifyRecord) GetVertifyMan() string {
	if m != nil {
		return m.VertifyMan
	}
	return ""
}

func (m *ProductVertifyRecord) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ProductVertifyRecord) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetProductVertifyRecordById struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductVertifyRecordById) Reset()         { *m = In_GetProductVertifyRecordById{} }
func (m *In_GetProductVertifyRecordById) String() string { return proto.CompactTextString(m) }
func (*In_GetProductVertifyRecordById) ProtoMessage()    {}
func (*In_GetProductVertifyRecordById) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{2}
}

func (m *In_GetProductVertifyRecordById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductVertifyRecordById.Unmarshal(m, b)
}
func (m *In_GetProductVertifyRecordById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductVertifyRecordById.Marshal(b, m, deterministic)
}
func (m *In_GetProductVertifyRecordById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductVertifyRecordById.Merge(m, src)
}
func (m *In_GetProductVertifyRecordById) XXX_Size() int {
	return xxx_messageInfo_In_GetProductVertifyRecordById.Size(m)
}
func (m *In_GetProductVertifyRecordById) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductVertifyRecordById.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductVertifyRecordById proto.InternalMessageInfo

func (m *In_GetProductVertifyRecordById) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Out_GetProductVertifyRecordById struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductVertifyRecord *ProductVertifyRecord `protobuf:"bytes,2,opt,name=product_vertify_record,json=productVertifyRecord,proto3" json:"product_vertify_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_GetProductVertifyRecordById) Reset()         { *m = Out_GetProductVertifyRecordById{} }
func (m *Out_GetProductVertifyRecordById) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductVertifyRecordById) ProtoMessage()    {}
func (*Out_GetProductVertifyRecordById) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{3}
}

func (m *Out_GetProductVertifyRecordById) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductVertifyRecordById.Unmarshal(m, b)
}
func (m *Out_GetProductVertifyRecordById) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductVertifyRecordById.Marshal(b, m, deterministic)
}
func (m *Out_GetProductVertifyRecordById) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductVertifyRecordById.Merge(m, src)
}
func (m *Out_GetProductVertifyRecordById) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductVertifyRecordById.Size(m)
}
func (m *Out_GetProductVertifyRecordById) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductVertifyRecordById.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductVertifyRecordById proto.InternalMessageInfo

func (m *Out_GetProductVertifyRecordById) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductVertifyRecordById) GetProductVertifyRecord() *ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecord
	}
	return nil
}

type Out_UpdateProductVertifyRecordInfo struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductVertifyRecord *ProductVertifyRecord `protobuf:"bytes,2,opt,name=product_vertify_record,json=productVertifyRecord,proto3" json:"product_vertify_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_UpdateProductVertifyRecordInfo) Reset()         { *m = Out_UpdateProductVertifyRecordInfo{} }
func (m *Out_UpdateProductVertifyRecordInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateProductVertifyRecordInfo) ProtoMessage()    {}
func (*Out_UpdateProductVertifyRecordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{4}
}

func (m *Out_UpdateProductVertifyRecordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateProductVertifyRecordInfo.Unmarshal(m, b)
}
func (m *Out_UpdateProductVertifyRecordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateProductVertifyRecordInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateProductVertifyRecordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateProductVertifyRecordInfo.Merge(m, src)
}
func (m *Out_UpdateProductVertifyRecordInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateProductVertifyRecordInfo.Size(m)
}
func (m *Out_UpdateProductVertifyRecordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateProductVertifyRecordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateProductVertifyRecordInfo proto.InternalMessageInfo

func (m *Out_UpdateProductVertifyRecordInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateProductVertifyRecordInfo) GetProductVertifyRecord() *ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecord
	}
	return nil
}

type In_UpdateProductVertifyRecordInfo struct {
	ProductVertifyRecord *ProductVertifyRecord `protobuf:"bytes,1,opt,name=product_vertify_record,json=productVertifyRecord,proto3" json:"product_vertify_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *In_UpdateProductVertifyRecordInfo) Reset()         { *m = In_UpdateProductVertifyRecordInfo{} }
func (m *In_UpdateProductVertifyRecordInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateProductVertifyRecordInfo) ProtoMessage()    {}
func (*In_UpdateProductVertifyRecordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{5}
}

func (m *In_UpdateProductVertifyRecordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateProductVertifyRecordInfo.Unmarshal(m, b)
}
func (m *In_UpdateProductVertifyRecordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateProductVertifyRecordInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateProductVertifyRecordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateProductVertifyRecordInfo.Merge(m, src)
}
func (m *In_UpdateProductVertifyRecordInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateProductVertifyRecordInfo.Size(m)
}
func (m *In_UpdateProductVertifyRecordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateProductVertifyRecordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateProductVertifyRecordInfo proto.InternalMessageInfo

func (m *In_UpdateProductVertifyRecordInfo) GetProductVertifyRecord() *ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecord
	}
	return nil
}

type In_GetProductVertifyRecords struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetProductVertifyRecords) Reset()         { *m = In_GetProductVertifyRecords{} }
func (m *In_GetProductVertifyRecords) String() string { return proto.CompactTextString(m) }
func (*In_GetProductVertifyRecords) ProtoMessage()    {}
func (*In_GetProductVertifyRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{6}
}

func (m *In_GetProductVertifyRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetProductVertifyRecords.Unmarshal(m, b)
}
func (m *In_GetProductVertifyRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetProductVertifyRecords.Marshal(b, m, deterministic)
}
func (m *In_GetProductVertifyRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetProductVertifyRecords.Merge(m, src)
}
func (m *In_GetProductVertifyRecords) XXX_Size() int {
	return xxx_messageInfo_In_GetProductVertifyRecords.Size(m)
}
func (m *In_GetProductVertifyRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetProductVertifyRecords.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetProductVertifyRecords proto.InternalMessageInfo

func (m *In_GetProductVertifyRecords) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetProductVertifyRecords) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetProductVertifyRecords) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetProductVertifyRecords) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetProductVertifyRecords) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetProductVertifyRecords struct {
	Error                    *Error                  `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                    int64                   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                    int64                   `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                    int64                   `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	ProductVertifyRecordList []*ProductVertifyRecord `protobuf:"bytes,5,rep,name=product_vertify_record_list,json=productVertifyRecordList,proto3" json:"product_vertify_record_list,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                `json:"-"`
	XXX_unrecognized         []byte                  `json:"-"`
	XXX_sizecache            int32                   `json:"-"`
}

func (m *Out_GetProductVertifyRecords) Reset()         { *m = Out_GetProductVertifyRecords{} }
func (m *Out_GetProductVertifyRecords) String() string { return proto.CompactTextString(m) }
func (*Out_GetProductVertifyRecords) ProtoMessage()    {}
func (*Out_GetProductVertifyRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{7}
}

func (m *Out_GetProductVertifyRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetProductVertifyRecords.Unmarshal(m, b)
}
func (m *Out_GetProductVertifyRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetProductVertifyRecords.Marshal(b, m, deterministic)
}
func (m *Out_GetProductVertifyRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetProductVertifyRecords.Merge(m, src)
}
func (m *Out_GetProductVertifyRecords) XXX_Size() int {
	return xxx_messageInfo_Out_GetProductVertifyRecords.Size(m)
}
func (m *Out_GetProductVertifyRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetProductVertifyRecords.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetProductVertifyRecords proto.InternalMessageInfo

func (m *Out_GetProductVertifyRecords) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetProductVertifyRecords) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetProductVertifyRecords) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetProductVertifyRecords) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetProductVertifyRecords) GetProductVertifyRecordList() []*ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecordList
	}
	return nil
}

type In_DeleteProductVertifyRecords struct {
	ProductVertifyRecordList []int64  `protobuf:"varint,1,rep,packed,name=product_vertify_record_list,json=productVertifyRecordList,proto3" json:"product_vertify_record_list,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *In_DeleteProductVertifyRecords) Reset()         { *m = In_DeleteProductVertifyRecords{} }
func (m *In_DeleteProductVertifyRecords) String() string { return proto.CompactTextString(m) }
func (*In_DeleteProductVertifyRecords) ProtoMessage()    {}
func (*In_DeleteProductVertifyRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{8}
}

func (m *In_DeleteProductVertifyRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_DeleteProductVertifyRecords.Unmarshal(m, b)
}
func (m *In_DeleteProductVertifyRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_DeleteProductVertifyRecords.Marshal(b, m, deterministic)
}
func (m *In_DeleteProductVertifyRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_DeleteProductVertifyRecords.Merge(m, src)
}
func (m *In_DeleteProductVertifyRecords) XXX_Size() int {
	return xxx_messageInfo_In_DeleteProductVertifyRecords.Size(m)
}
func (m *In_DeleteProductVertifyRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_In_DeleteProductVertifyRecords.DiscardUnknown(m)
}

var xxx_messageInfo_In_DeleteProductVertifyRecords proto.InternalMessageInfo

func (m *In_DeleteProductVertifyRecords) GetProductVertifyRecordList() []int64 {
	if m != nil {
		return m.ProductVertifyRecordList
	}
	return nil
}

type Out_DeleteProductVertifyRecords struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_DeleteProductVertifyRecords) Reset()         { *m = Out_DeleteProductVertifyRecords{} }
func (m *Out_DeleteProductVertifyRecords) String() string { return proto.CompactTextString(m) }
func (*Out_DeleteProductVertifyRecords) ProtoMessage()    {}
func (*Out_DeleteProductVertifyRecords) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{9}
}

func (m *Out_DeleteProductVertifyRecords) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_DeleteProductVertifyRecords.Unmarshal(m, b)
}
func (m *Out_DeleteProductVertifyRecords) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_DeleteProductVertifyRecords.Marshal(b, m, deterministic)
}
func (m *Out_DeleteProductVertifyRecords) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_DeleteProductVertifyRecords.Merge(m, src)
}
func (m *Out_DeleteProductVertifyRecords) XXX_Size() int {
	return xxx_messageInfo_Out_DeleteProductVertifyRecords.Size(m)
}
func (m *Out_DeleteProductVertifyRecords) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_DeleteProductVertifyRecords.DiscardUnknown(m)
}

var xxx_messageInfo_Out_DeleteProductVertifyRecords proto.InternalMessageInfo

func (m *Out_DeleteProductVertifyRecords) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_CreateProductVertifyRecord struct {
	ProductVertifyRecord *ProductVertifyRecord `protobuf:"bytes,1,opt,name=product_vertify_record,json=productVertifyRecord,proto3" json:"product_vertify_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *In_CreateProductVertifyRecord) Reset()         { *m = In_CreateProductVertifyRecord{} }
func (m *In_CreateProductVertifyRecord) String() string { return proto.CompactTextString(m) }
func (*In_CreateProductVertifyRecord) ProtoMessage()    {}
func (*In_CreateProductVertifyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{10}
}

func (m *In_CreateProductVertifyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_CreateProductVertifyRecord.Unmarshal(m, b)
}
func (m *In_CreateProductVertifyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_CreateProductVertifyRecord.Marshal(b, m, deterministic)
}
func (m *In_CreateProductVertifyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_CreateProductVertifyRecord.Merge(m, src)
}
func (m *In_CreateProductVertifyRecord) XXX_Size() int {
	return xxx_messageInfo_In_CreateProductVertifyRecord.Size(m)
}
func (m *In_CreateProductVertifyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_In_CreateProductVertifyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_In_CreateProductVertifyRecord proto.InternalMessageInfo

func (m *In_CreateProductVertifyRecord) GetProductVertifyRecord() *ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecord
	}
	return nil
}

type Out_CreateProductVertifyRecord struct {
	Error                *Error                `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ProductVertifyRecord *ProductVertifyRecord `protobuf:"bytes,2,opt,name=product_vertify_record,json=productVertifyRecord,proto3" json:"product_vertify_record,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Out_CreateProductVertifyRecord) Reset()         { *m = Out_CreateProductVertifyRecord{} }
func (m *Out_CreateProductVertifyRecord) String() string { return proto.CompactTextString(m) }
func (*Out_CreateProductVertifyRecord) ProtoMessage()    {}
func (*Out_CreateProductVertifyRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_7d9bfcd8b41666be, []int{11}
}

func (m *Out_CreateProductVertifyRecord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_CreateProductVertifyRecord.Unmarshal(m, b)
}
func (m *Out_CreateProductVertifyRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_CreateProductVertifyRecord.Marshal(b, m, deterministic)
}
func (m *Out_CreateProductVertifyRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_CreateProductVertifyRecord.Merge(m, src)
}
func (m *Out_CreateProductVertifyRecord) XXX_Size() int {
	return xxx_messageInfo_Out_CreateProductVertifyRecord.Size(m)
}
func (m *Out_CreateProductVertifyRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_CreateProductVertifyRecord.DiscardUnknown(m)
}

var xxx_messageInfo_Out_CreateProductVertifyRecord proto.InternalMessageInfo

func (m *Out_CreateProductVertifyRecord) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_CreateProductVertifyRecord) GetProductVertifyRecord() *ProductVertifyRecord {
	if m != nil {
		return m.ProductVertifyRecord
	}
	return nil
}

func init() {
	proto.RegisterType((*ProductVertifyRecord)(nil), "Product_vertify_record")
	proto.RegisterType((*Error)(nil), "Error")
	proto.RegisterType((*In_GetProductVertifyRecordById)(nil), "In_GetProductVertifyRecordById")
	proto.RegisterType((*Out_GetProductVertifyRecordById)(nil), "Out_GetProductVertifyRecordById")
	proto.RegisterType((*Out_UpdateProductVertifyRecordInfo)(nil), "Out_UpdateProductVertifyRecordInfo")
	proto.RegisterType((*In_UpdateProductVertifyRecordInfo)(nil), "In_UpdateProductVertifyRecordInfo")
	proto.RegisterType((*In_GetProductVertifyRecords)(nil), "In_GetProductVertifyRecords")
	proto.RegisterType((*Out_GetProductVertifyRecords)(nil), "Out_GetProductVertifyRecords")
	proto.RegisterType((*In_DeleteProductVertifyRecords)(nil), "In_DeleteProductVertifyRecords")
	proto.RegisterType((*Out_DeleteProductVertifyRecords)(nil), "Out_DeleteProductVertifyRecords")
	proto.RegisterType((*In_CreateProductVertifyRecord)(nil), "In_CreateProductVertifyRecord")
	proto.RegisterType((*Out_CreateProductVertifyRecord)(nil), "Out_CreateProductVertifyRecord")
}

func init() { proto.RegisterFile("product_vertify_record.proto", fileDescriptor_7d9bfcd8b41666be) }

var fileDescriptor_7d9bfcd8b41666be = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0x6e, 0x9a, 0xa6, 0xba, 0x67, 0xc1, 0x8b, 0x61, 0xa9, 0xb1, 0xff, 0x8e, 0x37, 0xbd, 0x0a,
	0x52, 0xf1, 0x52, 0x04, 0x7f, 0xd0, 0xa0, 0x8b, 0x12, 0x74, 0xc1, 0xab, 0x30, 0xdb, 0x39, 0xbb,
	0x0e, 0x9b, 0x26, 0x65, 0x66, 0x2a, 0xf4, 0x21, 0x5c, 0xf0, 0x15, 0x7c, 0x0b, 0x5f, 0xc4, 0xe7,
	0x91, 0xcc, 0xa4, 0x22, 0x38, 0x9d, 0x80, 0xc8, 0xde, 0xf5, 0x9c, 0x39, 0xd3, 0xef, 0xfb, 0xce,
	0xf9, 0xe6, 0x04, 0xc6, 0x1b, 0x59, 0xf1, 0xed, 0x4a, 0xe7, 0x5f, 0x50, 0x6a, 0x71, 0xb1, 0xcb,
	0x25, 0xae, 0x2a, 0xc9, 0x93, 0x8d, 0xac, 0x74, 0x45, 0x7f, 0x04, 0x30, 0x78, 0xef, 0x2c, 0x20,
	0x77, 0xa0, 0x2b, 0x78, 0x1c, 0xcc, 0x83, 0x45, 0x98, 0x75, 0x05, 0x27, 0x13, 0x80, 0xfd, 0x5f,
	0x09, 0x1e, 0x77, 0xe7, 0xc1, 0xe2, 0x28, 0x3b, 0x6a, 0x32, 0x29, 0x27, 0x33, 0x38, 0x5e, 0x49,
	0x64, 0x1a, 0x73, 0x2d, 0xd6, 0x18, 0x87, 0xe6, 0x1c, 0x6c, 0xea, 0x83, 0x58, 0x63, 0x5d, 0xb0,
	0x47, 0x58, 0xb3, 0x32, 0xee, 0xd9, 0x82, 0x26, 0x75, 0xca, 0x4a, 0x32, 0x80, 0xbe, 0xd2, 0x4c,
	0x6f, 0x55, 0x1c, 0x19, 0xd0, 0x26, 0xaa, 0xf3, 0x1c, 0x35, 0x13, 0x45, 0xdc, 0x37, 0x77, 0x9a,
	0x88, 0x3e, 0x86, 0xe8, 0xa5, 0x94, 0x95, 0x24, 0x04, 0x7a, 0xab, 0x8a, 0xa3, 0xe1, 0x1a, 0x65,
	0xe6, 0x37, 0x89, 0xe1, 0xd6, 0x1a, 0x95, 0x62, 0x97, 0xd8, 0x50, 0xdd, 0x87, 0xf4, 0x21, 0x4c,
	0xd3, 0x32, 0x7f, 0x85, 0xba, 0xd1, 0x7d, 0x66, 0x19, 0x64, 0x46, 0xf5, 0xb3, 0x5d, 0xfa, 0x97,
	0x72, 0x7a, 0x1d, 0xc0, 0xec, 0xdd, 0x56, 0x7b, 0xef, 0x8c, 0x21, 0xc2, 0x9a, 0x8c, 0xb9, 0x76,
	0xbc, 0xec, 0x27, 0x86, 0x5a, 0x66, 0x93, 0xe4, 0x14, 0x06, 0xee, 0x31, 0x18, 0x72, 0xc7, 0xcb,
	0xbb, 0x89, 0x7b, 0x08, 0xd9, 0xc9, 0xc6, 0x01, 0x48, 0xbf, 0x05, 0x40, 0x6b, 0x42, 0x1f, 0x37,
	0x9c, 0x69, 0x74, 0x71, 0x4a, 0xcb, 0x8b, 0xea, 0x66, 0x39, 0x49, 0xb8, 0x9f, 0x96, 0x6d, 0x8c,
	0x0e, 0x63, 0x06, 0xff, 0x82, 0xf9, 0x3d, 0x80, 0xd1, 0xe1, 0x59, 0x2a, 0x72, 0x02, 0x51, 0x21,
	0xd6, 0x42, 0x37, 0xb3, 0xb4, 0x41, 0x9d, 0xdd, 0xb0, 0x4b, 0x54, 0x46, 0x67, 0x98, 0xd9, 0xa0,
	0xb6, 0xb7, 0x42, 0x26, 0x57, 0x9f, 0xf3, 0x2b, 0xdc, 0x35, 0xf6, 0x3d, 0xb2, 0x99, 0x37, 0xb8,
	0x33, 0xc7, 0x9a, 0x49, 0x6d, 0xdd, 0xdd, 0x6b, 0x8e, 0xeb, 0x8c, 0x31, 0xf7, 0x3d, 0xb8, 0x8d,
	0x25, 0xb7, 0x87, 0x91, 0xf5, 0x1b, 0x96, 0xbc, 0x3e, 0xa2, 0x3f, 0x03, 0x18, 0x7b, 0xdc, 0xa3,
	0x5a, 0xc6, 0xf4, 0x5b, 0x43, 0xd7, 0xa9, 0x21, 0xfc, 0x53, 0xc3, 0x09, 0x44, 0xba, 0xd2, 0xac,
	0x30, 0xfc, 0xc2, 0xcc, 0x06, 0xe4, 0x0c, 0x46, 0xee, 0xa6, 0xe7, 0x85, 0x50, 0x3a, 0x8e, 0xe6,
	0xa1, 0xaf, 0xf3, 0xb1, 0xab, 0xf3, 0x6f, 0x85, 0xd2, 0x34, 0x37, 0x0f, 0xe9, 0x05, 0x16, 0xe8,
	0x9e, 0xb8, 0x22, 0x4f, 0xfc, 0xc8, 0xc1, 0x3c, 0x5c, 0x84, 0x1e, 0x80, 0xa7, 0xf6, 0xd9, 0xf9,
	0x10, 0xbc, 0xbd, 0xa3, 0x25, 0x4c, 0xd2, 0x32, 0x7f, 0x6e, 0x76, 0x90, 0xeb, 0xfe, 0xff, 0xf6,
	0xe3, 0xd7, 0x00, 0xa6, 0x35, 0x63, 0x0f, 0xe2, 0x4d, 0xbe, 0xc9, 0xe5, 0x75, 0x0f, 0x46, 0x2e,
	0x16, 0xaf, 0x59, 0xc9, 0x0b, 0x94, 0xe4, 0x1c, 0x46, 0xbe, 0x9d, 0x36, 0x4b, 0xfc, 0x8b, 0x72,
	0x38, 0x4f, 0x5a, 0xd6, 0x22, 0xed, 0x90, 0x2b, 0x98, 0xb6, 0x2c, 0x05, 0x9a, 0xb4, 0x2e, 0x8e,
	0xe1, 0x83, 0xa4, 0x7d, 0xdf, 0xd1, 0x0e, 0xf9, 0x04, 0xf1, 0xe1, 0x67, 0xe6, 0x51, 0xa3, 0x86,
	0x13, 0x9f, 0x14, 0x45, 0x3b, 0x75, 0xaf, 0x7c, 0x46, 0x34, 0xbd, 0xf2, 0x14, 0x34, 0xbd, 0xf2,
	0x54, 0xd0, 0x0e, 0xc9, 0x61, 0xe8, 0xb1, 0xce, 0x34, 0xf1, 0x9a, 0x79, 0x38, 0x4b, 0xfc, 0xde,
	0xa3, 0x9d, 0xf3, 0xbe, 0xf9, 0xea, 0x3f, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x28, 0x40,
	0x4a, 0x15, 0x08, 0x00, 0x00,
}
