// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user_info.proto

package user_info

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//用户信息  忽略某些数据sql:"-"
type UserInf struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=nike_name,json=nikeName,proto3" json:"nike_name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	UserStats            uint64   `protobuf:"varint,5,opt,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	IdentityCardType     uint64   `protobuf:"varint,6,opt,name=identity_card_type,json=identityCardType,proto3" json:"identity_card_type,omitempty"`
	IdentityCardNo       string   `protobuf:"bytes,7,opt,name=identity_card_no,json=identityCardNo,proto3" json:"identity_card_no,omitempty"`
	MobilePhone          string   `protobuf:"bytes,8,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	UserEmail            string   `protobuf:"bytes,9,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Gender               string   `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	UserPoint            uint64   `protobuf:"varint,11,opt,name=user_point,json=userPoint,proto3" json:"user_point,omitempty"`
	RegisterTime         string   `protobuf:"bytes,12,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	Birthday             string   `protobuf:"bytes,13,opt,name=birthday,proto3" json:"birthday,omitempty"`
	ModifiedTime         string   `protobuf:"bytes,14,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInf) Reset()         { *m = UserInf{} }
func (m *UserInf) String() string { return proto.CompactTextString(m) }
func (*UserInf) ProtoMessage()    {}
func (*UserInf) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{1}
}

func (m *UserInf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInf.Unmarshal(m, b)
}
func (m *UserInf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInf.Marshal(b, m, deterministic)
}
func (m *UserInf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInf.Merge(m, src)
}
func (m *UserInf) XXX_Size() int {
	return xxx_messageInfo_UserInf.Size(m)
}
func (m *UserInf) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInf.DiscardUnknown(m)
}

var xxx_messageInfo_UserInf proto.InternalMessageInfo

func (m *UserInf) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInf) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *UserInf) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInf) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInf) GetUserStats() uint64 {
	if m != nil {
		return m.UserStats
	}
	return 0
}

func (m *UserInf) GetIdentityCardType() uint64 {
	if m != nil {
		return m.IdentityCardType
	}
	return 0
}

func (m *UserInf) GetIdentityCardNo() string {
	if m != nil {
		return m.IdentityCardNo
	}
	return ""
}

func (m *UserInf) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *UserInf) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *UserInf) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInf) GetUserPoint() uint64 {
	if m != nil {
		return m.UserPoint
	}
	return 0
}

func (m *UserInf) GetRegisterTime() string {
	if m != nil {
		return m.RegisterTime
	}
	return ""
}

func (m *UserInf) GetBirthday() string {
	if m != nil {
		return m.Birthday
	}
	return ""
}

func (m *UserInf) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

type InDoneUserLogin struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MobilePhone          string   `protobuf:"bytes,3,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	VerificationCode     string   `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	LoginType            uint64   `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InDoneUserLogin) Reset()         { *m = InDoneUserLogin{} }
func (m *InDoneUserLogin) String() string { return proto.CompactTextString(m) }
func (*InDoneUserLogin) ProtoMessage()    {}
func (*InDoneUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{2}
}

func (m *InDoneUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InDoneUserLogin.Unmarshal(m, b)
}
func (m *InDoneUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InDoneUserLogin.Marshal(b, m, deterministic)
}
func (m *InDoneUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InDoneUserLogin.Merge(m, src)
}
func (m *InDoneUserLogin) XXX_Size() int {
	return xxx_messageInfo_InDoneUserLogin.Size(m)
}
func (m *InDoneUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_InDoneUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_InDoneUserLogin proto.InternalMessageInfo

func (m *InDoneUserLogin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *InDoneUserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InDoneUserLogin) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *InDoneUserLogin) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *InDoneUserLogin) GetLoginType() uint64 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

type OutDoneUserLogin struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,3,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutDoneUserLogin) Reset()         { *m = OutDoneUserLogin{} }
func (m *OutDoneUserLogin) String() string { return proto.CompactTextString(m) }
func (*OutDoneUserLogin) ProtoMessage()    {}
func (*OutDoneUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{3}
}

func (m *OutDoneUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutDoneUserLogin.Unmarshal(m, b)
}
func (m *OutDoneUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutDoneUserLogin.Marshal(b, m, deterministic)
}
func (m *OutDoneUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutDoneUserLogin.Merge(m, src)
}
func (m *OutDoneUserLogin) XXX_Size() int {
	return xxx_messageInfo_OutDoneUserLogin.Size(m)
}
func (m *OutDoneUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OutDoneUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OutDoneUserLogin proto.InternalMessageInfo

func (m *OutDoneUserLogin) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutDoneUserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OutDoneUserLogin) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InGetUserInfo struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MobilePhone          string   `protobuf:"bytes,2,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetUserInfo) Reset()         { *m = InGetUserInfo{} }
func (m *InGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*InGetUserInfo) ProtoMessage()    {}
func (*InGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{4}
}

func (m *InGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetUserInfo.Unmarshal(m, b)
}
func (m *InGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetUserInfo.Marshal(b, m, deterministic)
}
func (m *InGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetUserInfo.Merge(m, src)
}
func (m *InGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_InGetUserInfo.Size(m)
}
func (m *InGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InGetUserInfo proto.InternalMessageInfo

func (m *InGetUserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *InGetUserInfo) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *InGetUserInfo) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type OutGetUserInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,2,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutGetUserInfo) Reset()         { *m = OutGetUserInfo{} }
func (m *OutGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*OutGetUserInfo) ProtoMessage()    {}
func (*OutGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{5}
}

func (m *OutGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetUserInfo.Unmarshal(m, b)
}
func (m *OutGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetUserInfo.Marshal(b, m, deterministic)
}
func (m *OutGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetUserInfo.Merge(m, src)
}
func (m *OutGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_OutGetUserInfo.Size(m)
}
func (m *OutGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetUserInfo proto.InternalMessageInfo

func (m *OutGetUserInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutGetUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

func (m *OutGetUserInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type InGetUserInfoList struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetUserInfoList) Reset()         { *m = InGetUserInfoList{} }
func (m *InGetUserInfoList) String() string { return proto.CompactTextString(m) }
func (*InGetUserInfoList) ProtoMessage()    {}
func (*InGetUserInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{6}
}

func (m *InGetUserInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetUserInfoList.Unmarshal(m, b)
}
func (m *InGetUserInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetUserInfoList.Marshal(b, m, deterministic)
}
func (m *InGetUserInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetUserInfoList.Merge(m, src)
}
func (m *InGetUserInfoList) XXX_Size() int {
	return xxx_messageInfo_InGetUserInfoList.Size(m)
}
func (m *InGetUserInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetUserInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_InGetUserInfoList proto.InternalMessageInfo

func (m *InGetUserInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *InGetUserInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *InGetUserInfoList) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *InGetUserInfoList) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *InGetUserInfoList) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type OutGetUserInfoList struct {
	Error                *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64      `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserInfList          []*UserInf `protobuf:"bytes,5,rep,name=user_inf_list,json=userInfList,proto3" json:"user_inf_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OutGetUserInfoList) Reset()         { *m = OutGetUserInfoList{} }
func (m *OutGetUserInfoList) String() string { return proto.CompactTextString(m) }
func (*OutGetUserInfoList) ProtoMessage()    {}
func (*OutGetUserInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{7}
}

func (m *OutGetUserInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetUserInfoList.Unmarshal(m, b)
}
func (m *OutGetUserInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetUserInfoList.Marshal(b, m, deterministic)
}
func (m *OutGetUserInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetUserInfoList.Merge(m, src)
}
func (m *OutGetUserInfoList) XXX_Size() int {
	return xxx_messageInfo_OutGetUserInfoList.Size(m)
}
func (m *OutGetUserInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetUserInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetUserInfoList proto.InternalMessageInfo

func (m *OutGetUserInfoList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutGetUserInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OutGetUserInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *OutGetUserInfoList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OutGetUserInfoList) GetUserInfList() []*UserInf {
	if m != nil {
		return m.UserInfList
	}
	return nil
}

type InUpdateUserInfo struct {
	UserInf              *UserInf `protobuf:"bytes,1,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InUpdateUserInfo) Reset()         { *m = InUpdateUserInfo{} }
func (m *InUpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*InUpdateUserInfo) ProtoMessage()    {}
func (*InUpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{8}
}

func (m *InUpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InUpdateUserInfo.Unmarshal(m, b)
}
func (m *InUpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InUpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *InUpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InUpdateUserInfo.Merge(m, src)
}
func (m *InUpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_InUpdateUserInfo.Size(m)
}
func (m *InUpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InUpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InUpdateUserInfo proto.InternalMessageInfo

func (m *InUpdateUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type OutUpdateUserInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,2,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutUpdateUserInfo) Reset()         { *m = OutUpdateUserInfo{} }
func (m *OutUpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*OutUpdateUserInfo) ProtoMessage()    {}
func (*OutUpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{9}
}

func (m *OutUpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutUpdateUserInfo.Unmarshal(m, b)
}
func (m *OutUpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutUpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *OutUpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutUpdateUserInfo.Merge(m, src)
}
func (m *OutUpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_OutUpdateUserInfo.Size(m)
}
func (m *OutUpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutUpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutUpdateUserInfo proto.InternalMessageInfo

func (m *OutUpdateUserInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutUpdateUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InDoneUserRegister struct {
	Userinf              *UserInf `protobuf:"bytes,1,opt,name=userinf,proto3" json:"userinf,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	VerificationPhone    string   `protobuf:"bytes,3,opt,name=verification_phone,json=verificationPhone,proto3" json:"verification_phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InDoneUserRegister) Reset()         { *m = InDoneUserRegister{} }
func (m *InDoneUserRegister) String() string { return proto.CompactTextString(m) }
func (*InDoneUserRegister) ProtoMessage()    {}
func (*InDoneUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{10}
}

func (m *InDoneUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InDoneUserRegister.Unmarshal(m, b)
}
func (m *InDoneUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InDoneUserRegister.Marshal(b, m, deterministic)
}
func (m *InDoneUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InDoneUserRegister.Merge(m, src)
}
func (m *InDoneUserRegister) XXX_Size() int {
	return xxx_messageInfo_InDoneUserRegister.Size(m)
}
func (m *InDoneUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_InDoneUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_InDoneUserRegister proto.InternalMessageInfo

func (m *InDoneUserRegister) GetUserinf() *UserInf {
	if m != nil {
		return m.Userinf
	}
	return nil
}

func (m *InDoneUserRegister) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *InDoneUserRegister) GetVerificationPhone() string {
	if m != nil {
		return m.VerificationPhone
	}
	return ""
}

type OutDoneUserRegister struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,3,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutDoneUserRegister) Reset()         { *m = OutDoneUserRegister{} }
func (m *OutDoneUserRegister) String() string { return proto.CompactTextString(m) }
func (*OutDoneUserRegister) ProtoMessage()    {}
func (*OutDoneUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{11}
}

func (m *OutDoneUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutDoneUserRegister.Unmarshal(m, b)
}
func (m *OutDoneUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutDoneUserRegister.Marshal(b, m, deterministic)
}
func (m *OutDoneUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutDoneUserRegister.Merge(m, src)
}
func (m *OutDoneUserRegister) XXX_Size() int {
	return xxx_messageInfo_OutDoneUserRegister.Size(m)
}
func (m *OutDoneUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_OutDoneUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_OutDoneUserRegister proto.InternalMessageInfo

func (m *OutDoneUserRegister) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OutDoneUserRegister) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutDoneUserRegister) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InGetVerificationCode struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Telephone            string   `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetVerificationCode) Reset()         { *m = InGetVerificationCode{} }
func (m *InGetVerificationCode) String() string { return proto.CompactTextString(m) }
func (*InGetVerificationCode) ProtoMessage()    {}
func (*InGetVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{12}
}

func (m *InGetVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetVerificationCode.Unmarshal(m, b)
}
func (m *InGetVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetVerificationCode.Marshal(b, m, deterministic)
}
func (m *InGetVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetVerificationCode.Merge(m, src)
}
func (m *InGetVerificationCode) XXX_Size() int {
	return xxx_messageInfo_InGetVerificationCode.Size(m)
}
func (m *InGetVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_InGetVerificationCode proto.InternalMessageInfo

func (m *InGetVerificationCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InGetVerificationCode) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

type OutGetVerificationCode struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutGetVerificationCode) Reset()         { *m = OutGetVerificationCode{} }
func (m *OutGetVerificationCode) String() string { return proto.CompactTextString(m) }
func (*OutGetVerificationCode) ProtoMessage()    {}
func (*OutGetVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_84fe32b1d3884b9c, []int{13}
}

func (m *OutGetVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetVerificationCode.Unmarshal(m, b)
}
func (m *OutGetVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetVerificationCode.Marshal(b, m, deterministic)
}
func (m *OutGetVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetVerificationCode.Merge(m, src)
}
func (m *OutGetVerificationCode) XXX_Size() int {
	return xxx_messageInfo_OutGetVerificationCode.Size(m)
}
func (m *OutGetVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetVerificationCode proto.InternalMessageInfo

func (m *OutGetVerificationCode) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "user_info.Error")
	proto.RegisterType((*UserInf)(nil), "user_info.User_inf")
	proto.RegisterType((*InDoneUserLogin)(nil), "user_info.In_doneUserLogin")
	proto.RegisterType((*OutDoneUserLogin)(nil), "user_info.Out_doneUserLogin")
	proto.RegisterType((*InGetUserInfo)(nil), "user_info.In_getUserInfo")
	proto.RegisterType((*OutGetUserInfo)(nil), "user_info.Out_getUserInfo")
	proto.RegisterType((*InGetUserInfoList)(nil), "user_info.In_getUserInfoList")
	proto.RegisterType((*OutGetUserInfoList)(nil), "user_info.Out_getUserInfoList")
	proto.RegisterType((*InUpdateUserInfo)(nil), "user_info.In_updateUserInfo")
	proto.RegisterType((*OutUpdateUserInfo)(nil), "user_info.Out_updateUserInfo")
	proto.RegisterType((*InDoneUserRegister)(nil), "user_info.In_doneUserRegister")
	proto.RegisterType((*OutDoneUserRegister)(nil), "user_info.Out_doneUserRegister")
	proto.RegisterType((*InGetVerificationCode)(nil), "user_info.In_getVerificationCode")
	proto.RegisterType((*OutGetVerificationCode)(nil), "user_info.Out_getVerificationCode")
}

func init() { proto.RegisterFile("user_info.proto", fileDescriptor_84fe32b1d3884b9c) }

var fileDescriptor_84fe32b1d3884b9c = []byte{
	// 911 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0xf6, 0x78, 0xe2, 0xc4, 0x2e, 0xe7, 0xc7, 0xe9, 0x44, 0xbb, 0xb3, 0x26, 0x59, 0xbc, 0x8d,
	0xb4, 0x8a, 0x04, 0x9b, 0x43, 0x10, 0xe2, 0x8c, 0xb2, 0x4b, 0x64, 0x88, 0x76, 0xa3, 0x21, 0xe1,
	0xc8, 0x68, 0x92, 0xa9, 0x38, 0xad, 0x8c, 0xbb, 0xad, 0x99, 0x0e, 0xc8, 0x27, 0x84, 0xc4, 0x4b,
	0x70, 0xe3, 0x31, 0x10, 0x2f, 0xc1, 0x0b, 0x71, 0x40, 0x5d, 0x3d, 0xe3, 0xf4, 0x8c, 0xed, 0xe0,
	0xbd, 0xa5, 0x7e, 0xfa, 0x73, 0xd5, 0x57, 0x5f, 0xd5, 0x04, 0x76, 0x1e, 0x72, 0xcc, 0x22, 0x21,
	0x6f, 0xd5, 0xf1, 0x24, 0x53, 0x5a, 0xb1, 0xce, 0xcc, 0xc1, 0xbf, 0x82, 0xd6, 0xbb, 0x2c, 0x53,
	0x19, 0x63, 0xb0, 0x76, 0xa3, 0x12, 0x0c, 0xbc, 0x81, 0x77, 0xd4, 0x0a, 0xe9, 0x6f, 0x16, 0xc0,
	0xc6, 0x18, 0xf3, 0x3c, 0x1e, 0x61, 0xd0, 0x1c, 0x78, 0x47, 0x9d, 0xb0, 0x34, 0xf9, 0x3f, 0x3e,
	0xb4, 0xaf, 0x0a, 0x10, 0xf6, 0x1c, 0x36, 0x2c, 0x60, 0x42, 0xaf, 0xfd, 0x70, 0xdd, 0x98, 0xc3,
	0x84, 0x7d, 0x02, 0x1d, 0x29, 0xee, 0x31, 0x92, 0xf1, 0xb8, 0x44, 0x68, 0x1b, 0xc7, 0xfb, 0x78,
	0x8c, 0x26, 0x48, 0xaf, 0x28, 0xe8, 0xdb, 0xa0, 0x71, 0x50, 0xb0, 0x0f, 0xed, 0x49, 0x9c, 0xe7,
	0xbf, 0xa8, 0x2c, 0x09, 0xd6, 0x6c, 0xac, 0xb4, 0xd9, 0x21, 0x00, 0x3d, 0xcc, 0x75, 0xac, 0xf3,
	0xa0, 0x35, 0xf0, 0x8e, 0xd6, 0x42, 0x82, 0xfa, 0xc1, 0x38, 0xd8, 0x17, 0xc0, 0x44, 0x82, 0x52,
	0x0b, 0x3d, 0x8d, 0x6e, 0xe2, 0x2c, 0x89, 0xf4, 0x74, 0x82, 0xc1, 0x3a, 0xa5, 0xf5, 0xca, 0xc8,
	0x69, 0x9c, 0x25, 0x97, 0xd3, 0x09, 0xb2, 0x23, 0xe8, 0x55, 0xb3, 0xa5, 0x0a, 0x36, 0xe8, 0x07,
	0xb7, 0xdd, 0xdc, 0xf7, 0x8a, 0xbd, 0x82, 0xcd, 0xb1, 0xba, 0x16, 0x29, 0x46, 0x93, 0x3b, 0x25,
	0x31, 0x68, 0x53, 0x56, 0xd7, 0xfa, 0x2e, 0x8c, 0x6b, 0x56, 0x19, 0x8e, 0x63, 0x91, 0x06, 0x1d,
	0x4a, 0xa0, 0xca, 0xde, 0x19, 0x07, 0x7b, 0x06, 0xeb, 0x23, 0x94, 0x09, 0x66, 0x01, 0x50, 0xa8,
	0xb0, 0x66, 0xcf, 0x26, 0x4a, 0x48, 0x1d, 0x74, 0x1f, 0x1b, 0xba, 0x30, 0x0e, 0xf6, 0x19, 0x6c,
	0x65, 0x38, 0x12, 0xb9, 0xc6, 0x2c, 0xd2, 0x62, 0x8c, 0xc1, 0x26, 0xbd, 0xde, 0x2c, 0x9d, 0x97,
	0xc2, 0x12, 0x76, 0x2d, 0x32, 0x7d, 0x97, 0xc4, 0xd3, 0x60, 0xcb, 0x12, 0x56, 0xda, 0x06, 0x60,
	0xac, 0x12, 0x71, 0x2b, 0x30, 0xb1, 0x00, 0xdb, 0x16, 0xa0, 0x74, 0x1a, 0x00, 0xfe, 0xb7, 0x07,
	0xbd, 0xa1, 0x8c, 0x12, 0x25, 0xd1, 0x0c, 0xf6, 0x5c, 0x8d, 0x84, 0xac, 0xce, 0xc8, 0x7b, 0x62,
	0x46, 0xcd, 0xda, 0x8c, 0xea, 0x64, 0xf9, 0xf3, 0x64, 0x7d, 0x0e, 0xbb, 0x3f, 0x63, 0x26, 0x6e,
	0xc5, 0x4d, 0xac, 0x85, 0x92, 0x11, 0xa9, 0xcf, 0xce, 0xba, 0xe7, 0x06, 0x4e, 0x8d, 0x12, 0x0f,
	0x01, 0x52, 0x53, 0x91, 0x1d, 0x66, 0x31, 0x73, 0xf2, 0x98, 0x29, 0xf2, 0xdf, 0x3c, 0xd8, 0xfd,
	0xf0, 0xa0, 0x6b, 0xd5, 0xbf, 0x2e, 0xb4, 0x4d, 0x95, 0x77, 0x4f, 0x7a, 0xc7, 0x8f, 0x7b, 0x40,
	0xfe, 0xb0, 0x90, 0xfe, 0x3e, 0xb4, 0xb4, 0xba, 0x47, 0x59, 0x74, 0x61, 0x0d, 0x76, 0x0c, 0xed,
	0x32, 0x9f, 0xca, 0xef, 0x9e, 0xec, 0x39, 0x00, 0xa5, 0xf8, 0x43, 0x92, 0xfe, 0x50, 0xde, 0x72,
	0x01, 0xdb, 0x43, 0x19, 0x8d, 0x50, 0x5f, 0x59, 0x87, 0x7a, 0x9a, 0xbd, 0x3a, 0x43, 0xcd, 0x79,
	0x86, 0x9c, 0xbd, 0xf2, 0xdd, 0xbd, 0xe2, 0xbf, 0xc2, 0x8e, 0xe9, 0xd6, 0xfd, 0xad, 0xd7, 0xd0,
	0xc2, 0xa7, 0x7b, 0xa5, 0x70, 0xa5, 0xab, 0xe6, 0xff, 0x77, 0x65, 0xb8, 0xc9, 0x54, 0x8a, 0x79,
	0xe0, 0x0f, 0x7c, 0xc3, 0x0d, 0x19, 0xfc, 0x0f, 0x0f, 0x58, 0xb5, 0xd9, 0x73, 0x91, 0x6b, 0x93,
	0x9c, 0x8a, 0xb1, 0xd0, 0xc5, 0x19, 0xb0, 0x86, 0xf1, 0x4e, 0xe2, 0x11, 0xe6, 0xf4, 0x7b, 0x7e,
	0x68, 0x0d, 0x33, 0xd1, 0x1c, 0xe3, 0xec, 0xe6, 0x2e, 0xba, 0xc7, 0x69, 0xa1, 0x8f, 0x8e, 0xf5,
	0x7c, 0x8f, 0x53, 0x0a, 0xeb, 0x38, 0xd3, 0x56, 0xb0, 0x6b, 0x45, 0xd8, 0x78, 0x48, 0xee, 0x2f,
	0xa0, 0x8d, 0xb2, 0x50, 0x73, 0xcb, 0x9e, 0x26, 0x94, 0x56, 0xc8, 0x7f, 0x79, 0xb0, 0x57, 0x63,
	0x87, 0x8a, 0x5b, 0x95, 0xa1, 0x59, 0x13, 0xcd, 0x85, 0x4d, 0xf8, 0x6e, 0x13, 0xa4, 0x1c, 0x1d,
	0xa7, 0x54, 0xa0, 0x1f, 0x5a, 0x83, 0x7d, 0x0d, 0x5b, 0x25, 0x76, 0x94, 0x8a, 0x5c, 0x07, 0xad,
	0x81, 0xbf, 0x8c, 0xe8, 0x6e, 0x41, 0xb4, 0x29, 0x91, 0x9f, 0xc2, 0xee, 0x50, 0x46, 0x0f, 0x93,
	0x24, 0xd6, 0x38, 0x9b, 0xac, 0x3b, 0x31, 0x6f, 0x05, 0x1d, 0xa6, 0xc0, 0x4c, 0xfb, 0x35, 0x94,
	0x55, 0x77, 0xe1, 0x23, 0xf5, 0xc1, 0xff, 0xf4, 0x60, 0xcf, 0x39, 0x1b, 0x61, 0x71, 0x93, 0xd8,
	0x1b, 0xab, 0xdd, 0x55, 0x8a, 0x36, 0x9f, 0x90, 0x85, 0xc7, 0xa0, 0xb9, 0xe4, 0x18, 0xbc, 0x01,
	0x56, 0x49, 0x76, 0x4f, 0x4c, 0x05, 0x86, 0xd6, 0x88, 0xff, 0xee, 0xc1, 0xbe, 0x7b, 0x1c, 0x66,
	0x35, 0xee, 0x43, 0xeb, 0x92, 0xf6, 0xde, 0xee, 0xa6, 0x35, 0x1e, 0x99, 0x6a, 0xae, 0xce, 0xd4,
	0x2a, 0xf7, 0xe1, 0x3b, 0x78, 0x66, 0x57, 0xe6, 0xc7, 0x7a, 0x3f, 0xee, 0xa7, 0xb7, 0x53, 0x7c,
	0x7a, 0x0f, 0xa0, 0xa3, 0x31, 0x45, 0xf7, 0x36, 0x3c, 0x3a, 0xf8, 0x37, 0xf0, 0xbc, 0x90, 0xf8,
	0x1c, 0xd8, 0x8a, 0x83, 0x3e, 0xf9, 0xb7, 0xf8, 0x82, 0x93, 0x3a, 0xce, 0x61, 0xeb, 0x6d, 0xf5,
	0xf0, 0x3b, 0xcf, 0xea, 0x5f, 0x85, 0xfe, 0x81, 0x13, 0x9c, 0xbb, 0xba, 0xbc, 0xc1, 0xbe, 0x85,
	0xee, 0x99, 0x73, 0x9a, 0x5e, 0x54, 0xb1, 0x9c, 0xbd, 0xec, 0xf7, 0x6b, 0x48, 0x4e, 0x8c, 0x37,
	0x58, 0x08, 0x3b, 0x67, 0xb5, 0x25, 0x3e, 0x5c, 0x8a, 0x65, 0xc2, 0xfd, 0x97, 0xcb, 0xf1, 0x68,
	0xc1, 0x1a, 0xec, 0x03, 0x6c, 0x5f, 0x55, 0x37, 0xe3, 0xa0, 0x0a, 0x59, 0xdd, 0x9b, 0xfe, 0x61,
	0x0d, 0xb1, 0x1a, 0xe6, 0x0d, 0x76, 0x05, 0xbd, 0xb7, 0x75, 0x61, 0xbd, 0x5c, 0xcc, 0x5e, 0x19,
	0xef, 0x7f, 0xba, 0x84, 0xc0, 0x32, 0x81, 0x37, 0xd8, 0x4f, 0xb0, 0x77, 0xb6, 0x60, 0xba, 0xaf,
	0xe6, 0xfa, 0xaf, 0xa7, 0xf4, 0xf9, 0x3c, 0x07, 0xf5, 0x1c, 0xde, 0xb8, 0x5e, 0xa7, 0xff, 0x04,
	0xbf, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x55, 0xaa, 0x0a, 0x1c, 0x0a, 0x00, 0x00,
}
