// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: es.proto

package com_surprise_shop_srv_es

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	product_es "product_es"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProductEsHandler service

type ProductEsHandlerService interface {
	//获取信息
	GetProductById(ctx context.Context, in *product_es.In_GetProductById, opts ...client.CallOption) (*product_es.Out_GetProductById, error)
	//修改信息
	UpdateProductInfo(ctx context.Context, in *product_es.In_UpdateProductInfo, opts ...client.CallOption) (*product_es.Out_UpdateProductInfo, error)
	//获取列表
	GetProducts(ctx context.Context, in *product_es.In_GetProducts, opts ...client.CallOption) (*product_es.Out_GetProducts, error)
	//删除列表
	DeleteProducts(ctx context.Context, in *product_es.In_DeleteProducts, opts ...client.CallOption) (*product_es.Out_DeleteProducts, error)
	//新建信息
	CreateProduct(ctx context.Context, in *product_es.In_CreateProduct, opts ...client.CallOption) (*product_es.Out_CreateProduct, error)
}

type productEsHandlerService struct {
	c    client.Client
	name string
}

func NewProductEsHandlerService(name string, c client.Client) ProductEsHandlerService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "com.surprise.shop.srv.es"
	}
	return &productEsHandlerService{
		c:    c,
		name: name,
	}
}

func (c *productEsHandlerService) GetProductById(ctx context.Context, in *product_es.In_GetProductById, opts ...client.CallOption) (*product_es.Out_GetProductById, error) {
	req := c.c.NewRequest(c.name, "ProductEsHandler.GetProductById", in)
	out := new(product_es.Out_GetProductById)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productEsHandlerService) UpdateProductInfo(ctx context.Context, in *product_es.In_UpdateProductInfo, opts ...client.CallOption) (*product_es.Out_UpdateProductInfo, error) {
	req := c.c.NewRequest(c.name, "ProductEsHandler.UpdateProductInfo", in)
	out := new(product_es.Out_UpdateProductInfo)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productEsHandlerService) GetProducts(ctx context.Context, in *product_es.In_GetProducts, opts ...client.CallOption) (*product_es.Out_GetProducts, error) {
	req := c.c.NewRequest(c.name, "ProductEsHandler.GetProducts", in)
	out := new(product_es.Out_GetProducts)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productEsHandlerService) DeleteProducts(ctx context.Context, in *product_es.In_DeleteProducts, opts ...client.CallOption) (*product_es.Out_DeleteProducts, error) {
	req := c.c.NewRequest(c.name, "ProductEsHandler.DeleteProducts", in)
	out := new(product_es.Out_DeleteProducts)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *productEsHandlerService) CreateProduct(ctx context.Context, in *product_es.In_CreateProduct, opts ...client.CallOption) (*product_es.Out_CreateProduct, error) {
	req := c.c.NewRequest(c.name, "ProductEsHandler.CreateProduct", in)
	out := new(product_es.Out_CreateProduct)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProductEsHandler service

type ProductEsHandlerHandler interface {
	//获取信息
	GetProductById(context.Context, *product_es.In_GetProductById, *product_es.Out_GetProductById) error
	//修改信息
	UpdateProductInfo(context.Context, *product_es.In_UpdateProductInfo, *product_es.Out_UpdateProductInfo) error
	//获取列表
	GetProducts(context.Context, *product_es.In_GetProducts, *product_es.Out_GetProducts) error
	//删除列表
	DeleteProducts(context.Context, *product_es.In_DeleteProducts, *product_es.Out_DeleteProducts) error
	//新建信息
	CreateProduct(context.Context, *product_es.In_CreateProduct, *product_es.Out_CreateProduct) error
}

func RegisterProductEsHandlerHandler(s server.Server, hdlr ProductEsHandlerHandler, opts ...server.HandlerOption) error {
	type productEsHandler interface {
		GetProductById(ctx context.Context, in *product_es.In_GetProductById, out *product_es.Out_GetProductById) error
		UpdateProductInfo(ctx context.Context, in *product_es.In_UpdateProductInfo, out *product_es.Out_UpdateProductInfo) error
		GetProducts(ctx context.Context, in *product_es.In_GetProducts, out *product_es.Out_GetProducts) error
		DeleteProducts(ctx context.Context, in *product_es.In_DeleteProducts, out *product_es.Out_DeleteProducts) error
		CreateProduct(ctx context.Context, in *product_es.In_CreateProduct, out *product_es.Out_CreateProduct) error
	}
	type ProductEsHandler struct {
		productEsHandler
	}
	h := &productEsHandlerHandler{hdlr}
	return s.Handle(s.NewHandler(&ProductEsHandler{h}, opts...))
}

type productEsHandlerHandler struct {
	ProductEsHandlerHandler
}

func (h *productEsHandlerHandler) GetProductById(ctx context.Context, in *product_es.In_GetProductById, out *product_es.Out_GetProductById) error {
	return h.ProductEsHandlerHandler.GetProductById(ctx, in, out)
}

func (h *productEsHandlerHandler) UpdateProductInfo(ctx context.Context, in *product_es.In_UpdateProductInfo, out *product_es.Out_UpdateProductInfo) error {
	return h.ProductEsHandlerHandler.UpdateProductInfo(ctx, in, out)
}

func (h *productEsHandlerHandler) GetProducts(ctx context.Context, in *product_es.In_GetProducts, out *product_es.Out_GetProducts) error {
	return h.ProductEsHandlerHandler.GetProducts(ctx, in, out)
}

func (h *productEsHandlerHandler) DeleteProducts(ctx context.Context, in *product_es.In_DeleteProducts, out *product_es.Out_DeleteProducts) error {
	return h.ProductEsHandlerHandler.DeleteProducts(ctx, in, out)
}

func (h *productEsHandlerHandler) CreateProduct(ctx context.Context, in *product_es.In_CreateProduct, out *product_es.Out_CreateProduct) error {
	return h.ProductEsHandlerHandler.CreateProduct(ctx, in, out)
}
